// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Valle.TpvFinal {
    
    
    public partial class ArqueoCaja {
        
        private Gtk.VBox vbox1;
        
        private Valle.GtkUtilidades.MiLabel txtTitulo;
        
        private Gtk.Table pneBotonera;
        
        private void vbox18;
        
        private void vbox19;
        
        private void vbox20;
        
        private void vbox21;
        
        private void vbox22;
        
        private void vbox23;
        
        private void vbox24;
        
        private void vbox25;
        
        private void vbox26;
        
        private void vbox27;
        
        private void vbox28;
        
        private void vbox29;
        
        private void vbox30;
        
        private void vbox31;
        
        private Gtk.HButtonBox hbuttonbox1;
        
        private Gtk.Button btnCancelar;
        
        private Gtk.VBox vbox3;
        
        private Gtk.Image image14;
        
        private Gtk.Label label2;
        
        private Gtk.Button btnAceptar;
        
        private Gtk.VBox vbox2;
        
        private Gtk.Image image29;
        
        private Gtk.Label label1;
        
        protected virtual void Build() {
            Stetic.Gui.Initialize(this);
            // Widget Valle.TpvFinal.ArqueoCaja
            this.Name = "Valle.TpvFinal.ArqueoCaja";
            this.Title = Mono.Unix.Catalog.GetString("ArqueoCaja");
            this.WindowPosition = ((Gtk.WindowPosition)(4));
            // Container child Valle.TpvFinal.ArqueoCaja.Gtk.Container+ContainerChild
            this.vbox1 = new Gtk.VBox();
            this.vbox1.Name = "vbox1";
            this.vbox1.Spacing = 6;
            this.vbox1.BorderWidth = ((uint)(12));
            // Container child vbox1.Gtk.Box+BoxChild
            this.txtTitulo = new Valle.GtkUtilidades.MiLabel();
            this.txtTitulo.HeightRequest = 25;
            this.txtTitulo.Events = ((Gdk.EventMask)(256));
            this.txtTitulo.Name = "txtTitulo";
            this.vbox1.Add(this.txtTitulo);
            Gtk.Box.BoxChild w1 = ((Gtk.Box.BoxChild)(this.vbox1[this.txtTitulo]));
            w1.Position = 0;
            w1.Expand = false;
            w1.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.pneBotonera = new Gtk.Table(((uint)(3)), ((uint)(5)), false);
            this.pneBotonera.Name = "pneBotonera";
            this.pneBotonera.RowSpacing = ((uint)(6));
            this.pneBotonera.ColumnSpacing = ((uint)(6));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox18 = null;
            this.pneBotonera.Add(this.vbox18);
            Gtk.Table.TableChild w2 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox18]));
            w2.XOptions = ((Gtk.AttachOptions)(4));
            w2.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox19 = null;
            this.pneBotonera.Add(this.vbox19);
            Gtk.Table.TableChild w3 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox19]));
            w3.LeftAttach = ((uint)(1));
            w3.RightAttach = ((uint)(2));
            w3.XOptions = ((Gtk.AttachOptions)(4));
            w3.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox20 = null;
            this.pneBotonera.Add(this.vbox20);
            Gtk.Table.TableChild w4 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox20]));
            w4.LeftAttach = ((uint)(2));
            w4.RightAttach = ((uint)(3));
            w4.XOptions = ((Gtk.AttachOptions)(4));
            w4.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox21 = null;
            this.pneBotonera.Add(this.vbox21);
            Gtk.Table.TableChild w5 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox21]));
            w5.LeftAttach = ((uint)(3));
            w5.RightAttach = ((uint)(4));
            w5.XOptions = ((Gtk.AttachOptions)(4));
            w5.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox22 = null;
            this.pneBotonera.Add(this.vbox22);
            Gtk.Table.TableChild w6 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox22]));
            w6.LeftAttach = ((uint)(4));
            w6.RightAttach = ((uint)(5));
            w6.XOptions = ((Gtk.AttachOptions)(4));
            w6.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox23 = null;
            this.pneBotonera.Add(this.vbox23);
            Gtk.Table.TableChild w7 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox23]));
            w7.TopAttach = ((uint)(1));
            w7.BottomAttach = ((uint)(2));
            w7.XOptions = ((Gtk.AttachOptions)(4));
            w7.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox24 = null;
            this.pneBotonera.Add(this.vbox24);
            Gtk.Table.TableChild w8 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox24]));
            w8.TopAttach = ((uint)(1));
            w8.BottomAttach = ((uint)(2));
            w8.LeftAttach = ((uint)(1));
            w8.RightAttach = ((uint)(2));
            w8.XOptions = ((Gtk.AttachOptions)(4));
            w8.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox25 = null;
            this.pneBotonera.Add(this.vbox25);
            Gtk.Table.TableChild w9 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox25]));
            w9.TopAttach = ((uint)(1));
            w9.BottomAttach = ((uint)(2));
            w9.LeftAttach = ((uint)(2));
            w9.RightAttach = ((uint)(3));
            w9.XOptions = ((Gtk.AttachOptions)(4));
            w9.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox26 = null;
            this.pneBotonera.Add(this.vbox26);
            Gtk.Table.TableChild w10 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox26]));
            w10.TopAttach = ((uint)(1));
            w10.BottomAttach = ((uint)(2));
            w10.LeftAttach = ((uint)(3));
            w10.RightAttach = ((uint)(4));
            w10.XOptions = ((Gtk.AttachOptions)(4));
            w10.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox27 = null;
            this.pneBotonera.Add(this.vbox27);
            Gtk.Table.TableChild w11 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox27]));
            w11.TopAttach = ((uint)(1));
            w11.BottomAttach = ((uint)(2));
            w11.LeftAttach = ((uint)(4));
            w11.RightAttach = ((uint)(5));
            w11.XOptions = ((Gtk.AttachOptions)(4));
            w11.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox28 = null;
            this.pneBotonera.Add(this.vbox28);
            Gtk.Table.TableChild w12 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox28]));
            w12.TopAttach = ((uint)(2));
            w12.BottomAttach = ((uint)(3));
            w12.XOptions = ((Gtk.AttachOptions)(4));
            w12.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox29 = null;
            this.pneBotonera.Add(this.vbox29);
            Gtk.Table.TableChild w13 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox29]));
            w13.TopAttach = ((uint)(2));
            w13.BottomAttach = ((uint)(3));
            w13.LeftAttach = ((uint)(1));
            w13.RightAttach = ((uint)(2));
            w13.XOptions = ((Gtk.AttachOptions)(4));
            w13.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox30 = null;
            this.pneBotonera.Add(this.vbox30);
            Gtk.Table.TableChild w14 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox30]));
            w14.TopAttach = ((uint)(2));
            w14.BottomAttach = ((uint)(3));
            w14.LeftAttach = ((uint)(2));
            w14.RightAttach = ((uint)(3));
            w14.XOptions = ((Gtk.AttachOptions)(4));
            w14.YOptions = ((Gtk.AttachOptions)(4));
            // Container child pneBotonera.Gtk.Table+TableChild
            this.vbox31 = null;
            this.pneBotonera.Add(this.vbox31);
            Gtk.Table.TableChild w15 = ((Gtk.Table.TableChild)(this.pneBotonera[this.vbox31]));
            w15.TopAttach = ((uint)(2));
            w15.BottomAttach = ((uint)(3));
            w15.LeftAttach = ((uint)(3));
            w15.RightAttach = ((uint)(4));
            w15.XOptions = ((Gtk.AttachOptions)(4));
            w15.YOptions = ((Gtk.AttachOptions)(4));
            this.vbox1.Add(this.pneBotonera);
            Gtk.Box.BoxChild w16 = ((Gtk.Box.BoxChild)(this.vbox1[this.pneBotonera]));
            w16.Position = 1;
            w16.Expand = false;
            w16.Fill = false;
            // Container child vbox1.Gtk.Box+BoxChild
            this.hbuttonbox1 = new Gtk.HButtonBox();
            this.hbuttonbox1.Name = "hbuttonbox1";
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.btnCancelar = new Gtk.Button();
            this.btnCancelar.CanFocus = true;
            this.btnCancelar.Name = "btnCancelar";
            // Container child btnCancelar.Gtk.Container+ContainerChild
            this.vbox3 = new Gtk.VBox();
            this.vbox3.Name = "vbox3";
            this.vbox3.Spacing = 6;
            // Container child vbox3.Gtk.Box+BoxChild
            this.image14 = new Gtk.Image();
            this.image14.Name = "image14";
            this.image14.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-cancel", Gtk.IconSize.Dialog, 48);
            this.vbox3.Add(this.image14);
            Gtk.Box.BoxChild w17 = ((Gtk.Box.BoxChild)(this.vbox3[this.image14]));
            w17.Position = 0;
            w17.Expand = false;
            w17.Fill = false;
            // Container child vbox3.Gtk.Box+BoxChild
            this.label2 = new Gtk.Label();
            this.label2.Name = "label2";
            this.label2.LabelProp = Mono.Unix.Catalog.GetString("Cancelar");
            this.vbox3.Add(this.label2);
            Gtk.Box.BoxChild w18 = ((Gtk.Box.BoxChild)(this.vbox3[this.label2]));
            w18.Position = 1;
            w18.Expand = false;
            w18.Fill = false;
            this.btnCancelar.Add(this.vbox3);
            this.btnCancelar.Label = null;
            this.hbuttonbox1.Add(this.btnCancelar);
            Gtk.ButtonBox.ButtonBoxChild w20 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnCancelar]));
            w20.Expand = false;
            w20.Fill = false;
            // Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
            this.btnAceptar = new Gtk.Button();
            this.btnAceptar.CanFocus = true;
            this.btnAceptar.Name = "btnAceptar";
            // Container child btnAceptar.Gtk.Container+ContainerChild
            this.vbox2 = new Gtk.VBox();
            this.vbox2.Name = "vbox2";
            this.vbox2.Spacing = 6;
            // Container child vbox2.Gtk.Box+BoxChild
            this.image29 = new Gtk.Image();
            this.image29.Name = "image29";
            this.image29.Pixbuf = Stetic.IconLoader.LoadIcon(this, "gtk-apply", Gtk.IconSize.Dialog, 48);
            this.vbox2.Add(this.image29);
            Gtk.Box.BoxChild w21 = ((Gtk.Box.BoxChild)(this.vbox2[this.image29]));
            w21.Position = 0;
            w21.Expand = false;
            w21.Fill = false;
            // Container child vbox2.Gtk.Box+BoxChild
            this.label1 = new Gtk.Label();
            this.label1.Name = "label1";
            this.label1.LabelProp = Mono.Unix.Catalog.GetString("Aceptar");
            this.vbox2.Add(this.label1);
            Gtk.Box.BoxChild w22 = ((Gtk.Box.BoxChild)(this.vbox2[this.label1]));
            w22.Position = 1;
            w22.Expand = false;
            w22.Fill = false;
            this.btnAceptar.Add(this.vbox2);
            this.btnAceptar.Label = null;
            this.hbuttonbox1.Add(this.btnAceptar);
            Gtk.ButtonBox.ButtonBoxChild w24 = ((Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnAceptar]));
            w24.Position = 1;
            w24.Expand = false;
            w24.Fill = false;
            this.vbox1.Add(this.hbuttonbox1);
            Gtk.Box.BoxChild w25 = ((Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
            w25.Position = 2;
            w25.Expand = false;
            w25.Fill = false;
            this.Add(this.vbox1);
            if ((this.Child != null)) {
                this.Child.ShowAll();
            }
            this.DefaultWidth = 625;
            this.DefaultHeight = 571;
            this.Show();
            this.ExposeEvent += new Gtk.ExposeEventHandler(this.OnExposeEvent);
            this.btnCancelar.Clicked += new System.EventHandler(this.OnBtnCancelarClicked);
            this.btnAceptar.Clicked += new System.EventHandler(this.OnBtnAceptarClicked);
        }
    }
}
