
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.TpvFinal
{
	public partial class DesgloseTicket
	{
		private global::Gtk.VBox vbox2;

		private global::Valle.GtkUtilidades.MiLabel lblTitulo;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.Button btnDividirTicket;

		private global::Gtk.VBox vbox1;

		private global::Gtk.Image image22;

		private global::Gtk.Label label1;

		private global::Gtk.Button btnSepararTicket;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Image image23;

		private global::Gtk.Label label2;

		private global::Gtk.Button btnLlenarIden;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Image image24;

		private global::Gtk.Label label3;

		private global::Gtk.Button btnInfTicket;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Image image26;

		private global::Gtk.Label label5;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Image image25;

		private global::Gtk.Label label4;

		protected virtual void Init ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.TpvFinal.DesgloseTicket
			this.Name = "Valle.TpvFinal.DesgloseTicket";
			this.Title = global::Mono.Unix.Catalog.GetString ("DesgloseTicket");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Valle.TpvFinal.DesgloseTicket.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			this.vbox2.BorderWidth = ((uint)(12));
			// Container child vbox2.Gtk.Box+BoxChild
			this.lblTitulo = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblTitulo.HeightRequest = 25;
			this.lblTitulo.Events = ((global::Gdk.EventMask)(256));
			this.lblTitulo.Name = "lblTitulo";
			this.vbox2.Add (this.lblTitulo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.lblTitulo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDividirTicket = new global::Gtk.Button ();
			this.btnDividirTicket.WidthRequest = 100;
			this.btnDividirTicket.HeightRequest = 100;
			this.btnDividirTicket.CanFocus = true;
			this.btnDividirTicket.Name = "btnDividirTicket";
			// Container child btnDividirTicket.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.image22 = new global::Gtk.Image ();
			this.image22.Name = "image22";
			this.image22.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/Division_Sign(a).png"));
			this.vbox1.Add (this.image22);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.image22]));
			w2.Position = 0;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Dividir \nTicket");
			this.vbox1.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.label1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.btnDividirTicket.Add (this.vbox1);
			this.btnDividirTicket.Label = null;
			this.hbuttonbox1.Add (this.btnDividirTicket);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnDividirTicket]));
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSepararTicket = new global::Gtk.Button ();
			this.btnSepararTicket.WidthRequest = 100;
			this.btnSepararTicket.HeightRequest = 100;
			this.btnSepararTicket.CanFocus = true;
			this.btnSepararTicket.Name = "btnSepararTicket";
			// Container child btnSepararTicket.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image23 = new global::Gtk.Image ();
			this.image23.Name = "image23";
			this.image23.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/Line Chart.ico"));
			this.vbox3.Add (this.image23);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image23]));
			w6.Position = 0;
			w6.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<big>Separar</big>\n<big> ticket</big>");
			this.label2.UseMarkup = true;
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.btnSepararTicket.Add (this.vbox3);
			this.btnSepararTicket.Label = null;
			this.hbuttonbox1.Add (this.btnSepararTicket);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnSepararTicket]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnLlenarIden = new global::Gtk.Button ();
			this.btnLlenarIden.WidthRequest = 100;
			this.btnLlenarIden.HeightRequest = 100;
			this.btnLlenarIden.CanFocus = true;
			this.btnLlenarIden.Name = "btnLlenarIden";
			// Container child btnLlenarIden.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image24 = new global::Gtk.Image ();
			this.image24.Name = "image24";
			this.image24.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/Camarero muy ceremonioso llevando bandeja.jpg"));
			this.vbox4.Add (this.image24);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.image24]));
			w10.Position = 0;
			w10.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<big>Llenar</big>\n<big> Iden</big>");
			this.label3.UseMarkup = true;
			this.vbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label3]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.btnLlenarIden.Add (this.vbox4);
			this.btnLlenarIden.Label = null;
			this.hbuttonbox1.Add (this.btnLlenarIden);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnLlenarIden]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnInfTicket = new global::Gtk.Button ();
			this.btnInfTicket.WidthRequest = 100;
			this.btnInfTicket.HeightRequest = 100;
			this.btnInfTicket.CanFocus = true;
			this.btnInfTicket.Name = "btnInfTicket";
			// Container child btnInfTicket.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image26 = new global::Gtk.Image ();
			this.image26.Name = "image26";
			this.image26.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/NET13.ICO"));
			this.vbox6.Add (this.image26);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.image26]));
			w14.Position = 0;
			w14.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("<big>Informacion </big>\n        ticket");
			this.label5.UseMarkup = true;
			this.label5.Wrap = true;
			this.vbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label5]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.btnInfTicket.Add (this.vbox6);
			this.btnInfTicket.Label = null;
			this.hbuttonbox1.Add (this.btnInfTicket);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnInfTicket]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.WidthRequest = 100;
			this.btnSalir.HeightRequest = 100;
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			// Container child btnSalir.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.image25 = new global::Gtk.Image ();
			this.image25.Name = "image25";
			this.image25.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/~APP21MB.ICO"));
			this.vbox5.Add (this.image25);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.image25]));
			w18.Position = 0;
			w18.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("<big> Salir </big>");
			this.label4.UseMarkup = true;
			this.vbox5.Add (this.label4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label4]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.btnSalir.Add (this.vbox5);
			this.btnSalir.Label = null;
			this.hbuttonbox1.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnSalir]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox2.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbuttonbox1]));
			w22.PackType = ((global::Gtk.PackType)(1));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 566;
			this.DefaultHeight = 195;
			
			this.btnDividirTicket.Clicked += new global::System.EventHandler (this.btnDividir_Click);
			this.btnSepararTicket.Clicked += new global::System.EventHandler (this.btnSeparar_Click);
			this.btnLlenarIden.Clicked += new global::System.EventHandler (this.btnLlenar_Click);
			this.btnInfTicket.Clicked += new global::System.EventHandler (this.BtnEstadisticaClick);
			this.btnSalir.Clicked += new global::System.EventHandler (this.btnSalir_Click);
		}
	}
}
