
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.TpvFinal
{
	public partial class ImfTicket
	{
		private global::Gtk.VBox vbox1;

		private global::Valle.GtkUtilidades.MiLabel lblTitulo;

		private global::Gtk.HBox hbox1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TextView visorTicket;

		private global::Valle.GtkUtilidades.ScrollTactil scrooltactil1;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.Button btnSalir;

		protected virtual void Init ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.TpvFinal.ImfTicket
			this.Name = "Valle.TpvFinal.ImfTicket";
			this.Title = global::Mono.Unix.Catalog.GetString ("ImfTicket");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Valle.TpvFinal.ImfTicket.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblTitulo = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblTitulo.HeightRequest = 25;
			this.lblTitulo.Events = ((global::Gdk.EventMask)(256));
			this.lblTitulo.Name = "lblTitulo";
			this.vbox1.Add (this.lblTitulo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblTitulo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.HeightRequest = 500;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.visorTicket = new global::Gtk.TextView ();
			this.visorTicket.CanFocus = true;
			this.visorTicket.Name = "visorTicket";
			this.GtkScrolledWindow.Add (this.visorTicket);
			this.hbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.GtkScrolledWindow]));
			w3.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.scrooltactil1 = new global::Valle.GtkUtilidades.ScrollTactil ();
			this.scrooltactil1.Events = ((global::Gdk.EventMask)(256));
			this.scrooltactil1.Name = "scrooltactil1";
			this.hbox1.Add (this.scrooltactil1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.scrooltactil1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w5.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.WidthRequest = 100;
			this.btnSalir.HeightRequest = 100;
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w6 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w7 = new global::Gtk.HBox ();
			w7.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w8 = new global::Gtk.Image ();
			w8.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-close", global::Gtk.IconSize.Dialog);
			w7.Add (w8);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w10 = new global::Gtk.Label ();
			w7.Add (w10);
			w6.Add (w7);
			this.btnSalir.Add (w6);
			this.hbuttonbox1.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnSalir]));
			w14.Expand = false;
			w14.Fill = false;
			this.vbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox1]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 410;
			this.DefaultHeight = 667;
			
		}
	}
}
