
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.TpvFinal
{
	public partial class DividirTiket
	{
		private global::Gtk.VBox vbox1;

		private global::Valle.GtkUtilidades.MiLabel lblTitu;

		private global::Gtk.HBox hbox1;

		private global::Valle.GtkUtilidades.MiLabel txtNumPersonas;

		private global::Gtk.Button button6;

		private global::Gtk.Button button7;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button btnCaja;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Image image3;

		private global::Gtk.Label label1;

		private global::Gtk.HButtonBox hbuttonbox1;

		private global::Gtk.Button btnDividir;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Image image4;

		private global::Gtk.Label label2;

		private global::Gtk.Button btnSalir;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Image image5;

		private global::Gtk.Label label3;

		private global::Valle.GtkUtilidades.MiLabel lblInfTicket;

		protected virtual void Init ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.TpvFinal.DividirTiket
			this.Name = "Valle.TpvFinal.DividirTiket";
			this.Title = global::Mono.Unix.Catalog.GetString ("Dividir un ticket");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Valle.TpvFinal.DividirTiket.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(12));
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblTitu = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblTitu.HeightRequest = 25;
			this.lblTitu.Events = ((global::Gdk.EventMask)(256));
			this.lblTitu.Name = "lblTitu";
			this.vbox1.Add (this.lblTitu);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblTitu]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtNumPersonas = new global::Valle.GtkUtilidades.MiLabel ();
			this.txtNumPersonas.Events = ((global::Gdk.EventMask)(256));
			this.txtNumPersonas.Name = "txtNumPersonas";
			this.hbox1.Add (this.txtNumPersonas);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.txtNumPersonas]));
			w2.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button ();
			this.button6.WidthRequest = 100;
			this.button6.HeightRequest = 100;
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			// Container child button6.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.LargeToolbar);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w4.Add (w7);
			w3.Add (w4);
			this.button6.Add (w3);
			this.hbox1.Add (this.button6);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button6]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button7 = new global::Gtk.Button ();
			this.button7.WidthRequest = 100;
			this.button7.HeightRequest = 100;
			this.button7.CanFocus = true;
			this.button7.Name = "button7";
			this.button7.UseUnderline = true;
			// Container child button7.Gtk.Container+ContainerChild
			global::Gtk.Alignment w12 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w13 = new global::Gtk.HBox ();
			w13.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w14 = new global::Gtk.Image ();
			w14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.LargeToolbar);
			w13.Add (w14);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w16 = new global::Gtk.Label ();
			w13.Add (w16);
			w12.Add (w13);
			this.button7.Add (w12);
			this.hbox1.Add (this.button7);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button7]));
			w20.Position = 2;
			w20.Expand = false;
			w20.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w21.Position = 1;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.btnCaja = new global::Gtk.Button ();
			this.btnCaja.WidthRequest = 100;
			this.btnCaja.HeightRequest = 100;
			this.btnCaja.CanFocus = true;
			this.btnCaja.Name = "btnCaja";
			// Container child btnCaja.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image ();
			this.image3.Name = "image3";
			this.image3.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/CASH01B.ICO"));
			this.vbox2.Add (this.image3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.image3]));
			w22.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("<big>Caja</big>");
			this.label1.UseMarkup = true;
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			this.btnCaja.Add (this.vbox2);
			this.btnCaja.Label = null;
			this.hbox2.Add (this.btnCaja);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.btnCaja]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnDividir = new global::Gtk.Button ();
			this.btnDividir.WidthRequest = 100;
			this.btnDividir.HeightRequest = 100;
			this.btnDividir.CanFocus = true;
			this.btnDividir.Name = "btnDividir";
			// Container child btnDividir.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image4 = new global::Gtk.Image ();
			this.image4.Name = "image4";
			this.image4.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/Division_Sign(a).png"));
			this.vbox3.Add (this.image4);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image4]));
			w26.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("<big>Dividir</big>");
			this.label2.UseMarkup = true;
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
			w27.Position = 1;
			w27.Expand = false;
			w27.Fill = false;
			this.btnDividir.Add (this.vbox3);
			this.btnDividir.Label = null;
			this.hbuttonbox1.Add (this.btnDividir);
			global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnDividir]));
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.HeightRequest = 100;
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			// Container child btnSalir.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image ();
			this.image5.Name = "image5";
			this.image5.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/~APP21MB.ICO"));
			this.vbox4.Add (this.image5);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.image5]));
			w30.Position = 0;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("<big>Salir</big>");
			this.label3.UseMarkup = true;
			this.vbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label3]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.btnSalir.Add (this.vbox4);
			this.btnSalir.Label = null;
			this.hbuttonbox1.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1[this.btnSalir]));
			w33.Position = 1;
			w33.Expand = false;
			w33.Fill = false;
			this.hbox2.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.hbuttonbox1]));
			w34.Position = 1;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w35.PackType = ((global::Gtk.PackType)(1));
			w35.Position = 2;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblInfTicket = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblInfTicket.WidthRequest = 410;
			this.lblInfTicket.HeightRequest = 100;
			this.lblInfTicket.Events = ((global::Gdk.EventMask)(256));
			this.lblInfTicket.Name = "lblInfTicket";
			this.vbox1.Add (this.lblInfTicket);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblInfTicket]));
			w36.PackType = ((global::Gtk.PackType)(1));
			w36.Position = 3;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 443;
			this.DefaultHeight = 399;
			
			this.button6.Clicked += new global::System.EventHandler (this.btnSub_Click);
			this.button7.Clicked += new global::System.EventHandler (this.btnBaj_Click);
			this.btnCaja.Clicked += new global::System.EventHandler (this.btnCaja_Click);
			this.btnDividir.Clicked += new global::System.EventHandler (this.btnDividir_Click);
			this.btnSalir.Clicked += new global::System.EventHandler (this.btnSalir_Click);
		}
	}
}
