
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.TpvFinal
{
	public partial class Tpv
	{
		
		private global::Gtk.VBox vbox1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label lblNomMesas;

		private global::Gtk.Label lblNomCamarero;

		private global::Gtk.Label lblTarifa;

		private global::Gtk.HBox hbox2;

		private global::Gtk.VBox vbox2;

		private global::Gtk.ScrolledWindow scrollNotasGtk;

		private global::Gtk.TreeView lstNotas;

		private global::Gtk.HBox hbox4;

		private global::Valle.GtkUtilidades.MiLabel lblDisplayInf;

		private global::Valle.GtkUtilidades.MiLabel lblDisplay;

		private global::Gtk.Table table1;

		private global::Valle.GtkUtilidades.MiBoton btn4;

		private global::Valle.GtkUtilidades.MiBoton btn5;

		private global::Valle.GtkUtilidades.MiBoton btn6;

		private global::Valle.GtkUtilidades.MiBoton btn7;

		private global::Valle.GtkUtilidades.MiBoton btn8;

		private global::Valle.GtkUtilidades.MiBoton btn9;

		private global::Gtk.Button btnBorrar;

		private global::Gtk.Button btnBorrNum;

		private global::Valle.GtkUtilidades.MiBoton btnC;

		private global::Gtk.Button btnCaja;

		private global::Gtk.Button btnCamareros;

		private global::Valle.GtkUtilidades.MiBoton btnCero;

		private global::Valle.GtkUtilidades.MiBoton btnDos;

		private global::Gtk.Button btnFavoritos;

		private global::Gtk.Button btnImprimir;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Image image14;

		private global::Gtk.Label label1;

		private global::Gtk.Button btnMesas;

		private global::Gtk.Button btnOpciones;

		private global::Gtk.Button btnSalir;

		private global::Gtk.Button btnSecciones;

		private global::Gtk.Button btnTarifa;

		private global::Valle.GtkUtilidades.MiBoton btnTres;

		private global::Valle.GtkUtilidades.MiBoton btnUno;

		private global::Valle.GtkUtilidades.ScrollTactil scrollNotas;

		private global::Gtk.HBox hbox3;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Button btnAbrirCajon;

		private global::Gtk.VBox vbox8;

		private global::Gtk.Image image18;

		private global::Gtk.Label label4;

		private global::Gtk.Button btnHerrDesglose;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Image image17;

		private global::Gtk.Label label3;

		private global::Gtk.Button btnVarios;

		private global::Gtk.Button btnVariosConNombre;

		private global::Gtk.Table pneArticulos;

		private global::Gtk.VButtonBox vbuttonbox2;

		private global::Gtk.Button btnBuscador;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Image image16;

		private global::Gtk.Label label2;

		private global::Gtk.Button btnPgArriba;

		private global::Gtk.Button btnPgAbajo;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.TpvFinal.Tpv
			this.Name = "Valle.TpvFinal.Tpv";
			this.Title = global::Mono.Unix.Catalog.GetString ("Tpv");
			this.Decorated = false;
			this.SkipTaskbarHint = true;
			// Container child Valle.TpvFinal.Tpv.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(3));
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblNomMesas = new global::Gtk.Label ();
			this.lblNomMesas.Name = "lblNomMesas";
			this.lblNomMesas.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size='x-large'>Barra</span>");
			this.lblNomMesas.UseMarkup = true;
			this.hbox1.Add (this.lblNomMesas);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblNomMesas]));
			w1.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblNomCamarero = new global::Gtk.Label ();
			this.lblNomCamarero.Name = "lblNomCamarero";
			this.lblNomCamarero.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size='x-large'>Cajero</span>");
			this.lblNomCamarero.UseMarkup = true;
			this.hbox1.Add (this.lblNomCamarero);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblNomCamarero]));
			w2.Position = 1;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.lblTarifa = new global::Gtk.Label ();
			this.lblTarifa.Name = "lblTarifa";
			this.lblTarifa.LabelProp = global::Mono.Unix.Catalog.GetString ("<span size='x-large'  foreground=\"red\">T :  1</span>");
			this.lblTarifa.UseMarkup = true;
			this.hbox1.Add (this.lblTarifa);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.lblTarifa]));
			w3.Position = 2;
			w3.Fill = false;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.scrollNotasGtk = new global::Gtk.ScrolledWindow ();
			this.scrollNotasGtk.Name = "scrollNotasGtk";
			this.scrollNotasGtk.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child scrollNotasGtk.Gtk.Container+ContainerChild
			this.lstNotas = new global::Gtk.TreeView ();
			this.lstNotas.CanFocus = true;
			this.lstNotas.Name = "lstNotas";
			this.scrollNotasGtk.Add (this.lstNotas);
			this.vbox2.Add (this.scrollNotasGtk);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.scrollNotasGtk]));
			w6.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblDisplayInf = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblDisplayInf.WidthRequest = 120;
			this.lblDisplayInf.HeightRequest = 50;
			this.lblDisplayInf.Events = ((global::Gdk.EventMask)(256));
			this.lblDisplayInf.Name = "lblDisplayInf";
			this.hbox4.Add (this.lblDisplayInf);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblDisplayInf]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.lblDisplay = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblDisplay.Events = ((global::Gdk.EventMask)(256));
			this.lblDisplay.Name = "lblDisplay";
			this.hbox4.Add (this.lblDisplay);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.lblDisplay]));
			w8.Position = 1;
			this.vbox2.Add (this.hbox4);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.hbox4]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox2.Add (this.vbox2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.vbox2]));
			w10.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(4)), ((uint)(6)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btn4 = new global::Valle.GtkUtilidades.MiBoton ();
			this.btn4.WidthRequest = 50;
			this.btn4.HeightRequest = 50;
			this.btn4.Events = ((global::Gdk.EventMask)(256));
			this.btn4.Name = "btn4";
			this.table1.Add (this.btn4);
			global::Gtk.Table.TableChild w11 = ((global::Gtk.Table.TableChild)(this.table1[this.btn4]));
			w11.TopAttach = ((uint)(1));
			w11.BottomAttach = ((uint)(2));
			w11.LeftAttach = ((uint)(1));
			w11.RightAttach = ((uint)(2));
			w11.XOptions = ((global::Gtk.AttachOptions)(4));
			w11.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btn5 = new global::Valle.GtkUtilidades.MiBoton ();
			this.btn5.WidthRequest = 50;
			this.btn5.HeightRequest = 50;
			this.btn5.Events = ((global::Gdk.EventMask)(256));
			this.btn5.Name = "btn5";
			this.table1.Add (this.btn5);
			global::Gtk.Table.TableChild w12 = ((global::Gtk.Table.TableChild)(this.table1[this.btn5]));
			w12.TopAttach = ((uint)(1));
			w12.BottomAttach = ((uint)(2));
			w12.LeftAttach = ((uint)(2));
			w12.RightAttach = ((uint)(3));
			w12.XOptions = ((global::Gtk.AttachOptions)(4));
			w12.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btn6 = new global::Valle.GtkUtilidades.MiBoton ();
			this.btn6.WidthRequest = 50;
			this.btn6.HeightRequest = 50;
			this.btn6.Events = ((global::Gdk.EventMask)(256));
			this.btn6.Name = "btn6";
			this.table1.Add (this.btn6);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.table1[this.btn6]));
			w13.TopAttach = ((uint)(1));
			w13.BottomAttach = ((uint)(2));
			w13.LeftAttach = ((uint)(3));
			w13.RightAttach = ((uint)(4));
			w13.XOptions = ((global::Gtk.AttachOptions)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btn7 = new global::Valle.GtkUtilidades.MiBoton ();
			this.btn7.WidthRequest = 50;
			this.btn7.HeightRequest = 50;
			this.btn7.Events = ((global::Gdk.EventMask)(256));
			this.btn7.Name = "btn7";
			this.table1.Add (this.btn7);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.table1[this.btn7]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.LeftAttach = ((uint)(1));
			w14.RightAttach = ((uint)(2));
			w14.XOptions = ((global::Gtk.AttachOptions)(4));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btn8 = new global::Valle.GtkUtilidades.MiBoton ();
			this.btn8.WidthRequest = 50;
			this.btn8.HeightRequest = 50;
			this.btn8.Events = ((global::Gdk.EventMask)(256));
			this.btn8.Name = "btn8";
			this.table1.Add (this.btn8);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table1[this.btn8]));
			w15.TopAttach = ((uint)(2));
			w15.BottomAttach = ((uint)(3));
			w15.LeftAttach = ((uint)(2));
			w15.RightAttach = ((uint)(3));
			w15.XOptions = ((global::Gtk.AttachOptions)(4));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btn9 = new global::Valle.GtkUtilidades.MiBoton ();
			this.btn9.WidthRequest = 50;
			this.btn9.HeightRequest = 50;
			this.btn9.Events = ((global::Gdk.EventMask)(256));
			this.btn9.Name = "btn9";
			this.table1.Add (this.btn9);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table1[this.btn9]));
			w16.TopAttach = ((uint)(2));
			w16.BottomAttach = ((uint)(3));
			w16.LeftAttach = ((uint)(3));
			w16.RightAttach = ((uint)(4));
			w16.XOptions = ((global::Gtk.AttachOptions)(4));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnBorrar = new global::Gtk.Button ();
			this.btnBorrar.HeightRequest = 85;
			this.btnBorrar.CanFocus = true;
			this.btnBorrar.Name = "btnBorrar";
			this.btnBorrar.UseUnderline = true;
			// Container child btnBorrar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w17 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w18 = new global::Gtk.HBox ();
			w18.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w19 = new global::Gtk.Image ();
			w19.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/ERASE00C.ICO"));
			w18.Add (w19);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w21 = new global::Gtk.Label ();
			w18.Add (w21);
			w17.Add (w18);
			this.btnBorrar.Add (w17);
			this.table1.Add (this.btnBorrar);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1[this.btnBorrar]));
			w25.TopAttach = ((uint)(2));
			w25.BottomAttach = ((uint)(3));
			w25.XOptions = ((global::Gtk.AttachOptions)(4));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnBorrNum = new global::Gtk.Button ();
			this.btnBorrNum.CanFocus = true;
			this.btnBorrNum.Name = "btnBorrNum";
			this.btnBorrNum.UseUnderline = true;
			// Container child btnBorrNum.Gtk.Container+ContainerChild
			global::Gtk.Alignment w26 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w27 = new global::Gtk.HBox ();
			w27.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w28 = new global::Gtk.Image ();
			w28.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/Backspace.ICO"));
			w27.Add (w28);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w30 = new global::Gtk.Label ();
			w27.Add (w30);
			w26.Add (w27);
			this.btnBorrNum.Add (w26);
			this.table1.Add (this.btnBorrNum);
			global::Gtk.Table.TableChild w34 = ((global::Gtk.Table.TableChild)(this.table1[this.btnBorrNum]));
			w34.TopAttach = ((uint)(3));
			w34.BottomAttach = ((uint)(4));
			w34.LeftAttach = ((uint)(3));
			w34.RightAttach = ((uint)(4));
			w34.XOptions = ((global::Gtk.AttachOptions)(4));
			w34.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnC = new global::Valle.GtkUtilidades.MiBoton ();
			this.btnC.WidthRequest = 50;
			this.btnC.HeightRequest = 50;
			this.btnC.Events = ((global::Gdk.EventMask)(256));
			this.btnC.Name = "btnC";
			this.btnC.Texto = "C";
			this.table1.Add (this.btnC);
			global::Gtk.Table.TableChild w35 = ((global::Gtk.Table.TableChild)(this.table1[this.btnC]));
			w35.TopAttach = ((uint)(3));
			w35.BottomAttach = ((uint)(4));
			w35.LeftAttach = ((uint)(1));
			w35.RightAttach = ((uint)(2));
			w35.XOptions = ((global::Gtk.AttachOptions)(4));
			w35.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnCaja = new global::Gtk.Button ();
			this.btnCaja.HeightRequest = 85;
			this.btnCaja.CanFocus = true;
			this.btnCaja.Name = "btnCaja";
			this.btnCaja.UseUnderline = true;
			// Container child btnCaja.Gtk.Container+ContainerChild
			global::Gtk.Alignment w36 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w37 = new global::Gtk.HBox ();
			w37.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w38 = new global::Gtk.Image ();
			w38.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/CASH01B.ICO"));
			w37.Add (w38);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w40 = new global::Gtk.Label ();
			w37.Add (w40);
			w36.Add (w37);
			this.btnCaja.Add (w36);
			this.table1.Add (this.btnCaja);
			global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1[this.btnCaja]));
			w44.TopAttach = ((uint)(3));
			w44.BottomAttach = ((uint)(4));
			w44.XOptions = ((global::Gtk.AttachOptions)(4));
			w44.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnCamareros = new global::Gtk.Button ();
			this.btnCamareros.CanFocus = true;
			this.btnCamareros.Name = "btnCamareros";
			this.btnCamareros.UseUnderline = true;
			// Container child btnCamareros.Gtk.Container+ContainerChild
			global::Gtk.Alignment w45 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w46 = new global::Gtk.HBox ();
			w46.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w47 = new global::Gtk.Image ();
			w47.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/NET14.ICO"));
			w46.Add (w47);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w49 = new global::Gtk.Label ();
			w49.LabelProp = global::Mono.Unix.Catalog.GetString ("Camareros");
			w49.UseUnderline = true;
			w46.Add (w49);
			w45.Add (w46);
			this.btnCamareros.Add (w45);
			this.table1.Add (this.btnCamareros);
			global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1[this.btnCamareros]));
			w53.TopAttach = ((uint)(2));
			w53.BottomAttach = ((uint)(3));
			w53.LeftAttach = ((uint)(4));
			w53.RightAttach = ((uint)(5));
			w53.XOptions = ((global::Gtk.AttachOptions)(4));
			w53.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnCero = new global::Valle.GtkUtilidades.MiBoton ();
			this.btnCero.WidthRequest = 50;
			this.btnCero.HeightRequest = 50;
			this.btnCero.Events = ((global::Gdk.EventMask)(256));
			this.btnCero.Name = "btnCero";
			this.table1.Add (this.btnCero);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table1[this.btnCero]));
			w54.TopAttach = ((uint)(3));
			w54.BottomAttach = ((uint)(4));
			w54.LeftAttach = ((uint)(2));
			w54.RightAttach = ((uint)(3));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnDos = new global::Valle.GtkUtilidades.MiBoton ();
			this.btnDos.WidthRequest = 85;
			this.btnDos.HeightRequest = 50;
			this.btnDos.Events = ((global::Gdk.EventMask)(256));
			this.btnDos.Name = "btnDos";
			this.table1.Add (this.btnDos);
			global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table1[this.btnDos]));
			w55.LeftAttach = ((uint)(2));
			w55.RightAttach = ((uint)(3));
			w55.XOptions = ((global::Gtk.AttachOptions)(4));
			w55.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnFavoritos = new global::Gtk.Button ();
			this.btnFavoritos.CanFocus = true;
			this.btnFavoritos.Name = "btnFavoritos";
			this.btnFavoritos.UseUnderline = true;
			// Container child btnFavoritos.Gtk.Container+ContainerChild
			global::Gtk.Alignment w56 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w57 = new global::Gtk.HBox ();
			w57.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w58 = new global::Gtk.Image ();
			w58.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/{{F02B.ICO"));
			w57.Add (w58);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w60 = new global::Gtk.Label ();
			w60.LabelProp = global::Mono.Unix.Catalog.GetString ("Favoritos");
			w60.UseUnderline = true;
			w57.Add (w60);
			w56.Add (w57);
			this.btnFavoritos.Add (w56);
			this.table1.Add (this.btnFavoritos);
			global::Gtk.Table.TableChild w64 = ((global::Gtk.Table.TableChild)(this.table1[this.btnFavoritos]));
			w64.TopAttach = ((uint)(3));
			w64.BottomAttach = ((uint)(4));
			w64.LeftAttach = ((uint)(4));
			w64.RightAttach = ((uint)(5));
			w64.XOptions = ((global::Gtk.AttachOptions)(4));
			w64.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnImprimir = new global::Gtk.Button ();
			this.btnImprimir.CanFocus = true;
			this.btnImprimir.Name = "btnImprimir";
			// Container child btnImprimir.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image14 = new global::Gtk.Image ();
			this.image14.Name = "image14";
			this.image14.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-print", global::Gtk.IconSize.Dialog);
			this.vbox3.Add (this.image14);
			global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image14]));
			w65.Position = 0;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("   Imprimir\nPreimprimir");
			this.vbox3.Add (this.label1);
			global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label1]));
			w66.Position = 1;
			w66.Expand = false;
			w66.Fill = false;
			this.btnImprimir.Add (this.vbox3);
			this.btnImprimir.Label = null;
			this.table1.Add (this.btnImprimir);
			global::Gtk.Table.TableChild w68 = ((global::Gtk.Table.TableChild)(this.table1[this.btnImprimir]));
			w68.TopAttach = ((uint)(3));
			w68.BottomAttach = ((uint)(4));
			w68.LeftAttach = ((uint)(5));
			w68.RightAttach = ((uint)(6));
			w68.XOptions = ((global::Gtk.AttachOptions)(4));
			w68.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnMesas = new global::Gtk.Button ();
			this.btnMesas.CanFocus = true;
			this.btnMesas.Name = "btnMesas";
			this.btnMesas.UseUnderline = true;
			// Container child btnMesas.Gtk.Container+ContainerChild
			global::Gtk.Alignment w69 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w70 = new global::Gtk.HBox ();
			w70.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w71 = new global::Gtk.Image ();
			w71.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/TABLE00B.ICO"));
			w70.Add (w71);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w73 = new global::Gtk.Label ();
			w73.LabelProp = global::Mono.Unix.Catalog.GetString ("Mesas");
			w73.UseUnderline = true;
			w70.Add (w73);
			w69.Add (w70);
			this.btnMesas.Add (w69);
			this.table1.Add (this.btnMesas);
			global::Gtk.Table.TableChild w77 = ((global::Gtk.Table.TableChild)(this.table1[this.btnMesas]));
			w77.TopAttach = ((uint)(2));
			w77.BottomAttach = ((uint)(3));
			w77.LeftAttach = ((uint)(5));
			w77.RightAttach = ((uint)(6));
			w77.XOptions = ((global::Gtk.AttachOptions)(4));
			w77.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnOpciones = new global::Gtk.Button ();
			this.btnOpciones.CanFocus = true;
			this.btnOpciones.Name = "btnOpciones";
			// Container child btnOpciones.Gtk.Container+ContainerChild
			global::Gtk.Alignment w78 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w79 = new global::Gtk.HBox ();
			w79.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w80 = new global::Gtk.Image ();
			w80.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/configure_toolbars.gif"));
			w79.Add (w80);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w82 = new global::Gtk.Label ();
			w82.LabelProp = global::Mono.Unix.Catalog.GetString ("Opciones");
			w79.Add (w82);
			w78.Add (w79);
			this.btnOpciones.Add (w78);
			this.table1.Add (this.btnOpciones);
			global::Gtk.Table.TableChild w86 = ((global::Gtk.Table.TableChild)(this.table1[this.btnOpciones]));
			w86.LeftAttach = ((uint)(4));
			w86.RightAttach = ((uint)(5));
			w86.XOptions = ((global::Gtk.AttachOptions)(4));
			w86.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.WidthRequest = 85;
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w87 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w88 = new global::Gtk.HBox ();
			w88.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w89 = new global::Gtk.Image ();
			w89.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/exit.gif"));
			w88.Add (w89);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w91 = new global::Gtk.Label ();
			w88.Add (w91);
			w87.Add (w88);
			this.btnSalir.Add (w87);
			this.table1.Add (this.btnSalir);
			global::Gtk.Table.TableChild w95 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSalir]));
			w95.LeftAttach = ((uint)(5));
			w95.RightAttach = ((uint)(6));
			w95.XOptions = ((global::Gtk.AttachOptions)(4));
			w95.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSecciones = new global::Gtk.Button ();
			this.btnSecciones.CanFocus = true;
			this.btnSecciones.Name = "btnSecciones";
			// Container child btnSecciones.Gtk.Container+ContainerChild
			global::Gtk.Alignment w96 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w97 = new global::Gtk.HBox ();
			w97.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w98 = new global::Gtk.Image ();
			w98.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/ALPH03A.ICO"));
			w97.Add (w98);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w100 = new global::Gtk.Label ();
			w100.LabelProp = global::Mono.Unix.Catalog.GetString ("Secciones");
			w97.Add (w100);
			w96.Add (w97);
			this.btnSecciones.Add (w96);
			this.table1.Add (this.btnSecciones);
			global::Gtk.Table.TableChild w104 = ((global::Gtk.Table.TableChild)(this.table1[this.btnSecciones]));
			w104.TopAttach = ((uint)(1));
			w104.BottomAttach = ((uint)(2));
			w104.LeftAttach = ((uint)(4));
			w104.RightAttach = ((uint)(5));
			w104.XOptions = ((global::Gtk.AttachOptions)(4));
			w104.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnTarifa = new global::Gtk.Button ();
			this.btnTarifa.CanFocus = true;
			this.btnTarifa.Name = "btnTarifa";
			this.btnTarifa.UseUnderline = true;
			// Container child btnTarifa.Gtk.Container+ContainerChild
			global::Gtk.Alignment w105 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w106 = new global::Gtk.HBox ();
			w106.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w107 = new global::Gtk.Image ();
			w107.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/euro.png"));
			w106.Add (w107);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w109 = new global::Gtk.Label ();
			w109.LabelProp = global::Mono.Unix.Catalog.GetString ("Tarifa");
			w109.UseUnderline = true;
			w106.Add (w109);
			w105.Add (w106);
			this.btnTarifa.Add (w105);
			this.table1.Add (this.btnTarifa);
			global::Gtk.Table.TableChild w113 = ((global::Gtk.Table.TableChild)(this.table1[this.btnTarifa]));
			w113.TopAttach = ((uint)(1));
			w113.BottomAttach = ((uint)(2));
			w113.LeftAttach = ((uint)(5));
			w113.RightAttach = ((uint)(6));
			w113.XOptions = ((global::Gtk.AttachOptions)(4));
			w113.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnTres = new global::Valle.GtkUtilidades.MiBoton ();
			this.btnTres.WidthRequest = 85;
			this.btnTres.HeightRequest = 50;
			this.btnTres.Events = ((global::Gdk.EventMask)(256));
			this.btnTres.Name = "btnTres";
			this.table1.Add (this.btnTres);
			global::Gtk.Table.TableChild w114 = ((global::Gtk.Table.TableChild)(this.table1[this.btnTres]));
			w114.LeftAttach = ((uint)(3));
			w114.RightAttach = ((uint)(4));
			w114.XOptions = ((global::Gtk.AttachOptions)(4));
			w114.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnUno = new global::Valle.GtkUtilidades.MiBoton ();
			this.btnUno.WidthRequest = 85;
			this.btnUno.HeightRequest = 50;
			this.btnUno.Events = ((global::Gdk.EventMask)(256));
			this.btnUno.Name = "btnUno";
			this.table1.Add (this.btnUno);
			global::Gtk.Table.TableChild w115 = ((global::Gtk.Table.TableChild)(this.table1[this.btnUno]));
			w115.LeftAttach = ((uint)(1));
			w115.RightAttach = ((uint)(2));
			w115.XOptions = ((global::Gtk.AttachOptions)(4));
			w115.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.scrollNotas = new global::Valle.GtkUtilidades.ScrollTactil ();
			this.scrollNotas.WidthRequest = 95;
			this.scrollNotas.HeightRequest = 156;
			this.scrollNotas.Events = ((global::Gdk.EventMask)(256));
			this.scrollNotas.Name = "scrollNotas";
			this.table1.Add (this.scrollNotas);
			global::Gtk.Table.TableChild w116 = ((global::Gtk.Table.TableChild)(this.table1[this.scrollNotas]));
			w116.BottomAttach = ((uint)(2));
			w116.XOptions = ((global::Gtk.AttachOptions)(4));
			w116.YOptions = ((global::Gtk.AttachOptions)(4));
			this.hbox2.Add (this.table1);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.table1]));
			w117.Position = 1;
			w117.Expand = false;
			w117.Fill = false;
			this.vbox1.Add (this.hbox2);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox2]));
			w118.Position = 1;
			w118.Expand = false;
			w118.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.btnAbrirCajon = new global::Gtk.Button ();
			this.btnAbrirCajon.WidthRequest = 85;
			this.btnAbrirCajon.HeightRequest = 85;
			this.btnAbrirCajon.CanFocus = true;
			this.btnAbrirCajon.Name = "btnAbrirCajon";
			// Container child btnAbrirCajon.Gtk.Container+ContainerChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			// Container child vbox8.Gtk.Box+BoxChild
			this.image18 = new global::Gtk.Image ();
			this.image18.Name = "image18";
			this.image18.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/STARTUP.ICO"));
			this.vbox8.Add (this.image18);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.image18]));
			w119.Position = 0;
			w119.Expand = false;
			w119.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Abrir\nCajon");
			this.vbox8.Add (this.label4);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox8[this.label4]));
			w120.Position = 1;
			w120.Expand = false;
			w120.Fill = false;
			this.btnAbrirCajon.Add (this.vbox8);
			this.btnAbrirCajon.Label = null;
			this.vbox7.Add (this.btnAbrirCajon);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.btnAbrirCajon]));
			w122.Position = 0;
			w122.Expand = false;
			w122.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.btnHerrDesglose = new global::Gtk.Button ();
			this.btnHerrDesglose.CanFocus = true;
			this.btnHerrDesglose.Name = "btnHerrDesglose";
			// Container child btnHerrDesglose.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.image17 = new global::Gtk.Image ();
			this.image17.Name = "image17";
			this.image17.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/Comment.ico"));
			this.vbox5.Add (this.image17);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.image17]));
			w123.Position = 0;
			w123.Expand = false;
			w123.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Opciones\nDesglose");
			this.vbox5.Add (this.label3);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label3]));
			w124.Position = 1;
			w124.Expand = false;
			w124.Fill = false;
			this.btnHerrDesglose.Add (this.vbox5);
			this.btnHerrDesglose.Label = null;
			this.vbox7.Add (this.btnHerrDesglose);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.btnHerrDesglose]));
			w126.Position = 1;
			w126.Expand = false;
			w126.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.btnVarios = new global::Gtk.Button ();
			this.btnVarios.WidthRequest = 0;
			this.btnVarios.HeightRequest = 85;
			this.btnVarios.CanFocus = true;
			this.btnVarios.Name = "btnVarios";
			this.btnVarios.UseUnderline = true;
			this.btnVarios.Label = global::Mono.Unix.Catalog.GetString ("Varios");
			this.vbox7.Add (this.btnVarios);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.btnVarios]));
			w127.Position = 2;
			w127.Expand = false;
			w127.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.btnVariosConNombre = new global::Gtk.Button ();
			this.btnVariosConNombre.WidthRequest = 0;
			this.btnVariosConNombre.HeightRequest = 85;
			this.btnVariosConNombre.CanFocus = true;
			this.btnVariosConNombre.Name = "btnVariosConNombre";
			this.btnVariosConNombre.UseUnderline = true;
			this.btnVariosConNombre.Label = global::Mono.Unix.Catalog.GetString ("     Varios\nCon nombre");
			this.vbox7.Add (this.btnVariosConNombre);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.btnVariosConNombre]));
			w128.Position = 3;
			w128.Expand = false;
			w128.Fill = false;
			this.hbox3.Add (this.vbox7);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbox7]));
			w129.Position = 0;
			w129.Expand = false;
			w129.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.pneArticulos = new global::Gtk.Table (((uint)(4)), ((uint)(8)), true);
			this.pneArticulos.Name = "pneArticulos";
			this.pneArticulos.RowSpacing = ((uint)(6));
			this.pneArticulos.ColumnSpacing = ((uint)(6));
			this.hbox3.Add (this.pneArticulos);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.pneArticulos]));
			w130.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox ();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbuttonbox2.Spacing = 3;
			this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(3));
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnBuscador = new global::Gtk.Button ();
			this.btnBuscador.WidthRequest = 100;
			this.btnBuscador.HeightRequest = 95;
			this.btnBuscador.CanFocus = true;
			this.btnBuscador.Name = "btnBuscador";
			// Container child btnBuscador.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image16 = new global::Gtk.Image ();
			this.image16.Name = "image16";
			this.image16.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Dialog);
			this.vbox4.Add (this.image16);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.image16]));
			w131.Position = 0;
			w131.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Buscar");
			this.vbox4.Add (this.label2);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label2]));
			w132.Position = 1;
			w132.Expand = false;
			w132.Fill = false;
			this.btnBuscador.Add (this.vbox4);
			this.btnBuscador.Label = null;
			this.vbuttonbox2.Add (this.btnBuscador);
			global::Gtk.ButtonBox.ButtonBoxChild w134 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.btnBuscador]));
			w134.Expand = false;
			w134.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnPgArriba = new global::Gtk.Button ();
			this.btnPgArriba.HeightRequest = 117;
			this.btnPgArriba.CanFocus = true;
			this.btnPgArriba.Name = "btnPgArriba";
			this.btnPgArriba.UseUnderline = true;
			// Container child btnPgArriba.Gtk.Container+ContainerChild
			global::Gtk.Alignment w135 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w136 = new global::Gtk.HBox ();
			w136.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w137 = new global::Gtk.Image ();
			w137.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/ARROW12Dx.ICO"));
			w136.Add (w137);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w139 = new global::Gtk.Label ();
			w136.Add (w139);
			w135.Add (w136);
			this.btnPgArriba.Add (w135);
			this.vbuttonbox2.Add (this.btnPgArriba);
			global::Gtk.ButtonBox.ButtonBoxChild w143 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.btnPgArriba]));
			w143.Position = 1;
			w143.Expand = false;
			w143.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnPgAbajo = new global::Gtk.Button ();
			this.btnPgAbajo.CanFocus = true;
			this.btnPgAbajo.Name = "btnPgAbajo";
			this.btnPgAbajo.UseUnderline = true;
			// Container child btnPgAbajo.Gtk.Container+ContainerChild
			global::Gtk.Alignment w144 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w145 = new global::Gtk.HBox ();
			w145.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w146 = new global::Gtk.Image ();
			w146.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./iconos/ARROW12Ax.ICO"));
			w145.Add (w146);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w148 = new global::Gtk.Label ();
			w145.Add (w148);
			w144.Add (w145);
			this.btnPgAbajo.Add (w144);
			this.vbuttonbox2.Add (this.btnPgAbajo);
			global::Gtk.ButtonBox.ButtonBoxChild w152 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2[this.btnPgAbajo]));
			w152.Position = 2;
			w152.Expand = false;
			w152.Fill = false;
			this.hbox3.Add (this.vbuttonbox2);
			global::Gtk.Box.BoxChild w153 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.vbuttonbox2]));
			w153.Position = 2;
			w153.Expand = false;
			w153.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w154 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox3]));
			w154.Position = 2;
			w154.Expand = false;
			w154.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			int width=0,height=0;
			this.RootWindow.GetSize(out width,out height);
			       
			this.DefaultWidth = width;
			this.DefaultHeight = height;
		
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.lstNotas.SelectCursorRow += new global::Gtk.SelectCursorRowHandler (this.OnLstNotasSelectCursorRow);
			this.btnUno.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btnTres.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btnTarifa.Clicked += new global::System.EventHandler (this.OnBtnTarifaClicked);
			this.btnSecciones.Clicked += new global::System.EventHandler (this.OnBtnSeccionesClicked);
			this.btnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
			this.btnOpciones.Clicked += new global::System.EventHandler (this.OnBtnOpcionesClicked);
			this.btnMesas.Clicked += new global::System.EventHandler (this.OnBtnMesasClicked);
			this.btnImprimir.Clicked += new global::System.EventHandler (this.OnBtnImprimirClicked);
			this.btnFavoritos.Clicked += new global::System.EventHandler (this.OnBtnFavoritosClicked);
			this.btnDos.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btnCero.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btnCamareros.Clicked += new global::System.EventHandler (this.OnBtnCamarerosClicked);
			this.btnCaja.Clicked += new global::System.EventHandler (this.OnBtnCajaClicked);
			this.btnC.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btnBorrNum.Clicked += new global::System.EventHandler (this.OnBtnBorrNumClicked);
			this.btnBorrar.Clicked += new global::System.EventHandler (this.OnBtnBorrarClicked);
			this.btn9.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btn8.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btn7.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btn6.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btn5.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btn4.ClickBoton += new global::Valle.GtkUtilidades.MiBoton.OnEjAccionTecla (this.OnBtnNumerico);
			this.btnAbrirCajon.Clicked += new global::System.EventHandler (this.OnBtnAbrirCajonClicked);
			this.btnHerrDesglose.Clicked += new global::System.EventHandler (this.OnBtnHerrDesgloseClicked);
			this.btnVarios.Clicked += new global::System.EventHandler (this.OnBtnVariosClicked);
			this.btnVariosConNombre.Clicked += new global::System.EventHandler (this.OnBtnVariosConNombreClicked);
			this.btnBuscador.Clicked += new global::System.EventHandler (this.OnBtnBuscadorClicked);
			this.btnPgArriba.Clicked += new global::System.EventHandler (this.OnBtnPgArribaClicked);
			this.btnPgAbajo.Clicked += new global::System.EventHandler (this.OnBtnPgAbajoClicked);
		}
	}
}
