
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GesTpv
{
	public partial class VenExportImport
	{
		private global::Gtk.Table table1;
		private global::Gtk.Button btnImportar;
		private global::Gtk.Button btnSalir;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView lstRemoto;
		private global::Gtk.Label label3;
		private global::Gtk.Label lblInforamcion;
		private global::Gtk.VBox vbox1;
		private global::Gtk.RadioButton radioIndividual;
		private global::Gtk.RadioButton radioTodas;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GesTpv.VenExportImport
			this.CanFocus = true;
			this.Events = ((global::Gdk.EventMask)(1081344));
			this.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.Name = "Valle.GesTpv.VenExportImport";
			this.Title = global::Mono.Unix.Catalog.GetString ("Importar todos los datos del servidor");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/exec.gif"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Valle.GesTpv.VenExportImport.Gtk.Container+ContainerChild
			this.table1 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(12));
			// Container child table1.Gtk.Table+TableChild
			this.btnImportar = new global::Gtk.Button ();
			this.btnImportar.CanFocus = true;
			this.btnImportar.Name = "btnImportar";
			this.btnImportar.UseUnderline = true;
			this.btnImportar.BorderWidth = ((uint)(3));
			// Container child btnImportar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_data-sources-new", global::Gtk.IconSize.Menu);
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w5.LabelProp = global::Mono.Unix.Catalog.GetString ("Ejecutar Importar");
			w5.UseUnderline = true;
			w2.Add (w5);
			w1.Add (w2);
			this.btnImportar.Add (w1);
			this.table1.Add (this.btnImportar);
			global::Gtk.Table.TableChild w9 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnImportar]));
			w9.TopAttach = ((uint)(3));
			w9.BottomAttach = ((uint)(4));
			w9.XOptions = ((global::Gtk.AttachOptions)(4));
			w9.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.BorderWidth = ((uint)(3));
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/EXIT00C.ICO"));
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w14.LabelProp = global::Mono.Unix.Catalog.GetString ("Salir importar");
			w14.UseUnderline = true;
			w11.Add (w14);
			w10.Add (w11);
			this.btnSalir.Add (w10);
			this.table1.Add (this.btnSalir);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnSalir]));
			w18.TopAttach = ((uint)(3));
			w18.BottomAttach = ((uint)(4));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.WidthRequest = 450;
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.lstRemoto = new global::Gtk.TreeView ();
			this.lstRemoto.HeightRequest = 365;
			this.lstRemoto.CanFocus = true;
			this.lstRemoto.Name = "lstRemoto";
			this.GtkScrolledWindow1.Add (this.lstRemoto);
			this.table1.Add (this.GtkScrolledWindow1);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table1 [this.GtkScrolledWindow1]));
			w20.TopAttach = ((uint)(2));
			w20.BottomAttach = ((uint)(3));
			w20.RightAttach = ((uint)(2));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Lista de tablas a Importar");
			this.table1.Add (this.label3);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.table1 [this.label3]));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.lblInforamcion = new global::Gtk.Label ();
			this.lblInforamcion.Name = "lblInforamcion";
			this.lblInforamcion.Xalign = 0F;
			this.lblInforamcion.LabelProp = global::Mono.Unix.Catalog.GetString ("ATENCION: Los datos del gestor seran remplazados por los del TPV");
			this.table1.Add (this.lblInforamcion);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblInforamcion]));
			w22.TopAttach = ((uint)(4));
			w22.BottomAttach = ((uint)(5));
			w22.RightAttach = ((uint)(2));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.radioIndividual = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Importar datos que pertenezca a este servidor"));
			this.radioIndividual.CanFocus = true;
			this.radioIndividual.Name = "radioIndividual";
			this.radioIndividual.Active = true;
			this.radioIndividual.DrawIndicator = true;
			this.radioIndividual.UseUnderline = true;
			this.radioIndividual.Group = new global::GLib.SList (global::System.IntPtr.Zero);
			this.vbox1.Add (this.radioIndividual);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.radioIndividual]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.radioTodas = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Importar todos los datos (Esto desincroniza a otros server)"));
			this.radioTodas.CanFocus = true;
			this.radioTodas.Name = "radioTodas";
			this.radioTodas.DrawIndicator = true;
			this.radioTodas.UseUnderline = true;
			this.radioTodas.Group = this.radioIndividual.Group;
			this.vbox1.Add (this.radioTodas);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.radioTodas]));
			w24.Position = 1;
			w24.Expand = false;
			this.table1.Add (this.vbox1);
			global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table1 [this.vbox1]));
			w25.TopAttach = ((uint)(1));
			w25.BottomAttach = ((uint)(2));
			w25.RightAttach = ((uint)(2));
			w25.XOptions = ((global::Gtk.AttachOptions)(0));
			w25.YOptions = ((global::Gtk.AttachOptions)(4));
			this.Add (this.table1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 511;
			this.DefaultHeight = 602;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.radioTodas.Toggled += new global::System.EventHandler (this.OnRadioTodasToggled);
			this.btnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
			this.btnImportar.Clicked += new global::System.EventHandler (this.OnBtnImportarClicked);
		}
	}
}
