
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GesTpv
{
	public partial class VenConfigTpv
	{
		private global::Gtk.VBox vboxPrincipal;
		private global::Gtk.HBox hboxTpvs;
		private global::Gtk.Label label2;
		private global::Gtk.ComboBox cmbTpvs;
		private global::Gtk.Button btnAñadirTpvs;
		private global::Gtk.Notebook tabConfig;
		private global::Gtk.Table tableConfig;
		private global::Gtk.CheckButton checkImprimirAuto;
		private global::Gtk.CheckButton checkMesasPrimero;
		private global::Gtk.CheckButton checkVarios;
		private global::Gtk.CheckButton checkVariosConNombre;
		private global::Gtk.Label label5;
		private global::Gtk.Label label6;
		private global::Gtk.Label label8;
		private global::Gtk.Entry txtContraseña;
		private global::Valle.GtkUtilidades.TxtHoras txtHoraIniTpv;
		private global::Gtk.SpinButton txtTempControles;
		private global::Gtk.SpinButton txtTempNoAc;
		private global::Gtk.Label label1;
		private global::Gtk.VBox vboxZonasMesas;
		private global::Gtk.HBox hbox8;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label10;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView tblZonasBase;
		private global::Gtk.VButtonBox vbuttonbox1;
		private global::Gtk.Button btnAñadirZona;
		private global::Gtk.Button btnQuitarZona;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label11;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView tblZonasTpv;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label label12;
		private global::Gtk.ScrolledWindow GtkScrolledWindow2;
		private global::Gtk.TreeView tblMesasZona;
		private global::Gtk.Label label4;
		private global::Gtk.VBox vboxZonasMesas1;
		private global::Gtk.HBox hbox4;
		private global::Gtk.VBox vbox13;
		private global::Gtk.Label label13;
		private global::Gtk.ScrolledWindow GtkScrolledWindow3;
		private global::Gtk.TreeView tblSeccionesBase;
		private global::Gtk.VButtonBox vbuttonbox2;
		private global::Gtk.Button btnAñadirSec;
		private global::Gtk.Button btnQuitarSec;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label label14;
		private global::Gtk.ScrolledWindow GtkScrolledWindow4;
		private global::Gtk.TreeView tblSeccionesTpv;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label label15;
		private global::Gtk.ScrolledWindow GtkScrolledWindow5;
		private global::Gtk.TreeView tblTeclasSec;
		private global::Gtk.Label label3;
		private global::Gtk.VBox vboxZonasMesas2;
		private global::Gtk.HBox hbox5;
		private global::Gtk.VBox vbox9;
		private global::Gtk.Label label16;
		private global::Gtk.ScrolledWindow GtkScrolledWindow6;
		private global::Gtk.TreeView tblBaseFav;
		private global::Gtk.VButtonBox vbuttonbox3;
		private global::Gtk.Button btnAñadirFav;
		private global::Gtk.Button btnQuitarFav;
		private global::Gtk.VBox vbox10;
		private global::Gtk.HBox hbox1;
		private global::Valle.GtkUtilidades.TxtHoras txtHoraIniFav;
		private global::Gtk.VButtonBox vbuttonbox4;
		private global::Gtk.Button btnAceptarHor;
		private global::Gtk.Label label17;
		private global::Gtk.ScrolledWindow GtkScrolledWindow7;
		private global::Gtk.TreeView tblTpvFav;
		private global::Gtk.VBox vbox12;
		private global::Gtk.Label label18;
		private global::Gtk.ScrolledWindow GtkScrolledWindow8;
		private global::Gtk.TreeView tblTeclasFav;
		private global::Gtk.Label label19;
		private global::Gtk.HButtonBox grpModos;
		private global::Gtk.Button btnEditar;
		private global::Gtk.Button btnAñadir;
		private global::Gtk.Button btnBorrar;
		private global::Gtk.HBox hbox7;
		private global::Gtk.HButtonBox grpModos1;
		private global::Gtk.Button btnAceptar;
		private global::Gtk.Button btnSalir;
		private global::Gtk.Label lblInformacion;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GesTpv.VenConfigTpv
			this.HeightRequest = 700;
			this.Name = "Valle.GesTpv.VenConfigTpv";
			this.Title = global::Mono.Unix.Catalog.GetString ("Configuracion de tpv's");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/exec.gif"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Valle.GesTpv.VenConfigTpv.Gtk.Container+ContainerChild
			this.vboxPrincipal = new global::Gtk.VBox ();
			this.vboxPrincipal.Name = "vboxPrincipal";
			this.vboxPrincipal.Spacing = 6;
			this.vboxPrincipal.BorderWidth = ((uint)(9));
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.hboxTpvs = new global::Gtk.HBox ();
			this.hboxTpvs.Name = "hboxTpvs";
			this.hboxTpvs.Spacing = 6;
			// Container child hboxTpvs.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Tpv editado");
			this.hboxTpvs.Add (this.label2);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hboxTpvs [this.label2]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hboxTpvs.Gtk.Box+BoxChild
			this.cmbTpvs = global::Gtk.ComboBox.NewText ();
			this.cmbTpvs.WidthRequest = 251;
			this.cmbTpvs.Name = "cmbTpvs";
			this.hboxTpvs.Add (this.cmbTpvs);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hboxTpvs [this.cmbTpvs]));
			w2.Position = 1;
			w2.Expand = false;
			// Container child hboxTpvs.Gtk.Box+BoxChild
			this.btnAñadirTpvs = new global::Gtk.Button ();
			this.btnAñadirTpvs.CanFocus = true;
			this.btnAñadirTpvs.Name = "btnAñadirTpvs";
			this.btnAñadirTpvs.UseUnderline = true;
			// Container child btnAñadirTpvs.Gtk.Container+ContainerChild
			global::Gtk.Alignment w3 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w4 = new global::Gtk.HBox ();
			w4.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w5 = new global::Gtk.Image ();
			w5.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w4.Add (w5);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w7 = new global::Gtk.Label ();
			w4.Add (w7);
			w3.Add (w4);
			this.btnAñadirTpvs.Add (w3);
			this.hboxTpvs.Add (this.btnAñadirTpvs);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hboxTpvs [this.btnAñadirTpvs]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			this.vboxPrincipal.Add (this.hboxTpvs);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.hboxTpvs]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.tabConfig = new global::Gtk.Notebook ();
			this.tabConfig.CanFocus = true;
			this.tabConfig.Name = "tabConfig";
			this.tabConfig.CurrentPage = 0;
			this.tabConfig.BorderWidth = ((uint)(12));
			// Container child tabConfig.Gtk.Notebook+NotebookChild
			this.tableConfig = new global::Gtk.Table (((uint)(5)), ((uint)(3)), false);
			this.tableConfig.Name = "tableConfig";
			this.tableConfig.RowSpacing = ((uint)(10));
			this.tableConfig.ColumnSpacing = ((uint)(10));
			this.tableConfig.BorderWidth = ((uint)(15));
			// Container child tableConfig.Gtk.Table+TableChild
			this.checkImprimirAuto = new global::Gtk.CheckButton ();
			this.checkImprimirAuto.CanFocus = true;
			this.checkImprimirAuto.Name = "checkImprimirAuto";
			this.checkImprimirAuto.Label = global::Mono.Unix.Catalog.GetString ("Impresion automatica");
			this.checkImprimirAuto.DrawIndicator = true;
			this.checkImprimirAuto.UseUnderline = true;
			this.tableConfig.Add (this.checkImprimirAuto);
			global::Gtk.Table.TableChild w13 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.checkImprimirAuto]));
			w13.TopAttach = ((uint)(3));
			w13.BottomAttach = ((uint)(4));
			w13.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.checkMesasPrimero = new global::Gtk.CheckButton ();
			this.checkMesasPrimero.CanFocus = true;
			this.checkMesasPrimero.Name = "checkMesasPrimero";
			this.checkMesasPrimero.Label = global::Mono.Unix.Catalog.GetString ("Identificacion primero");
			this.checkMesasPrimero.DrawIndicator = true;
			this.checkMesasPrimero.UseUnderline = true;
			this.tableConfig.Add (this.checkMesasPrimero);
			global::Gtk.Table.TableChild w14 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.checkMesasPrimero]));
			w14.TopAttach = ((uint)(2));
			w14.BottomAttach = ((uint)(3));
			w14.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.checkVarios = new global::Gtk.CheckButton ();
			this.checkVarios.CanFocus = true;
			this.checkVarios.Name = "checkVarios";
			this.checkVarios.Label = global::Mono.Unix.Catalog.GetString ("Mostrar varios");
			this.checkVarios.DrawIndicator = true;
			this.checkVarios.UseUnderline = true;
			this.tableConfig.Add (this.checkVarios);
			global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.checkVarios]));
			w15.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.checkVariosConNombre = new global::Gtk.CheckButton ();
			this.checkVariosConNombre.CanFocus = true;
			this.checkVariosConNombre.Name = "checkVariosConNombre";
			this.checkVariosConNombre.Label = global::Mono.Unix.Catalog.GetString ("Mostrar varios con nombre");
			this.checkVariosConNombre.DrawIndicator = true;
			this.checkVariosConNombre.UseUnderline = true;
			this.tableConfig.Add (this.checkVariosConNombre);
			global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.checkVariosConNombre]));
			w16.TopAttach = ((uint)(1));
			w16.BottomAttach = ((uint)(2));
			w16.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Tiempo inf. Ticket");
			this.tableConfig.Add (this.label5);
			global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.label5]));
			w17.TopAttach = ((uint)(2));
			w17.BottomAttach = ((uint)(3));
			w17.LeftAttach = ((uint)(1));
			w17.RightAttach = ((uint)(2));
			w17.XOptions = ((global::Gtk.AttachOptions)(4));
			w17.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Tiempo para controles");
			this.tableConfig.Add (this.label6);
			global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.label6]));
			w18.TopAttach = ((uint)(3));
			w18.BottomAttach = ((uint)(4));
			w18.LeftAttach = ((uint)(1));
			w18.RightAttach = ((uint)(2));
			w18.XOptions = ((global::Gtk.AttachOptions)(4));
			w18.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Contraseña desbloqueo");
			this.tableConfig.Add (this.label8);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.label8]));
			w19.TopAttach = ((uint)(1));
			w19.BottomAttach = ((uint)(2));
			w19.LeftAttach = ((uint)(1));
			w19.RightAttach = ((uint)(2));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.txtContraseña = new global::Gtk.Entry ();
			this.txtContraseña.CanFocus = true;
			this.txtContraseña.Name = "txtContraseña";
			this.txtContraseña.IsEditable = true;
			this.txtContraseña.Visibility = false;
			this.txtContraseña.InvisibleChar = '●';
			this.tableConfig.Add (this.txtContraseña);
			global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.txtContraseña]));
			w20.TopAttach = ((uint)(1));
			w20.BottomAttach = ((uint)(2));
			w20.LeftAttach = ((uint)(2));
			w20.RightAttach = ((uint)(3));
			w20.XOptions = ((global::Gtk.AttachOptions)(4));
			w20.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.txtHoraIniTpv = new global::Valle.GtkUtilidades.TxtHoras ();
			this.txtHoraIniTpv.Events = ((global::Gdk.EventMask)(256));
			this.txtHoraIniTpv.Name = "txtHoraIniTpv";
			this.txtHoraIniTpv.Etiqueta = "Hora inicio tpv";
			this.tableConfig.Add (this.txtHoraIniTpv);
			global::Gtk.Table.TableChild w21 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.txtHoraIniTpv]));
			w21.TopAttach = ((uint)(4));
			w21.BottomAttach = ((uint)(5));
			w21.LeftAttach = ((uint)(1));
			w21.RightAttach = ((uint)(2));
			w21.XOptions = ((global::Gtk.AttachOptions)(4));
			w21.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.txtTempControles = new global::Gtk.SpinButton (0, 100, 1);
			this.txtTempControles.CanFocus = true;
			this.txtTempControles.Name = "txtTempControles";
			this.txtTempControles.Adjustment.PageIncrement = 10;
			this.txtTempControles.ClimbRate = 1;
			this.txtTempControles.Numeric = true;
			this.tableConfig.Add (this.txtTempControles);
			global::Gtk.Table.TableChild w22 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.txtTempControles]));
			w22.TopAttach = ((uint)(3));
			w22.BottomAttach = ((uint)(4));
			w22.LeftAttach = ((uint)(2));
			w22.RightAttach = ((uint)(3));
			w22.XOptions = ((global::Gtk.AttachOptions)(4));
			w22.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child tableConfig.Gtk.Table+TableChild
			this.txtTempNoAc = new global::Gtk.SpinButton (0, 100, 1);
			this.txtTempNoAc.CanFocus = true;
			this.txtTempNoAc.Name = "txtTempNoAc";
			this.txtTempNoAc.Adjustment.PageIncrement = 10;
			this.txtTempNoAc.ClimbRate = 1;
			this.txtTempNoAc.Numeric = true;
			this.tableConfig.Add (this.txtTempNoAc);
			global::Gtk.Table.TableChild w23 = ((global::Gtk.Table.TableChild)(this.tableConfig [this.txtTempNoAc]));
			w23.TopAttach = ((uint)(2));
			w23.BottomAttach = ((uint)(3));
			w23.LeftAttach = ((uint)(2));
			w23.RightAttach = ((uint)(3));
			w23.XOptions = ((global::Gtk.AttachOptions)(4));
			w23.YOptions = ((global::Gtk.AttachOptions)(4));
			this.tabConfig.Add (this.tableConfig);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Obciones de configuracion");
			this.tabConfig.SetTabLabel (this.tableConfig, this.label1);
			this.label1.ShowAll ();
			// Container child tabConfig.Gtk.Notebook+NotebookChild
			this.vboxZonasMesas = new global::Gtk.VBox ();
			this.vboxZonasMesas.Name = "vboxZonasMesas";
			this.vboxZonasMesas.Spacing = 6;
			// Container child vboxZonasMesas.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox ();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			this.vbox3.BorderWidth = ((uint)(6));
			// Container child vbox3.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Zonas no incluidas en el tpv");
			this.vbox3.Add (this.label10);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label10]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.tblZonasBase = new global::Gtk.TreeView ();
			this.tblZonasBase.CanFocus = true;
			this.tblZonasBase.Name = "tblZonasBase";
			this.GtkScrolledWindow.Add (this.tblZonasBase);
			this.vbox3.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
			w27.Position = 1;
			this.hbox8.Add (this.vbox3);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox3]));
			w28.Position = 0;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbuttonbox1 = new global::Gtk.VButtonBox ();
			this.vbuttonbox1.Name = "vbuttonbox1";
			this.vbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnAñadirZona = new global::Gtk.Button ();
			this.btnAñadirZona.CanFocus = true;
			this.btnAñadirZona.Name = "btnAñadirZona";
			this.btnAñadirZona.UseUnderline = true;
			// Container child btnAñadirZona.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/ARROW12Cx.ICO"));
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Añadir");
			w33.UseUnderline = true;
			w30.Add (w33);
			w29.Add (w30);
			this.btnAñadirZona.Add (w29);
			this.vbuttonbox1.Add (this.btnAñadirZona);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnAñadirZona]));
			w37.Expand = false;
			w37.Fill = false;
			// Container child vbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuitarZona = new global::Gtk.Button ();
			this.btnQuitarZona.CanFocus = true;
			this.btnQuitarZona.Name = "btnQuitarZona";
			this.btnQuitarZona.UseUnderline = true;
			// Container child btnQuitarZona.Gtk.Container+ContainerChild
			global::Gtk.Alignment w38 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w39 = new global::Gtk.HBox ();
			w39.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w40 = new global::Gtk.Image ();
			w40.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/ARROW12Bx.ICO"));
			w39.Add (w40);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w42 = new global::Gtk.Label ();
			w42.LabelProp = global::Mono.Unix.Catalog.GetString ("Quitar");
			w42.UseUnderline = true;
			w39.Add (w42);
			w38.Add (w39);
			this.btnQuitarZona.Add (w38);
			this.vbuttonbox1.Add (this.btnQuitarZona);
			global::Gtk.ButtonBox.ButtonBoxChild w46 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox1 [this.btnQuitarZona]));
			w46.Position = 1;
			w46.Expand = false;
			w46.Fill = false;
			this.hbox8.Add (this.vbuttonbox1);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbuttonbox1]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(6));
			// Container child vbox4.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Zonas incluidas en el tpv");
			this.vbox4.Add (this.label11);
			global::Gtk.Box.BoxChild w48 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label11]));
			w48.Position = 0;
			w48.Expand = false;
			w48.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.tblZonasTpv = new global::Gtk.TreeView ();
			this.tblZonasTpv.CanFocus = true;
			this.tblZonasTpv.Name = "tblZonasTpv";
			this.GtkScrolledWindow1.Add (this.tblZonasTpv);
			this.vbox4.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.GtkScrolledWindow1]));
			w50.Position = 1;
			this.hbox8.Add (this.vbox4);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.vbox4]));
			w51.Position = 2;
			this.vboxZonasMesas.Add (this.hbox8);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vboxZonasMesas [this.hbox8]));
			w52.Position = 0;
			// Container child vboxZonasMesas.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(6));
			// Container child vbox5.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Mesas de la zona seleccionada en el tpv");
			this.vbox5.Add (this.label12);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label12]));
			w53.Position = 0;
			w53.Expand = false;
			w53.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
			this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
			this.tblMesasZona = new global::Gtk.TreeView ();
			this.tblMesasZona.CanFocus = true;
			this.tblMesasZona.Name = "tblMesasZona";
			this.GtkScrolledWindow2.Add (this.tblMesasZona);
			this.vbox5.Add (this.GtkScrolledWindow2);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.GtkScrolledWindow2]));
			w55.Position = 1;
			this.vboxZonasMesas.Add (this.vbox5);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vboxZonasMesas [this.vbox5]));
			w56.Position = 1;
			this.tabConfig.Add (this.vboxZonasMesas);
			global::Gtk.Notebook.NotebookChild w57 = ((global::Gtk.Notebook.NotebookChild)(this.tabConfig [this.vboxZonasMesas]));
			w57.Position = 1;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Zonas y mesas");
			this.tabConfig.SetTabLabel (this.vboxZonasMesas, this.label4);
			this.label4.ShowAll ();
			// Container child tabConfig.Gtk.Notebook+NotebookChild
			this.vboxZonasMesas1 = new global::Gtk.VBox ();
			this.vboxZonasMesas1.Name = "vboxZonasMesas1";
			this.vboxZonasMesas1.Spacing = 6;
			// Container child vboxZonasMesas1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox13 = new global::Gtk.VBox ();
			this.vbox13.Name = "vbox13";
			this.vbox13.Spacing = 6;
			this.vbox13.BorderWidth = ((uint)(6));
			// Container child vbox13.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.Xalign = 0F;
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Secciones no incluidas en el tpv");
			this.vbox13.Add (this.label13);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.label13]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vbox13.Gtk.Box+BoxChild
			this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
			this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
			this.tblSeccionesBase = new global::Gtk.TreeView ();
			this.tblSeccionesBase.CanFocus = true;
			this.tblSeccionesBase.Name = "tblSeccionesBase";
			this.GtkScrolledWindow3.Add (this.tblSeccionesBase);
			this.vbox13.Add (this.GtkScrolledWindow3);
			global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.GtkScrolledWindow3]));
			w60.Position = 1;
			this.hbox4.Add (this.vbox13);
			global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox13]));
			w61.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbuttonbox2 = new global::Gtk.VButtonBox ();
			this.vbuttonbox2.Name = "vbuttonbox2";
			this.vbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnAñadirSec = new global::Gtk.Button ();
			this.btnAñadirSec.CanFocus = true;
			this.btnAñadirSec.Name = "btnAñadirSec";
			this.btnAñadirSec.UseUnderline = true;
			// Container child btnAñadirSec.Gtk.Container+ContainerChild
			global::Gtk.Alignment w62 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w63 = new global::Gtk.HBox ();
			w63.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w64 = new global::Gtk.Image ();
			w64.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/ARROW12Cx.ICO"));
			w63.Add (w64);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w66 = new global::Gtk.Label ();
			w66.LabelProp = global::Mono.Unix.Catalog.GetString ("Añadir");
			w66.UseUnderline = true;
			w63.Add (w66);
			w62.Add (w63);
			this.btnAñadirSec.Add (w62);
			this.vbuttonbox2.Add (this.btnAñadirSec);
			global::Gtk.ButtonBox.ButtonBoxChild w70 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.btnAñadirSec]));
			w70.Expand = false;
			w70.Fill = false;
			// Container child vbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuitarSec = new global::Gtk.Button ();
			this.btnQuitarSec.CanFocus = true;
			this.btnQuitarSec.Name = "btnQuitarSec";
			this.btnQuitarSec.UseUnderline = true;
			// Container child btnQuitarSec.Gtk.Container+ContainerChild
			global::Gtk.Alignment w71 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w72 = new global::Gtk.HBox ();
			w72.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w73 = new global::Gtk.Image ();
			w73.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/ARROW12Bx.ICO"));
			w72.Add (w73);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w75 = new global::Gtk.Label ();
			w75.LabelProp = global::Mono.Unix.Catalog.GetString ("Quitar");
			w75.UseUnderline = true;
			w72.Add (w75);
			w71.Add (w72);
			this.btnQuitarSec.Add (w71);
			this.vbuttonbox2.Add (this.btnQuitarSec);
			global::Gtk.ButtonBox.ButtonBoxChild w79 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox2 [this.btnQuitarSec]));
			w79.Position = 1;
			w79.Expand = false;
			w79.Fill = false;
			this.hbox4.Add (this.vbuttonbox2);
			global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbuttonbox2]));
			w80.Position = 1;
			w80.Expand = false;
			w80.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			this.vbox7.BorderWidth = ((uint)(6));
			// Container child vbox7.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Secciones en incluidas el tpv");
			this.vbox7.Add (this.label14);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label14]));
			w81.Position = 0;
			w81.Expand = false;
			w81.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.GtkScrolledWindow4 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow4.Name = "GtkScrolledWindow4";
			this.GtkScrolledWindow4.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow4.Gtk.Container+ContainerChild
			this.tblSeccionesTpv = new global::Gtk.TreeView ();
			this.tblSeccionesTpv.CanFocus = true;
			this.tblSeccionesTpv.Name = "tblSeccionesTpv";
			this.GtkScrolledWindow4.Add (this.tblSeccionesTpv);
			this.vbox7.Add (this.GtkScrolledWindow4);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkScrolledWindow4]));
			w83.Position = 1;
			this.hbox4.Add (this.vbox7);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.vbox7]));
			w84.Position = 2;
			this.vboxZonasMesas1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.vboxZonasMesas1 [this.hbox4]));
			w85.Position = 0;
			// Container child vboxZonasMesas1.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			this.vbox8.BorderWidth = ((uint)(6));
			// Container child vbox8.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label ();
			this.label15.Name = "label15";
			this.label15.Xalign = 0F;
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Teclas de la seccion del tpv seleccionada");
			this.vbox8.Add (this.label15);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label15]));
			w86.Position = 0;
			w86.Expand = false;
			w86.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
			this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
			this.tblTeclasSec = new global::Gtk.TreeView ();
			this.tblTeclasSec.CanFocus = true;
			this.tblTeclasSec.Name = "tblTeclasSec";
			this.GtkScrolledWindow5.Add (this.tblTeclasSec);
			this.vbox8.Add (this.GtkScrolledWindow5);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.GtkScrolledWindow5]));
			w88.Position = 1;
			this.vboxZonasMesas1.Add (this.vbox8);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.vboxZonasMesas1 [this.vbox8]));
			w89.Position = 1;
			this.tabConfig.Add (this.vboxZonasMesas1);
			global::Gtk.Notebook.NotebookChild w90 = ((global::Gtk.Notebook.NotebookChild)(this.tabConfig [this.vboxZonasMesas1]));
			w90.Position = 2;
			// Notebook tab
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Teclados y secciones");
			this.tabConfig.SetTabLabel (this.vboxZonasMesas1, this.label3);
			this.label3.ShowAll ();
			// Container child tabConfig.Gtk.Notebook+NotebookChild
			this.vboxZonasMesas2 = new global::Gtk.VBox ();
			this.vboxZonasMesas2.Name = "vboxZonasMesas2";
			this.vboxZonasMesas2.Spacing = 6;
			// Container child vboxZonasMesas2.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			this.vbox9.BorderWidth = ((uint)(6));
			// Container child vbox9.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label ();
			this.label16.Name = "label16";
			this.label16.Xalign = 0F;
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Favoritos no incluidos en el tpv");
			this.vbox9.Add (this.label16);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.label16]));
			w91.Position = 0;
			w91.Expand = false;
			w91.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
			this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
			this.tblBaseFav = new global::Gtk.TreeView ();
			this.tblBaseFav.CanFocus = true;
			this.tblBaseFav.Name = "tblBaseFav";
			this.GtkScrolledWindow6.Add (this.tblBaseFav);
			this.vbox9.Add (this.GtkScrolledWindow6);
			global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.GtkScrolledWindow6]));
			w93.Position = 1;
			this.hbox5.Add (this.vbox9);
			global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox9]));
			w94.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbuttonbox3 = new global::Gtk.VButtonBox ();
			this.vbuttonbox3.Name = "vbuttonbox3";
			this.vbuttonbox3.BorderWidth = ((uint)(3));
			this.vbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(1));
			// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.btnAñadirFav = new global::Gtk.Button ();
			this.btnAñadirFav.CanFocus = true;
			this.btnAñadirFav.Name = "btnAñadirFav";
			this.btnAñadirFav.UseUnderline = true;
			// Container child btnAñadirFav.Gtk.Container+ContainerChild
			global::Gtk.Alignment w95 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w96 = new global::Gtk.HBox ();
			w96.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w97 = new global::Gtk.Image ();
			w97.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/ARROW12Cx.ICO"));
			w96.Add (w97);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w99 = new global::Gtk.Label ();
			w99.LabelProp = global::Mono.Unix.Catalog.GetString ("Añadir");
			w99.UseUnderline = true;
			w96.Add (w99);
			w95.Add (w96);
			this.btnAñadirFav.Add (w95);
			this.vbuttonbox3.Add (this.btnAñadirFav);
			global::Gtk.ButtonBox.ButtonBoxChild w103 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3 [this.btnAñadirFav]));
			w103.Expand = false;
			w103.Fill = false;
			// Container child vbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuitarFav = new global::Gtk.Button ();
			this.btnQuitarFav.CanFocus = true;
			this.btnQuitarFav.Name = "btnQuitarFav";
			this.btnQuitarFav.UseUnderline = true;
			// Container child btnQuitarFav.Gtk.Container+ContainerChild
			global::Gtk.Alignment w104 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w105 = new global::Gtk.HBox ();
			w105.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w106 = new global::Gtk.Image ();
			w106.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/ARROW12Bx.ICO"));
			w105.Add (w106);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w108 = new global::Gtk.Label ();
			w108.LabelProp = global::Mono.Unix.Catalog.GetString ("Quitar");
			w108.UseUnderline = true;
			w105.Add (w108);
			w104.Add (w105);
			this.btnQuitarFav.Add (w104);
			this.vbuttonbox3.Add (this.btnQuitarFav);
			global::Gtk.ButtonBox.ButtonBoxChild w112 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox3 [this.btnQuitarFav]));
			w112.Position = 1;
			w112.Expand = false;
			w112.Fill = false;
			this.hbox5.Add (this.vbuttonbox3);
			global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbuttonbox3]));
			w113.Position = 1;
			w113.Expand = false;
			w113.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			this.vbox10.BorderWidth = ((uint)(6));
			// Container child vbox10.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtHoraIniFav = new global::Valle.GtkUtilidades.TxtHoras ();
			this.txtHoraIniFav.Sensitive = false;
			this.txtHoraIniFav.Events = ((global::Gdk.EventMask)(256));
			this.txtHoraIniFav.Name = "txtHoraIniFav";
			this.txtHoraIniFav.Etiqueta = "Hora inico favorito";
			this.hbox1.Add (this.txtHoraIniFav);
			global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtHoraIniFav]));
			w114.Position = 0;
			w114.Expand = false;
			w114.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbuttonbox4 = new global::Gtk.VButtonBox ();
			this.vbuttonbox4.Name = "vbuttonbox4";
			this.vbuttonbox4.BorderWidth = ((uint)(3));
			// Container child vbuttonbox4.Gtk.ButtonBox+ButtonBoxChild
			this.btnAceptarHor = new global::Gtk.Button ();
			this.btnAceptarHor.CanFocus = true;
			this.btnAceptarHor.Name = "btnAceptarHor";
			this.btnAceptarHor.UseStock = true;
			this.btnAceptarHor.UseUnderline = true;
			this.btnAceptarHor.Label = "gtk-ok";
			this.vbuttonbox4.Add (this.btnAceptarHor);
			global::Gtk.ButtonBox.ButtonBoxChild w115 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbuttonbox4 [this.btnAceptarHor]));
			w115.Expand = false;
			w115.Fill = false;
			this.hbox1.Add (this.vbuttonbox4);
			global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbuttonbox4]));
			w116.Position = 1;
			w116.Expand = false;
			w116.Fill = false;
			this.vbox10.Add (this.hbox1);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.hbox1]));
			w117.Position = 0;
			w117.Expand = false;
			w117.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label ();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Favoritos incluidos en el tpv");
			this.vbox10.Add (this.label17);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label17]));
			w118.Position = 1;
			w118.Expand = false;
			w118.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.GtkScrolledWindow7 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow7.Name = "GtkScrolledWindow7";
			this.GtkScrolledWindow7.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow7.Gtk.Container+ContainerChild
			this.tblTpvFav = new global::Gtk.TreeView ();
			this.tblTpvFav.CanFocus = true;
			this.tblTpvFav.Name = "tblTpvFav";
			this.GtkScrolledWindow7.Add (this.tblTpvFav);
			this.vbox10.Add (this.GtkScrolledWindow7);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.GtkScrolledWindow7]));
			w120.Position = 2;
			this.hbox5.Add (this.vbox10);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.vbox10]));
			w121.Position = 2;
			this.vboxZonasMesas2.Add (this.hbox5);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.vboxZonasMesas2 [this.hbox5]));
			w122.Position = 0;
			// Container child vboxZonasMesas2.Gtk.Box+BoxChild
			this.vbox12 = new global::Gtk.VBox ();
			this.vbox12.Name = "vbox12";
			this.vbox12.Spacing = 6;
			this.vbox12.BorderWidth = ((uint)(6));
			// Container child vbox12.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label ();
			this.label18.Name = "label18";
			this.label18.Xalign = 0F;
			this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Teclas de favoritos seleccionado en el tpv");
			this.vbox12.Add (this.label18);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.label18]));
			w123.Position = 0;
			w123.Expand = false;
			w123.Fill = false;
			// Container child vbox12.Gtk.Box+BoxChild
			this.GtkScrolledWindow8 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow8.Name = "GtkScrolledWindow8";
			this.GtkScrolledWindow8.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow8.Gtk.Container+ContainerChild
			this.tblTeclasFav = new global::Gtk.TreeView ();
			this.tblTeclasFav.CanFocus = true;
			this.tblTeclasFav.Name = "tblTeclasFav";
			this.GtkScrolledWindow8.Add (this.tblTeclasFav);
			this.vbox12.Add (this.GtkScrolledWindow8);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.GtkScrolledWindow8]));
			w125.Position = 1;
			this.vboxZonasMesas2.Add (this.vbox12);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.vboxZonasMesas2 [this.vbox12]));
			w126.Position = 1;
			this.tabConfig.Add (this.vboxZonasMesas2);
			global::Gtk.Notebook.NotebookChild w127 = ((global::Gtk.Notebook.NotebookChild)(this.tabConfig [this.vboxZonasMesas2]));
			w127.Position = 3;
			// Notebook tab
			this.label19 = new global::Gtk.Label ();
			this.label19.Name = "label19";
			this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Favoritos");
			this.tabConfig.SetTabLabel (this.vboxZonasMesas2, this.label19);
			this.label19.ShowAll ();
			this.vboxPrincipal.Add (this.tabConfig);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.tabConfig]));
			w128.Position = 1;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.grpModos = new global::Gtk.HButtonBox ();
			this.grpModos.Name = "grpModos";
			this.grpModos.Spacing = 14;
			this.grpModos.BorderWidth = ((uint)(6));
			this.grpModos.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditar = new global::Gtk.Button ();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			// Container child btnEditar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w129 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w130 = new global::Gtk.HBox ();
			w130.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w131 = new global::Gtk.Image ();
			w131.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_effects", global::Gtk.IconSize.Menu);
			w130.Add (w131);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w133 = new global::Gtk.Label ();
			w133.LabelProp = global::Mono.Unix.Catalog.GetString ("Editar");
			w133.UseUnderline = true;
			w130.Add (w133);
			w129.Add (w130);
			this.btnEditar.Add (w129);
			this.grpModos.Add (this.btnEditar);
			global::Gtk.ButtonBox.ButtonBoxChild w137 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnEditar]));
			w137.Expand = false;
			w137.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnAñadir = new global::Gtk.Button ();
			this.btnAñadir.CanFocus = true;
			this.btnAñadir.Name = "btnAñadir";
			this.btnAñadir.UseUnderline = true;
			// Container child btnAñadir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w138 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w139 = new global::Gtk.HBox ();
			w139.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w140 = new global::Gtk.Image ();
			w140.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w139.Add (w140);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w142 = new global::Gtk.Label ();
			w142.LabelProp = global::Mono.Unix.Catalog.GetString ("Añadir");
			w142.UseUnderline = true;
			w139.Add (w142);
			w138.Add (w139);
			this.btnAñadir.Add (w138);
			this.grpModos.Add (this.btnAñadir);
			global::Gtk.ButtonBox.ButtonBoxChild w146 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnAñadir]));
			w146.Position = 1;
			w146.Expand = false;
			w146.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnBorrar = new global::Gtk.Button ();
			this.btnBorrar.CanFocus = true;
			this.btnBorrar.Name = "btnBorrar";
			this.btnBorrar.UseUnderline = true;
			// Container child btnBorrar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w147 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w148 = new global::Gtk.HBox ();
			w148.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w149 = new global::Gtk.Image ();
			w149.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w148.Add (w149);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w151 = new global::Gtk.Label ();
			w151.LabelProp = global::Mono.Unix.Catalog.GetString ("Borrar art");
			w151.UseUnderline = true;
			w148.Add (w151);
			w147.Add (w148);
			this.btnBorrar.Add (w147);
			this.grpModos.Add (this.btnBorrar);
			global::Gtk.ButtonBox.ButtonBoxChild w155 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnBorrar]));
			w155.Position = 2;
			w155.Expand = false;
			w155.Fill = false;
			this.vboxPrincipal.Add (this.grpModos);
			global::Gtk.Box.BoxChild w156 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.grpModos]));
			w156.Position = 2;
			w156.Expand = false;
			w156.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox ();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.grpModos1 = new global::Gtk.HButtonBox ();
			this.grpModos1.Name = "grpModos1";
			this.grpModos1.Spacing = 14;
			this.grpModos1.BorderWidth = ((uint)(6));
			this.grpModos1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child grpModos1.Gtk.ButtonBox+ButtonBoxChild
			this.btnAceptar = new global::Gtk.Button ();
			this.btnAceptar.CanFocus = true;
			this.btnAceptar.Name = "btnAceptar";
			this.btnAceptar.UseStock = true;
			this.btnAceptar.UseUnderline = true;
			this.btnAceptar.Label = "gtk-ok";
			this.grpModos1.Add (this.btnAceptar);
			global::Gtk.ButtonBox.ButtonBoxChild w157 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos1 [this.btnAceptar]));
			w157.Expand = false;
			w157.Fill = false;
			// Container child grpModos1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w158 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w159 = new global::Gtk.HBox ();
			w159.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w160 = new global::Gtk.Image ();
			w160.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/EXIT00C.ICO"));
			w159.Add (w160);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w162 = new global::Gtk.Label ();
			w162.LabelProp = global::Mono.Unix.Catalog.GetString ("Salir");
			w162.UseUnderline = true;
			w159.Add (w162);
			w158.Add (w159);
			this.btnSalir.Add (w158);
			this.grpModos1.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w166 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos1 [this.btnSalir]));
			w166.Position = 1;
			w166.Expand = false;
			w166.Fill = false;
			this.hbox7.Add (this.grpModos1);
			global::Gtk.Box.BoxChild w167 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.grpModos1]));
			w167.Position = 2;
			this.vboxPrincipal.Add (this.hbox7);
			global::Gtk.Box.BoxChild w168 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.hbox7]));
			w168.Position = 3;
			w168.Expand = false;
			w168.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.lblInformacion = new global::Gtk.Label ();
			this.lblInformacion.Name = "lblInformacion";
			this.lblInformacion.Xalign = 0F;
			this.lblInformacion.LabelProp = global::Mono.Unix.Catalog.GetString ("Modo no editable activado");
			this.vboxPrincipal.Add (this.lblInformacion);
			global::Gtk.Box.BoxChild w169 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.lblInformacion]));
			w169.Position = 4;
			w169.Expand = false;
			w169.Fill = false;
			this.Add (this.vboxPrincipal);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 651;
			this.DefaultHeight = 738;
			this.btnAceptar.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.cmbTpvs.Changed += new global::System.EventHandler (this.OnCmbTpvsChanged);
			this.btnAñadirTpvs.Clicked += new global::System.EventHandler (this.OnBtnAñadirTpvsClicked);
			this.btnAñadirZona.Clicked += new global::System.EventHandler (this.OnBtnAñadirZonaClicked);
			this.btnQuitarZona.Clicked += new global::System.EventHandler (this.OnBtnQuitarZonaClicked);
			this.tblZonasTpv.CursorChanged += new global::System.EventHandler (this.OnTblZonasTpvCursorChanged);
			this.btnAñadirSec.Clicked += new global::System.EventHandler (this.OnBtnAñadirSecClicked);
			this.btnQuitarSec.Clicked += new global::System.EventHandler (this.OnBtnQuitarSecClicked);
			this.tblSeccionesTpv.CursorChanged += new global::System.EventHandler (this.OnTblSeccionesTpvCursorChanged);
			this.btnAñadirFav.Clicked += new global::System.EventHandler (this.OnBtnAñadirFavClicked);
			this.btnQuitarFav.Clicked += new global::System.EventHandler (this.OnBtnQuitarFavClicked);
			this.btnAceptarHor.Clicked += new global::System.EventHandler (this.OnBtnAceptarHorClicked);
			this.tblTpvFav.CursorChanged += new global::System.EventHandler (this.OnTblTpvFavCursorChanged);
			this.btnEditar.Clicked += new global::System.EventHandler (this.OnBtnEditarClicked);
			this.btnAceptar.Clicked += new global::System.EventHandler (this.OnBtnAceptarClicked);
			this.btnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
