
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GesTpv
{
	public partial class VenArticulos
	{
		private global::Gtk.VBox vboxPrincipal;
		private global::Gtk.Table table1;
		private global::Gtk.HButtonBox grpNavegador;
		private global::Gtk.Button btnPrimero;
		private global::Gtk.Button btnAtras;
		private global::Gtk.Button btnSiguiente;
		private global::Gtk.Button btnUltimo;
		private global::Gtk.VBox vboxInfReg;
		private global::Gtk.Label lblTotalReg;
		private global::Gtk.Label lblRegAct;
		private global::Gtk.VBox vboxInfReg1;
		private global::Gtk.Label lblIDArt;
		private global::Gtk.Label lblNomArt;
		private global::Gtk.Notebook tabArticulos;
		private global::Gtk.Table pneDatosArt;
		private global::Gtk.Button btnGrabar;
		private global::Gtk.VBox vbox1;
		private global::Gtk.CheckButton chkPorKilos;
		private global::Gtk.CheckButton chkNoEnVenta;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label5;
		private global::Gtk.SpinButton txtPrecioDos;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label6;
		private global::Gtk.SpinButton txtPrecioTres;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label4;
		private global::Gtk.SpinButton txtPrecioUno;
		private global::Gtk.VBox vboxFamilias;
		private global::Gtk.Label label7;
		private global::Gtk.HBox hbox1;
		private global::Gtk.ComboBox cmbFamilias;
		private global::Gtk.Button btnAñadirFam;
		private global::Gtk.VBox vboxIDArt;
		private global::Gtk.Label label2;
		private global::Gtk.SpinButton txtID;
		private global::Gtk.VBox vboxNombre;
		private global::Gtk.Label label3;
		private global::Gtk.Entry txtNombre;
		private global::Gtk.Label label8;
		private global::Gtk.VBox pneDesglose;
		private global::Gtk.HBox hbox5;
		private global::Gtk.Label lblNomArtDes;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnBuscarAgre;
		private global::Gtk.Button btnCrearAgre;
		private global::Gtk.HBox hbox6;
		private global::Gtk.VBox vboxInfReg2;
		private global::Gtk.Label lblTotalReg1;
		private global::Gtk.SpinButton spnCantidad;
		private global::Gtk.VBox vboxInfReg3;
		private global::Gtk.Label lblTotalReg2;
		private global::Gtk.SpinButton spnGrupo;
		private global::Gtk.VBox vboxInfReg4;
		private global::Gtk.Label lblTotalReg3;
		private global::Gtk.SpinButton spnIncremento;
		private global::Gtk.VBox vbox9;
		private global::Gtk.Button btnAceptarDes;
		private global::Gtk.Button btnBorrarDes;
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		private global::Gtk.TreeView treeDesgloses;
		private global::Gtk.Label label9;
		private global::Gtk.VBox pneControlStock;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vboxFamilias1;
		private global::Gtk.Label label14;
		private global::Gtk.HBox hbox4;
		private global::Gtk.ComboBox cmbAlmacen;
		private global::Gtk.Button btnMasAlm;
		private global::Gtk.VBox vbox10;
		private global::Gtk.Label label1;
		private global::Gtk.SpinButton spnNivel;
		private global::Gtk.HBox hbox3;
		private global::Gtk.VBox vbox8;
		private global::Gtk.Label label10;
		private global::Gtk.SpinButton spnStockMax;
		private global::Gtk.VBox vbox6;
		private global::Gtk.Label label11;
		private global::Gtk.SpinButton spnSockMini;
		private global::Gtk.VBox vbox7;
		private global::Gtk.Label label12;
		private global::Gtk.SpinButton spnStockActual;
		private global::Gtk.VButtonBox vbtControl;
		private global::Gtk.Button btnAceptarAlm;
		private global::Gtk.Button btnBorrarAlm;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView treeAlmacenes;
		private global::Gtk.Label label13;
		private global::Gtk.HButtonBox grpModos;
		private global::Gtk.Button btnBuscar;
		private global::Gtk.Button btnAceptar;
		private global::Gtk.Button btnEditar;
		private global::Gtk.Button btnAñadir;
		private global::Gtk.Button btnMasArt;
		private global::Gtk.Button btnBorrar;
		private global::Gtk.Button btnSalir;
		private global::Gtk.Label lblInformacion;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GesTpv.VenArticulos
			this.Name = "Valle.GesTpv.VenArticulos";
			this.Title = global::Mono.Unix.Catalog.GetString ("Gestion de articulos");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/exec.gif"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Valle.GesTpv.VenArticulos.Gtk.Container+ContainerChild
			this.vboxPrincipal = new global::Gtk.VBox ();
			this.vboxPrincipal.Name = "vboxPrincipal";
			this.vboxPrincipal.Spacing = 6;
			this.vboxPrincipal.BorderWidth = ((uint)(9));
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(2)), ((uint)(2)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.grpNavegador = new global::Gtk.HButtonBox ();
			this.grpNavegador.Name = "grpNavegador";
			this.grpNavegador.BorderWidth = ((uint)(12));
			// Container child grpNavegador.Gtk.ButtonBox+ButtonBoxChild
			this.btnPrimero = new global::Gtk.Button ();
			this.btnPrimero.CanFocus = true;
			this.btnPrimero.Name = "btnPrimero";
			this.btnPrimero.UseUnderline = true;
			// Container child btnPrimero.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_first", global::Gtk.IconSize.Menu);
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w2.Add (w5);
			w1.Add (w2);
			this.btnPrimero.Add (w1);
			this.grpNavegador.Add (this.btnPrimero);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpNavegador [this.btnPrimero]));
			w9.Expand = false;
			w9.Fill = false;
			// Container child grpNavegador.Gtk.ButtonBox+ButtonBoxChild
			this.btnAtras = new global::Gtk.Button ();
			this.btnAtras.CanFocus = true;
			this.btnAtras.Name = "btnAtras";
			this.btnAtras.UseUnderline = true;
			// Container child btnAtras.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_left", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w11.Add (w14);
			w10.Add (w11);
			this.btnAtras.Add (w10);
			this.grpNavegador.Add (this.btnAtras);
			global::Gtk.ButtonBox.ButtonBoxChild w18 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpNavegador [this.btnAtras]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child grpNavegador.Gtk.ButtonBox+ButtonBoxChild
			this.btnSiguiente = new global::Gtk.Button ();
			this.btnSiguiente.CanFocus = true;
			this.btnSiguiente.Name = "btnSiguiente";
			this.btnSiguiente.UseUnderline = true;
			// Container child btnSiguiente.Gtk.Container+ContainerChild
			global::Gtk.Alignment w19 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w20 = new global::Gtk.HBox ();
			w20.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w21 = new global::Gtk.Image ();
			w21.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_right", global::Gtk.IconSize.Menu);
			w20.Add (w21);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w23 = new global::Gtk.Label ();
			w20.Add (w23);
			w19.Add (w20);
			this.btnSiguiente.Add (w19);
			this.grpNavegador.Add (this.btnSiguiente);
			global::Gtk.ButtonBox.ButtonBoxChild w27 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpNavegador [this.btnSiguiente]));
			w27.Position = 2;
			w27.Expand = false;
			w27.Fill = false;
			// Container child grpNavegador.Gtk.ButtonBox+ButtonBoxChild
			this.btnUltimo = new global::Gtk.Button ();
			this.btnUltimo.CanFocus = true;
			this.btnUltimo.Name = "btnUltimo";
			this.btnUltimo.UseUnderline = true;
			// Container child btnUltimo.Gtk.Container+ContainerChild
			global::Gtk.Alignment w28 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w29 = new global::Gtk.HBox ();
			w29.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w30 = new global::Gtk.Image ();
			w30.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_last", global::Gtk.IconSize.Menu);
			w29.Add (w30);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w32 = new global::Gtk.Label ();
			w29.Add (w32);
			w28.Add (w29);
			this.btnUltimo.Add (w28);
			this.grpNavegador.Add (this.btnUltimo);
			global::Gtk.ButtonBox.ButtonBoxChild w36 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpNavegador [this.btnUltimo]));
			w36.Position = 3;
			w36.Expand = false;
			w36.Fill = false;
			this.table1.Add (this.grpNavegador);
			global::Gtk.Table.TableChild w37 = ((global::Gtk.Table.TableChild)(this.table1 [this.grpNavegador]));
			w37.XOptions = ((global::Gtk.AttachOptions)(4));
			w37.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vboxInfReg = new global::Gtk.VBox ();
			this.vboxInfReg.Name = "vboxInfReg";
			this.vboxInfReg.Spacing = 6;
			// Container child vboxInfReg.Gtk.Box+BoxChild
			this.lblTotalReg = new global::Gtk.Label ();
			this.lblTotalReg.Name = "lblTotalReg";
			this.lblTotalReg.Xalign = 0F;
			this.lblTotalReg.LabelProp = global::Mono.Unix.Catalog.GetString ("Nun Registros");
			this.vboxInfReg.Add (this.lblTotalReg);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg [this.lblTotalReg]));
			w38.Position = 0;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vboxInfReg.Gtk.Box+BoxChild
			this.lblRegAct = new global::Gtk.Label ();
			this.lblRegAct.Name = "lblRegAct";
			this.lblRegAct.Xalign = 0F;
			this.lblRegAct.LabelProp = global::Mono.Unix.Catalog.GetString ("Registro");
			this.vboxInfReg.Add (this.lblRegAct);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg [this.lblRegAct]));
			w39.Position = 1;
			w39.Expand = false;
			w39.Fill = false;
			this.table1.Add (this.vboxInfReg);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table1 [this.vboxInfReg]));
			w40.LeftAttach = ((uint)(1));
			w40.RightAttach = ((uint)(2));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.vboxInfReg1 = new global::Gtk.VBox ();
			this.vboxInfReg1.Name = "vboxInfReg1";
			this.vboxInfReg1.Spacing = 6;
			// Container child vboxInfReg1.Gtk.Box+BoxChild
			this.lblIDArt = new global::Gtk.Label ();
			this.lblIDArt.Name = "lblIDArt";
			this.lblIDArt.Xalign = 0F;
			this.lblIDArt.LabelProp = global::Mono.Unix.Catalog.GetString ("ID del articulo");
			this.vboxInfReg1.Add (this.lblIDArt);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg1 [this.lblIDArt]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vboxInfReg1.Gtk.Box+BoxChild
			this.lblNomArt = new global::Gtk.Label ();
			this.lblNomArt.Name = "lblNomArt";
			this.lblNomArt.Xalign = 0F;
			this.lblNomArt.LabelProp = global::Mono.Unix.Catalog.GetString ("NomArticulo");
			this.vboxInfReg1.Add (this.lblNomArt);
			global::Gtk.Box.BoxChild w42 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg1 [this.lblNomArt]));
			w42.Position = 1;
			w42.Expand = false;
			w42.Fill = false;
			this.table1.Add (this.vboxInfReg1);
			global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1 [this.vboxInfReg1]));
			w43.TopAttach = ((uint)(1));
			w43.BottomAttach = ((uint)(2));
			w43.XOptions = ((global::Gtk.AttachOptions)(4));
			w43.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vboxPrincipal.Add (this.table1);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.table1]));
			w44.Position = 0;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.tabArticulos = new global::Gtk.Notebook ();
			this.tabArticulos.HeightRequest = 455;
			this.tabArticulos.CanFocus = true;
			this.tabArticulos.Name = "tabArticulos";
			this.tabArticulos.CurrentPage = 0;
			// Container child tabArticulos.Gtk.Notebook+NotebookChild
			this.pneDatosArt = new global::Gtk.Table (((uint)(3)), ((uint)(4)), false);
			this.pneDatosArt.Name = "pneDatosArt";
			this.pneDatosArt.RowSpacing = ((uint)(4));
			this.pneDatosArt.ColumnSpacing = ((uint)(14));
			this.pneDatosArt.BorderWidth = ((uint)(30));
			// Container child pneDatosArt.Gtk.Table+TableChild
			this.btnGrabar = new global::Gtk.Button ();
			this.btnGrabar.CanFocus = true;
			this.btnGrabar.Name = "btnGrabar";
			this.btnGrabar.UseStock = true;
			this.btnGrabar.UseUnderline = true;
			this.btnGrabar.BorderWidth = ((uint)(6));
			this.btnGrabar.Label = "gtk-save";
			this.pneDatosArt.Add (this.btnGrabar);
			global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.pneDatosArt [this.btnGrabar]));
			w45.TopAttach = ((uint)(2));
			w45.BottomAttach = ((uint)(3));
			w45.LeftAttach = ((uint)(3));
			w45.RightAttach = ((uint)(4));
			w45.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pneDatosArt.Gtk.Table+TableChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.chkPorKilos = new global::Gtk.CheckButton ();
			this.chkPorKilos.CanFocus = true;
			this.chkPorKilos.Name = "chkPorKilos";
			this.chkPorKilos.Label = global::Mono.Unix.Catalog.GetString ("Se vende por kilos");
			this.chkPorKilos.DrawIndicator = true;
			this.chkPorKilos.UseUnderline = true;
			this.vbox1.Add (this.chkPorKilos);
			global::Gtk.Box.BoxChild w46 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.chkPorKilos]));
			w46.Position = 0;
			w46.Expand = false;
			w46.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.chkNoEnVenta = new global::Gtk.CheckButton ();
			this.chkNoEnVenta.CanFocus = true;
			this.chkNoEnVenta.Name = "chkNoEnVenta";
			this.chkNoEnVenta.Label = global::Mono.Unix.Catalog.GetString ("Producto no en venta");
			this.chkNoEnVenta.DrawIndicator = true;
			this.chkNoEnVenta.UseUnderline = true;
			this.vbox1.Add (this.chkNoEnVenta);
			global::Gtk.Box.BoxChild w47 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.chkNoEnVenta]));
			w47.Position = 1;
			w47.Expand = false;
			w47.Fill = false;
			this.pneDatosArt.Add (this.vbox1);
			global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.pneDatosArt [this.vbox1]));
			w48.LeftAttach = ((uint)(2));
			w48.RightAttach = ((uint)(3));
			w48.XOptions = ((global::Gtk.AttachOptions)(4));
			w48.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pneDatosArt.Gtk.Table+TableChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Tarifa 2");
			this.vbox2.Add (this.label5);
			global::Gtk.Box.BoxChild w49 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label5]));
			w49.Position = 0;
			w49.Expand = false;
			w49.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.txtPrecioDos = new global::Gtk.SpinButton (0, 100, 1);
			this.txtPrecioDos.CanFocus = true;
			this.txtPrecioDos.Name = "txtPrecioDos";
			this.txtPrecioDos.Adjustment.PageIncrement = 10;
			this.txtPrecioDos.ClimbRate = 1;
			this.txtPrecioDos.Digits = ((uint)(2));
			this.txtPrecioDos.Numeric = true;
			this.vbox2.Add (this.txtPrecioDos);
			global::Gtk.Box.BoxChild w50 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.txtPrecioDos]));
			w50.Position = 1;
			w50.Expand = false;
			w50.Fill = false;
			this.pneDatosArt.Add (this.vbox2);
			global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.pneDatosArt [this.vbox2]));
			w51.TopAttach = ((uint)(2));
			w51.BottomAttach = ((uint)(3));
			w51.LeftAttach = ((uint)(1));
			w51.RightAttach = ((uint)(2));
			w51.XOptions = ((global::Gtk.AttachOptions)(4));
			w51.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pneDatosArt.Gtk.Table+TableChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label ();
			this.label6.Name = "label6";
			this.label6.Xalign = 0F;
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Tarifa 3");
			this.vbox3.Add (this.label6);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label6]));
			w52.Position = 0;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtPrecioTres = new global::Gtk.SpinButton (0, 100, 1);
			this.txtPrecioTres.CanFocus = true;
			this.txtPrecioTres.Name = "txtPrecioTres";
			this.txtPrecioTres.Adjustment.PageIncrement = 10;
			this.txtPrecioTres.ClimbRate = 1;
			this.txtPrecioTres.Digits = ((uint)(2));
			this.txtPrecioTres.Numeric = true;
			this.vbox3.Add (this.txtPrecioTres);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.txtPrecioTres]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			this.pneDatosArt.Add (this.vbox3);
			global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.pneDatosArt [this.vbox3]));
			w54.TopAttach = ((uint)(2));
			w54.BottomAttach = ((uint)(3));
			w54.LeftAttach = ((uint)(2));
			w54.RightAttach = ((uint)(3));
			w54.XOptions = ((global::Gtk.AttachOptions)(4));
			w54.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pneDatosArt.Gtk.Table+TableChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Tarifa 1");
			this.vbox4.Add (this.label4);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label4]));
			w55.Position = 0;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txtPrecioUno = new global::Gtk.SpinButton (0, 100, 1);
			this.txtPrecioUno.CanFocus = true;
			this.txtPrecioUno.Name = "txtPrecioUno";
			this.txtPrecioUno.Adjustment.PageIncrement = 10;
			this.txtPrecioUno.ClimbRate = 1;
			this.txtPrecioUno.Digits = ((uint)(2));
			this.txtPrecioUno.Numeric = true;
			this.vbox4.Add (this.txtPrecioUno);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.txtPrecioUno]));
			w56.Position = 1;
			w56.Expand = false;
			w56.Fill = false;
			this.pneDatosArt.Add (this.vbox4);
			global::Gtk.Table.TableChild w57 = ((global::Gtk.Table.TableChild)(this.pneDatosArt [this.vbox4]));
			w57.TopAttach = ((uint)(2));
			w57.BottomAttach = ((uint)(3));
			w57.XOptions = ((global::Gtk.AttachOptions)(4));
			w57.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pneDatosArt.Gtk.Table+TableChild
			this.vboxFamilias = new global::Gtk.VBox ();
			this.vboxFamilias.Name = "vboxFamilias";
			this.vboxFamilias.Spacing = 6;
			// Container child vboxFamilias.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label ();
			this.label7.Name = "label7";
			this.label7.Xalign = 0F;
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Familia");
			this.vboxFamilias.Add (this.label7);
			global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vboxFamilias [this.label7]));
			w58.Position = 0;
			w58.Expand = false;
			w58.Fill = false;
			// Container child vboxFamilias.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.cmbFamilias = global::Gtk.ComboBox.NewText ();
			this.cmbFamilias.WidthRequest = 200;
			this.cmbFamilias.Name = "cmbFamilias";
			this.hbox1.Add (this.cmbFamilias);
			global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.cmbFamilias]));
			w59.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.btnAñadirFam = new global::Gtk.Button ();
			this.btnAñadirFam.CanFocus = true;
			this.btnAñadirFam.Name = "btnAñadirFam";
			this.btnAñadirFam.UseUnderline = true;
			// Container child btnAñadirFam.Gtk.Container+ContainerChild
			global::Gtk.Alignment w60 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w61 = new global::Gtk.HBox ();
			w61.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w62 = new global::Gtk.Image ();
			w62.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w61.Add (w62);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w64 = new global::Gtk.Label ();
			w61.Add (w64);
			w60.Add (w61);
			this.btnAñadirFam.Add (w60);
			this.hbox1.Add (this.btnAñadirFam);
			global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.btnAñadirFam]));
			w68.Position = 1;
			w68.Expand = false;
			w68.Fill = false;
			this.vboxFamilias.Add (this.hbox1);
			global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.vboxFamilias [this.hbox1]));
			w69.Position = 1;
			w69.Expand = false;
			w69.Fill = false;
			this.pneDatosArt.Add (this.vboxFamilias);
			global::Gtk.Table.TableChild w70 = ((global::Gtk.Table.TableChild)(this.pneDatosArt [this.vboxFamilias]));
			w70.XOptions = ((global::Gtk.AttachOptions)(4));
			w70.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pneDatosArt.Gtk.Table+TableChild
			this.vboxIDArt = new global::Gtk.VBox ();
			this.vboxIDArt.Name = "vboxIDArt";
			this.vboxIDArt.Spacing = 6;
			// Container child vboxIDArt.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Ref Articulo");
			this.vboxIDArt.Add (this.label2);
			global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.vboxIDArt [this.label2]));
			w71.Position = 0;
			w71.Expand = false;
			w71.Fill = false;
			// Container child vboxIDArt.Gtk.Box+BoxChild
			this.txtID = new global::Gtk.SpinButton (0, 1E+25, 1);
			this.txtID.CanFocus = true;
			this.txtID.Name = "txtID";
			this.txtID.Adjustment.PageIncrement = 10;
			this.txtID.ClimbRate = 1;
			this.txtID.Numeric = true;
			this.vboxIDArt.Add (this.txtID);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vboxIDArt [this.txtID]));
			w72.Position = 1;
			w72.Expand = false;
			w72.Fill = false;
			this.pneDatosArt.Add (this.vboxIDArt);
			global::Gtk.Table.TableChild w73 = ((global::Gtk.Table.TableChild)(this.pneDatosArt [this.vboxIDArt]));
			w73.TopAttach = ((uint)(1));
			w73.BottomAttach = ((uint)(2));
			w73.XOptions = ((global::Gtk.AttachOptions)(4));
			w73.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child pneDatosArt.Gtk.Table+TableChild
			this.vboxNombre = new global::Gtk.VBox ();
			this.vboxNombre.Name = "vboxNombre";
			this.vboxNombre.Spacing = 6;
			// Container child vboxNombre.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
			this.vboxNombre.Add (this.label3);
			global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.vboxNombre [this.label3]));
			w74.Position = 0;
			w74.Expand = false;
			w74.Fill = false;
			// Container child vboxNombre.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry ();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '●';
			this.vboxNombre.Add (this.txtNombre);
			global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.vboxNombre [this.txtNombre]));
			w75.Position = 1;
			w75.Expand = false;
			w75.Fill = false;
			this.pneDatosArt.Add (this.vboxNombre);
			global::Gtk.Table.TableChild w76 = ((global::Gtk.Table.TableChild)(this.pneDatosArt [this.vboxNombre]));
			w76.TopAttach = ((uint)(1));
			w76.BottomAttach = ((uint)(2));
			w76.LeftAttach = ((uint)(1));
			w76.RightAttach = ((uint)(2));
			w76.XOptions = ((global::Gtk.AttachOptions)(4));
			w76.YOptions = ((global::Gtk.AttachOptions)(4));
			this.tabArticulos.Add (this.pneDatosArt);
			// Notebook tab
			this.label8 = new global::Gtk.Label ();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Datos Articulos");
			this.tabArticulos.SetTabLabel (this.pneDatosArt, this.label8);
			this.label8.ShowAll ();
			// Container child tabArticulos.Gtk.Notebook+NotebookChild
			this.pneDesglose = new global::Gtk.VBox ();
			this.pneDesglose.Name = "pneDesglose";
			this.pneDesglose.Spacing = 6;
			this.pneDesglose.BorderWidth = ((uint)(15));
			// Container child pneDesglose.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.lblNomArtDes = new global::Gtk.Label ();
			this.lblNomArtDes.Name = "lblNomArtDes";
			this.lblNomArtDes.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre del articulo");
			this.hbox5.Add (this.lblNomArtDes);
			global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.lblNomArtDes]));
			w78.Position = 0;
			w78.Expand = false;
			w78.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.Spacing = 4;
			this.hbuttonbox1.BorderWidth = ((uint)(3));
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnBuscarAgre = new global::Gtk.Button ();
			this.btnBuscarAgre.CanFocus = true;
			this.btnBuscarAgre.Name = "btnBuscarAgre";
			this.btnBuscarAgre.UseUnderline = true;
			this.btnBuscarAgre.BorderWidth = ((uint)(3));
			this.btnBuscarAgre.Label = global::Mono.Unix.Catalog.GetString ("Buscar y agregar articulo");
			this.hbuttonbox1.Add (this.btnBuscarAgre);
			global::Gtk.ButtonBox.ButtonBoxChild w79 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnBuscarAgre]));
			w79.Expand = false;
			w79.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnCrearAgre = new global::Gtk.Button ();
			this.btnCrearAgre.CanFocus = true;
			this.btnCrearAgre.Name = "btnCrearAgre";
			this.btnCrearAgre.UseUnderline = true;
			this.btnCrearAgre.BorderWidth = ((uint)(3));
			this.btnCrearAgre.Label = global::Mono.Unix.Catalog.GetString ("Crear y agregar articulo");
			this.hbuttonbox1.Add (this.btnCrearAgre);
			global::Gtk.ButtonBox.ButtonBoxChild w80 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnCrearAgre]));
			w80.Position = 1;
			w80.Expand = false;
			w80.Fill = false;
			this.hbox5.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.hbuttonbox1]));
			w81.Position = 1;
			this.pneDesglose.Add (this.hbox5);
			global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.pneDesglose [this.hbox5]));
			w82.Position = 0;
			w82.Expand = false;
			w82.Fill = false;
			// Container child pneDesglose.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vboxInfReg2 = new global::Gtk.VBox ();
			this.vboxInfReg2.Name = "vboxInfReg2";
			this.vboxInfReg2.Spacing = 6;
			this.vboxInfReg2.BorderWidth = ((uint)(6));
			// Container child vboxInfReg2.Gtk.Box+BoxChild
			this.lblTotalReg1 = new global::Gtk.Label ();
			this.lblTotalReg1.Name = "lblTotalReg1";
			this.lblTotalReg1.Xalign = 0F;
			this.lblTotalReg1.LabelProp = global::Mono.Unix.Catalog.GetString ("Cantidad de articulos que genera ");
			this.vboxInfReg2.Add (this.lblTotalReg1);
			global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg2 [this.lblTotalReg1]));
			w83.Position = 0;
			w83.Expand = false;
			w83.Fill = false;
			// Container child vboxInfReg2.Gtk.Box+BoxChild
			this.spnCantidad = new global::Gtk.SpinButton (0, 100, 1);
			this.spnCantidad.CanFocus = true;
			this.spnCantidad.Name = "spnCantidad";
			this.spnCantidad.Adjustment.PageIncrement = 10;
			this.spnCantidad.ClimbRate = 1;
			this.spnCantidad.Numeric = true;
			this.vboxInfReg2.Add (this.spnCantidad);
			global::Gtk.Box.BoxChild w84 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg2 [this.spnCantidad]));
			w84.Position = 1;
			w84.Expand = false;
			w84.Fill = false;
			this.hbox6.Add (this.vboxInfReg2);
			global::Gtk.Box.BoxChild w85 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vboxInfReg2]));
			w85.Position = 0;
			w85.Expand = false;
			w85.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vboxInfReg3 = new global::Gtk.VBox ();
			this.vboxInfReg3.Name = "vboxInfReg3";
			this.vboxInfReg3.Spacing = 6;
			this.vboxInfReg3.BorderWidth = ((uint)(6));
			// Container child vboxInfReg3.Gtk.Box+BoxChild
			this.lblTotalReg2 = new global::Gtk.Label ();
			this.lblTotalReg2.Name = "lblTotalReg2";
			this.lblTotalReg2.Xalign = 0F;
			this.lblTotalReg2.LabelProp = global::Mono.Unix.Catalog.GetString ("Grupo al que pertenece");
			this.vboxInfReg3.Add (this.lblTotalReg2);
			global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg3 [this.lblTotalReg2]));
			w86.Position = 0;
			w86.Expand = false;
			w86.Fill = false;
			// Container child vboxInfReg3.Gtk.Box+BoxChild
			this.spnGrupo = new global::Gtk.SpinButton (0, 100, 1);
			this.spnGrupo.CanFocus = true;
			this.spnGrupo.Name = "spnGrupo";
			this.spnGrupo.Adjustment.PageIncrement = 10;
			this.spnGrupo.ClimbRate = 1;
			this.spnGrupo.Numeric = true;
			this.vboxInfReg3.Add (this.spnGrupo);
			global::Gtk.Box.BoxChild w87 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg3 [this.spnGrupo]));
			w87.Position = 1;
			w87.Expand = false;
			w87.Fill = false;
			this.hbox6.Add (this.vboxInfReg3);
			global::Gtk.Box.BoxChild w88 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vboxInfReg3]));
			w88.Position = 1;
			w88.Expand = false;
			w88.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vboxInfReg4 = new global::Gtk.VBox ();
			this.vboxInfReg4.Name = "vboxInfReg4";
			this.vboxInfReg4.Spacing = 6;
			this.vboxInfReg4.BorderWidth = ((uint)(6));
			// Container child vboxInfReg4.Gtk.Box+BoxChild
			this.lblTotalReg3 = new global::Gtk.Label ();
			this.lblTotalReg3.Name = "lblTotalReg3";
			this.lblTotalReg3.Xalign = 0F;
			this.lblTotalReg3.LabelProp = global::Mono.Unix.Catalog.GetString ("Incremento del precio");
			this.vboxInfReg4.Add (this.lblTotalReg3);
			global::Gtk.Box.BoxChild w89 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg4 [this.lblTotalReg3]));
			w89.Position = 0;
			w89.Expand = false;
			w89.Fill = false;
			// Container child vboxInfReg4.Gtk.Box+BoxChild
			this.spnIncremento = new global::Gtk.SpinButton (0, 100, 1);
			this.spnIncremento.CanFocus = true;
			this.spnIncremento.Name = "spnIncremento";
			this.spnIncremento.Adjustment.PageIncrement = 10;
			this.spnIncremento.ClimbRate = 1;
			this.spnIncremento.Digits = ((uint)(2));
			this.spnIncremento.Numeric = true;
			this.vboxInfReg4.Add (this.spnIncremento);
			global::Gtk.Box.BoxChild w90 = ((global::Gtk.Box.BoxChild)(this.vboxInfReg4 [this.spnIncremento]));
			w90.Position = 1;
			w90.Expand = false;
			w90.Fill = false;
			this.hbox6.Add (this.vboxInfReg4);
			global::Gtk.Box.BoxChild w91 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vboxInfReg4]));
			w91.Position = 2;
			w91.Expand = false;
			w91.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox ();
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.btnAceptarDes = new global::Gtk.Button ();
			this.btnAceptarDes.CanFocus = true;
			this.btnAceptarDes.Name = "btnAceptarDes";
			this.btnAceptarDes.UseStock = true;
			this.btnAceptarDes.UseUnderline = true;
			this.btnAceptarDes.BorderWidth = ((uint)(3));
			this.btnAceptarDes.Label = "gtk-ok";
			this.vbox9.Add (this.btnAceptarDes);
			global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.btnAceptarDes]));
			w92.Position = 0;
			w92.Expand = false;
			w92.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.btnBorrarDes = new global::Gtk.Button ();
			this.btnBorrarDes.CanFocus = true;
			this.btnBorrarDes.Name = "btnBorrarDes";
			this.btnBorrarDes.UseUnderline = true;
			this.btnBorrarDes.BorderWidth = ((uint)(3));
			// Container child btnBorrarDes.Gtk.Container+ContainerChild
			global::Gtk.Alignment w93 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w94 = new global::Gtk.HBox ();
			w94.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w95 = new global::Gtk.Image ();
			w95.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w94.Add (w95);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w97 = new global::Gtk.Label ();
			w97.LabelProp = global::Mono.Unix.Catalog.GetString ("Borrar");
			w97.UseUnderline = true;
			w94.Add (w97);
			w93.Add (w94);
			this.btnBorrarDes.Add (w93);
			this.vbox9.Add (this.btnBorrarDes);
			global::Gtk.Box.BoxChild w101 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.btnBorrarDes]));
			w101.Position = 1;
			w101.Expand = false;
			w101.Fill = false;
			this.hbox6.Add (this.vbox9);
			global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.vbox9]));
			w102.Position = 3;
			w102.Expand = false;
			w102.Fill = false;
			this.pneDesglose.Add (this.hbox6);
			global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.pneDesglose [this.hbox6]));
			w103.Position = 1;
			w103.Expand = false;
			w103.Fill = false;
			// Container child pneDesglose.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeDesgloses = new global::Gtk.TreeView ();
			this.treeDesgloses.CanFocus = true;
			this.treeDesgloses.Name = "treeDesgloses";
			this.GtkScrolledWindow1.Add (this.treeDesgloses);
			this.pneDesglose.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w105 = ((global::Gtk.Box.BoxChild)(this.pneDesglose [this.GtkScrolledWindow1]));
			w105.Position = 2;
			this.tabArticulos.Add (this.pneDesglose);
			global::Gtk.Notebook.NotebookChild w106 = ((global::Gtk.Notebook.NotebookChild)(this.tabArticulos [this.pneDesglose]));
			w106.Position = 1;
			// Notebook tab
			this.label9 = new global::Gtk.Label ();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Desglose de articulos");
			this.tabArticulos.SetTabLabel (this.pneDesglose, this.label9);
			this.label9.ShowAll ();
			// Container child tabArticulos.Gtk.Notebook+NotebookChild
			this.pneControlStock = new global::Gtk.VBox ();
			this.pneControlStock.Name = "pneControlStock";
			this.pneControlStock.Spacing = 6;
			this.pneControlStock.BorderWidth = ((uint)(9));
			// Container child pneControlStock.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vboxFamilias1 = new global::Gtk.VBox ();
			this.vboxFamilias1.Name = "vboxFamilias1";
			this.vboxFamilias1.Spacing = 6;
			// Container child vboxFamilias1.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label ();
			this.label14.Name = "label14";
			this.label14.Xalign = 0F;
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Almacen");
			this.vboxFamilias1.Add (this.label14);
			global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.vboxFamilias1 [this.label14]));
			w107.Position = 0;
			w107.Expand = false;
			w107.Fill = false;
			// Container child vboxFamilias1.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.cmbAlmacen = global::Gtk.ComboBox.NewText ();
			this.cmbAlmacen.WidthRequest = 200;
			this.cmbAlmacen.Name = "cmbAlmacen";
			this.hbox4.Add (this.cmbAlmacen);
			global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.cmbAlmacen]));
			w108.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnMasAlm = new global::Gtk.Button ();
			this.btnMasAlm.CanFocus = true;
			this.btnMasAlm.Name = "btnMasAlm";
			this.btnMasAlm.UseUnderline = true;
			// Container child btnMasAlm.Gtk.Container+ContainerChild
			global::Gtk.Alignment w109 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w110 = new global::Gtk.HBox ();
			w110.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w111 = new global::Gtk.Image ();
			w111.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w110.Add (w111);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w113 = new global::Gtk.Label ();
			w110.Add (w113);
			w109.Add (w110);
			this.btnMasAlm.Add (w109);
			this.hbox4.Add (this.btnMasAlm);
			global::Gtk.Box.BoxChild w117 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnMasAlm]));
			w117.Position = 1;
			w117.Expand = false;
			w117.Fill = false;
			this.vboxFamilias1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vboxFamilias1 [this.hbox4]));
			w118.Position = 1;
			w118.Expand = false;
			w118.Fill = false;
			this.hbox2.Add (this.vboxFamilias1);
			global::Gtk.Box.BoxChild w119 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vboxFamilias1]));
			w119.Position = 0;
			w119.Expand = false;
			w119.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox10 = new global::Gtk.VBox ();
			this.vbox10.Name = "vbox10";
			this.vbox10.Spacing = 6;
			this.vbox10.BorderWidth = ((uint)(3));
			// Container child vbox10.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Nivel abastecimento");
			this.vbox10.Add (this.label1);
			global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.label1]));
			w120.Position = 0;
			w120.Expand = false;
			w120.Fill = false;
			// Container child vbox10.Gtk.Box+BoxChild
			this.spnNivel = new global::Gtk.SpinButton (0, 100, 1);
			this.spnNivel.CanFocus = true;
			this.spnNivel.Name = "spnNivel";
			this.spnNivel.Adjustment.PageIncrement = 10;
			this.spnNivel.ClimbRate = 1;
			this.spnNivel.Numeric = true;
			this.vbox10.Add (this.spnNivel);
			global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.spnNivel]));
			w121.Position = 1;
			this.hbox2.Add (this.vbox10);
			global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox10]));
			w122.Position = 1;
			w122.Expand = false;
			w122.Fill = false;
			this.pneControlStock.Add (this.hbox2);
			global::Gtk.Box.BoxChild w123 = ((global::Gtk.Box.BoxChild)(this.pneControlStock [this.hbox2]));
			w123.Position = 0;
			w123.Expand = false;
			w123.Fill = false;
			// Container child pneControlStock.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox8 = new global::Gtk.VBox ();
			this.vbox8.Name = "vbox8";
			this.vbox8.Spacing = 6;
			this.vbox8.BorderWidth = ((uint)(3));
			// Container child vbox8.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label ();
			this.label10.Name = "label10";
			this.label10.Xalign = 0F;
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Stock maximo");
			this.vbox8.Add (this.label10);
			global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.label10]));
			w124.Position = 0;
			w124.Expand = false;
			w124.Fill = false;
			// Container child vbox8.Gtk.Box+BoxChild
			this.spnStockMax = new global::Gtk.SpinButton (0, 100, 1);
			this.spnStockMax.CanFocus = true;
			this.spnStockMax.Name = "spnStockMax";
			this.spnStockMax.Adjustment.PageIncrement = 10;
			this.spnStockMax.ClimbRate = 1;
			this.spnStockMax.Numeric = true;
			this.vbox8.Add (this.spnStockMax);
			global::Gtk.Box.BoxChild w125 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.spnStockMax]));
			w125.Position = 1;
			this.hbox3.Add (this.vbox8);
			global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox8]));
			w126.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			this.vbox6.BorderWidth = ((uint)(3));
			// Container child vbox6.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label ();
			this.label11.Name = "label11";
			this.label11.Xalign = 0F;
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString ("Stock minimo");
			this.vbox6.Add (this.label11);
			global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.label11]));
			w127.Position = 0;
			w127.Expand = false;
			w127.Fill = false;
			// Container child vbox6.Gtk.Box+BoxChild
			this.spnSockMini = new global::Gtk.SpinButton (0, 100, 1);
			this.spnSockMini.CanFocus = true;
			this.spnSockMini.Name = "spnSockMini";
			this.spnSockMini.Adjustment.PageIncrement = 10;
			this.spnSockMini.ClimbRate = 1;
			this.spnSockMini.Numeric = true;
			this.vbox6.Add (this.spnSockMini);
			global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.spnSockMini]));
			w128.Position = 1;
			this.hbox3.Add (this.vbox6);
			global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox6]));
			w129.Position = 1;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			this.vbox7.BorderWidth = ((uint)(3));
			// Container child vbox7.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label ();
			this.label12.Name = "label12";
			this.label12.Xalign = 0F;
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Stock actual");
			this.vbox7.Add (this.label12);
			global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.label12]));
			w130.Position = 0;
			w130.Expand = false;
			w130.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.spnStockActual = new global::Gtk.SpinButton (0, 100, 1);
			this.spnStockActual.CanFocus = true;
			this.spnStockActual.Name = "spnStockActual";
			this.spnStockActual.Adjustment.PageIncrement = 10;
			this.spnStockActual.ClimbRate = 1;
			this.spnStockActual.Numeric = true;
			this.vbox7.Add (this.spnStockActual);
			global::Gtk.Box.BoxChild w131 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.spnStockActual]));
			w131.Position = 1;
			this.hbox3.Add (this.vbox7);
			global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbox7]));
			w132.Position = 2;
			// Container child hbox3.Gtk.Box+BoxChild
			this.vbtControl = new global::Gtk.VButtonBox ();
			this.vbtControl.Name = "vbtControl";
			// Container child vbtControl.Gtk.ButtonBox+ButtonBoxChild
			this.btnAceptarAlm = new global::Gtk.Button ();
			this.btnAceptarAlm.CanFocus = true;
			this.btnAceptarAlm.Name = "btnAceptarAlm";
			this.btnAceptarAlm.UseStock = true;
			this.btnAceptarAlm.UseUnderline = true;
			this.btnAceptarAlm.BorderWidth = ((uint)(6));
			this.btnAceptarAlm.Label = "gtk-ok";
			this.vbtControl.Add (this.btnAceptarAlm);
			global::Gtk.ButtonBox.ButtonBoxChild w133 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtControl [this.btnAceptarAlm]));
			w133.Expand = false;
			w133.Fill = false;
			// Container child vbtControl.Gtk.ButtonBox+ButtonBoxChild
			this.btnBorrarAlm = new global::Gtk.Button ();
			this.btnBorrarAlm.CanFocus = true;
			this.btnBorrarAlm.Name = "btnBorrarAlm";
			this.btnBorrarAlm.UseUnderline = true;
			this.btnBorrarAlm.BorderWidth = ((uint)(6));
			// Container child btnBorrarAlm.Gtk.Container+ContainerChild
			global::Gtk.Alignment w134 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w135 = new global::Gtk.HBox ();
			w135.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w136 = new global::Gtk.Image ();
			w136.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w135.Add (w136);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w138 = new global::Gtk.Label ();
			w138.LabelProp = global::Mono.Unix.Catalog.GetString ("Borrar");
			w138.UseUnderline = true;
			w135.Add (w138);
			w134.Add (w135);
			this.btnBorrarAlm.Add (w134);
			this.vbtControl.Add (this.btnBorrarAlm);
			global::Gtk.ButtonBox.ButtonBoxChild w142 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.vbtControl [this.btnBorrarAlm]));
			w142.Position = 1;
			w142.Expand = false;
			w142.Fill = false;
			this.hbox3.Add (this.vbtControl);
			global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.vbtControl]));
			w143.Position = 3;
			w143.Expand = false;
			w143.Fill = false;
			this.pneControlStock.Add (this.hbox3);
			global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.pneControlStock [this.hbox3]));
			w144.Position = 1;
			w144.Expand = false;
			w144.Fill = false;
			// Container child pneControlStock.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeAlmacenes = new global::Gtk.TreeView ();
			this.treeAlmacenes.CanFocus = true;
			this.treeAlmacenes.Name = "treeAlmacenes";
			this.GtkScrolledWindow.Add (this.treeAlmacenes);
			this.pneControlStock.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.pneControlStock [this.GtkScrolledWindow]));
			w146.Position = 2;
			this.tabArticulos.Add (this.pneControlStock);
			global::Gtk.Notebook.NotebookChild w147 = ((global::Gtk.Notebook.NotebookChild)(this.tabArticulos [this.pneControlStock]));
			w147.Position = 2;
			// Notebook tab
			this.label13 = new global::Gtk.Label ();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Control Stock");
			this.tabArticulos.SetTabLabel (this.pneControlStock, this.label13);
			this.label13.ShowAll ();
			this.vboxPrincipal.Add (this.tabArticulos);
			global::Gtk.Box.BoxChild w148 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.tabArticulos]));
			w148.Position = 1;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.grpModos = new global::Gtk.HButtonBox ();
			this.grpModos.Name = "grpModos";
			this.grpModos.Spacing = 14;
			this.grpModos.BorderWidth = ((uint)(6));
			this.grpModos.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnBuscar = new global::Gtk.Button ();
			this.btnBuscar.CanFocus = true;
			this.btnBuscar.Name = "btnBuscar";
			this.btnBuscar.UseUnderline = true;
			// Container child btnBuscar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w149 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w150 = new global::Gtk.HBox ();
			w150.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w151 = new global::Gtk.Image ();
			w151.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-find", global::Gtk.IconSize.Menu);
			w150.Add (w151);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w153 = new global::Gtk.Label ();
			w153.LabelProp = global::Mono.Unix.Catalog.GetString ("Buscar");
			w153.UseUnderline = true;
			w150.Add (w153);
			w149.Add (w150);
			this.btnBuscar.Add (w149);
			this.grpModos.Add (this.btnBuscar);
			global::Gtk.ButtonBox.ButtonBoxChild w157 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnBuscar]));
			w157.Expand = false;
			w157.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnAceptar = new global::Gtk.Button ();
			this.btnAceptar.CanFocus = true;
			this.btnAceptar.Name = "btnAceptar";
			this.btnAceptar.UseStock = true;
			this.btnAceptar.UseUnderline = true;
			this.btnAceptar.Label = "gtk-apply";
			this.grpModos.Add (this.btnAceptar);
			global::Gtk.ButtonBox.ButtonBoxChild w158 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnAceptar]));
			w158.Position = 1;
			w158.Expand = false;
			w158.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditar = new global::Gtk.Button ();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			// Container child btnEditar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w159 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w160 = new global::Gtk.HBox ();
			w160.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w161 = new global::Gtk.Image ();
			w161.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_effects", global::Gtk.IconSize.Menu);
			w160.Add (w161);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w163 = new global::Gtk.Label ();
			w163.LabelProp = global::Mono.Unix.Catalog.GetString ("Editar");
			w163.UseUnderline = true;
			w160.Add (w163);
			w159.Add (w160);
			this.btnEditar.Add (w159);
			this.grpModos.Add (this.btnEditar);
			global::Gtk.ButtonBox.ButtonBoxChild w167 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnEditar]));
			w167.Position = 2;
			w167.Expand = false;
			w167.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnAñadir = new global::Gtk.Button ();
			this.btnAñadir.CanFocus = true;
			this.btnAñadir.Name = "btnAñadir";
			this.btnAñadir.UseUnderline = true;
			// Container child btnAñadir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w168 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w169 = new global::Gtk.HBox ();
			w169.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w170 = new global::Gtk.Image ();
			w170.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w169.Add (w170);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w172 = new global::Gtk.Label ();
			w172.LabelProp = global::Mono.Unix.Catalog.GetString ("Añadir");
			w172.UseUnderline = true;
			w169.Add (w172);
			w168.Add (w169);
			this.btnAñadir.Add (w168);
			this.grpModos.Add (this.btnAñadir);
			global::Gtk.ButtonBox.ButtonBoxChild w176 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnAñadir]));
			w176.Position = 3;
			w176.Expand = false;
			w176.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnMasArt = new global::Gtk.Button ();
			this.btnMasArt.CanFocus = true;
			this.btnMasArt.Name = "btnMasArt";
			this.btnMasArt.UseUnderline = true;
			// Container child btnMasArt.Gtk.Container+ContainerChild
			global::Gtk.Alignment w177 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w178 = new global::Gtk.HBox ();
			w178.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w179 = new global::Gtk.Image ();
			w179.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/ARITH03C.ICO"));
			w178.Add (w179);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w181 = new global::Gtk.Label ();
			w181.LabelProp = global::Mono.Unix.Catalog.GetString (" Otro");
			w181.UseUnderline = true;
			w178.Add (w181);
			w177.Add (w178);
			this.btnMasArt.Add (w177);
			this.grpModos.Add (this.btnMasArt);
			global::Gtk.ButtonBox.ButtonBoxChild w185 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnMasArt]));
			w185.Position = 4;
			w185.Expand = false;
			w185.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnBorrar = new global::Gtk.Button ();
			this.btnBorrar.CanFocus = true;
			this.btnBorrar.Name = "btnBorrar";
			this.btnBorrar.UseUnderline = true;
			// Container child btnBorrar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w186 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w187 = new global::Gtk.HBox ();
			w187.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w188 = new global::Gtk.Image ();
			w188.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w187.Add (w188);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w190 = new global::Gtk.Label ();
			w190.LabelProp = global::Mono.Unix.Catalog.GetString ("Borrar");
			w190.UseUnderline = true;
			w187.Add (w190);
			w186.Add (w187);
			this.btnBorrar.Add (w186);
			this.grpModos.Add (this.btnBorrar);
			global::Gtk.ButtonBox.ButtonBoxChild w194 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnBorrar]));
			w194.Position = 5;
			w194.Expand = false;
			w194.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w195 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w196 = new global::Gtk.HBox ();
			w196.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w197 = new global::Gtk.Image ();
			w197.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/EXIT00C.ICO"));
			w196.Add (w197);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w199 = new global::Gtk.Label ();
			w199.LabelProp = global::Mono.Unix.Catalog.GetString ("Salir");
			w199.UseUnderline = true;
			w196.Add (w199);
			w195.Add (w196);
			this.btnSalir.Add (w195);
			this.grpModos.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w203 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnSalir]));
			w203.Position = 6;
			w203.Expand = false;
			w203.Fill = false;
			this.vboxPrincipal.Add (this.grpModos);
			global::Gtk.Box.BoxChild w204 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.grpModos]));
			w204.Position = 2;
			w204.Expand = false;
			w204.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.lblInformacion = new global::Gtk.Label ();
			this.lblInformacion.Name = "lblInformacion";
			this.lblInformacion.Xalign = 0F;
			this.lblInformacion.LabelProp = global::Mono.Unix.Catalog.GetString ("Esta usted en modo no editable");
			this.vboxPrincipal.Add (this.lblInformacion);
			global::Gtk.Box.BoxChild w205 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.lblInformacion]));
			w205.Position = 3;
			w205.Expand = false;
			w205.Fill = false;
			this.Add (this.vboxPrincipal);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 899;
			this.DefaultHeight = 714;
			this.btnAceptar.Hide ();
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnPrimero.Clicked += new global::System.EventHandler (this.OnBtnPrimeroClicked);
			this.btnAtras.Clicked += new global::System.EventHandler (this.OnBtnAtrasClicked);
			this.btnSiguiente.Clicked += new global::System.EventHandler (this.OnBtnSiguienteClicked);
			this.btnUltimo.Clicked += new global::System.EventHandler (this.OnBtnUltimoClicked);
			this.txtNombre.Changed += new global::System.EventHandler (this.OnTxtNombreChanged);
			this.txtNombre.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnTxtNombreFocusOutEvent);
			this.txtID.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnTxtIDFocusOutEvent);
			this.txtID.Changed += new global::System.EventHandler (this.OnTxtIDChanged);
			this.cmbFamilias.Changed += new global::System.EventHandler (this.OnCmbFamiliasChanged);
			this.btnAñadirFam.Clicked += new global::System.EventHandler (this.OnBtnAñadirFamClicked);
			this.chkPorKilos.Clicked += new global::System.EventHandler (this.OnChkPorKilosClicked);
			this.chkNoEnVenta.Clicked += new global::System.EventHandler (this.OnChkNoEnVentaClicked);
			this.btnGrabar.Clicked += new global::System.EventHandler (this.OnBtnGrabarClicked);
			this.btnBuscarAgre.Clicked += new global::System.EventHandler (this.OnBtnBuscarAgreClicked);
			this.btnCrearAgre.Clicked += new global::System.EventHandler (this.OnBtnCrearAgreClicked);
			this.spnCantidad.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnSpnCantidadFocusInEvent);
			this.spnCantidad.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSpnNivelFocusOutEvent);
			this.spnGrupo.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnSpnGrupoFocusInEvent);
			this.spnGrupo.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSpnNivelFocusOutEvent);
			this.spnIncremento.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnSpnIncrementoFocusInEvent);
			this.spnIncremento.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSpnNivelFocusOutEvent);
			this.btnAceptarDes.Clicked += new global::System.EventHandler (this.OnBtnAceptarDesClicked);
			this.btnBorrarDes.Clicked += new global::System.EventHandler (this.OnBtnBorrarDesClicked);
			this.treeDesgloses.CursorChanged += new global::System.EventHandler (this.OnTreeDesglosesCursorChanged);
			this.cmbAlmacen.Changed += new global::System.EventHandler (this.OnCmbFamiliasChanged);
			this.btnMasAlm.Clicked += new global::System.EventHandler (this.OnBtnMasAlmClicked);
			this.spnNivel.FocusInEvent += new global::Gtk.FocusInEventHandler (this.OnSpnNivelFocusInEvent);
			this.spnNivel.FocusOutEvent += new global::Gtk.FocusOutEventHandler (this.OnSpnNivelFocusOutEvent);
			this.btnAceptarAlm.Clicked += new global::System.EventHandler (this.OnBtnAceptarAlmClicked);
			this.btnBorrarAlm.Clicked += new global::System.EventHandler (this.OnBtnBorrarAlmClicked);
			this.treeAlmacenes.CursorChanged += new global::System.EventHandler (this.OnTreeAlmacenesCursorChanged);
			this.btnBuscar.Clicked += new global::System.EventHandler (this.OnBtnBuscarClicked);
			this.btnAceptar.Clicked += new global::System.EventHandler (this.OnBtnAceptarClicked);
			this.btnEditar.Clicked += new global::System.EventHandler (this.OnBtnEditarClicked);
			this.btnAñadir.Clicked += new global::System.EventHandler (this.OnBtnAñadirArtClicked);
			this.btnMasArt.Clicked += new global::System.EventHandler (this.OnBtnAñadirArtClicked);
			this.btnBorrar.Clicked += new global::System.EventHandler (this.OnBtnBorrarClicked);
			this.btnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
