
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GesTpv
{
	public partial class VenListados
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TextView txtConsulta;
		private global::Gtk.HBox hbox3;
		private global::Gtk.Label lblInformacion;
		private global::Gtk.Button btnEjConsulta;
		private global::Gtk.Button button339;
		private global::Valle.GtkUtilidades.ArbolDeVista arboldevista1;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnSalir;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GesTpv.VenListados
			this.Name = "Valle.GesTpv.VenListados";
			this.Title = global::Mono.Unix.Catalog.GetString ("Listado de tablas");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/exec.gif"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			// Container child Valle.GesTpv.VenListados.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(6));
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.HeightRequest = 100;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			this.GtkScrolledWindow.BorderWidth = ((uint)(6));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.txtConsulta = new global::Gtk.TextView ();
			this.txtConsulta.CanFocus = true;
			this.txtConsulta.Name = "txtConsulta";
			this.GtkScrolledWindow.Add (this.txtConsulta);
			this.vbox1.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
			w2.Position = 0;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			this.hbox3.BorderWidth = ((uint)(3));
			// Container child hbox3.Gtk.Box+BoxChild
			this.lblInformacion = new global::Gtk.Label ();
			this.lblInformacion.Name = "lblInformacion";
			this.lblInformacion.Xalign = 0F;
			this.hbox3.Add (this.lblInformacion);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.lblInformacion]));
			w3.Position = 0;
			// Container child hbox3.Gtk.Box+BoxChild
			this.btnEjConsulta = new global::Gtk.Button ();
			this.btnEjConsulta.CanFocus = true;
			this.btnEjConsulta.Name = "btnEjConsulta";
			this.btnEjConsulta.UseUnderline = true;
			this.btnEjConsulta.Label = global::Mono.Unix.Catalog.GetString ("Ejecutar consulta");
			this.hbox3.Add (this.btnEjConsulta);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.btnEjConsulta]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.button339 = new global::Gtk.Button ();
			this.button339.CanFocus = true;
			this.button339.Name = "button339";
			this.button339.UseStock = true;
			this.button339.UseUnderline = true;
			this.button339.Label = "gtk-stop";
			this.hbox3.Add (this.button339);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.button339]));
			w5.PackType = ((global::Gtk.PackType)(1));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox1.Add (this.hbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox3]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.arboldevista1 = new global::Valle.GtkUtilidades.ArbolDeVista ();
			this.arboldevista1.HeightRequest = 400;
			this.arboldevista1.Events = ((global::Gdk.EventMask)(256));
			this.arboldevista1.Name = "arboldevista1";
			this.vbox1.Add (this.arboldevista1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.arboldevista1]));
			w7.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.BorderWidth = ((uint)(6));
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			this.btnSalir.Label = global::Mono.Unix.Catalog.GetString ("Salir");
			this.hbuttonbox1.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w8 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnSalir]));
			w8.Expand = false;
			w8.Fill = false;
			this.vbox1.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox1]));
			w9.Position = 3;
			w9.Expand = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 718;
			this.DefaultHeight = 644;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnEjConsulta.Clicked += new global::System.EventHandler (this.OnBtnEjConsultaClicked);
			this.button339.Clicked += new global::System.EventHandler (this.OnButton339Clicked);
			this.btnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
