
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GesTpv
{
	public partial class VenPrecios
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label1;
		private global::Valle.GtkUtilidades.ArbolDeVista arbolSeciones;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Notebook notebook1;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label3;
		private global::Gtk.SpinButton txtEuros;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnRevertirEuros;
		private global::Gtk.Button btnActualizarEuro;
		private global::Gtk.Label label2;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label label24;
		private global::Gtk.SpinButton txtPorcentaje;
		private global::Gtk.HButtonBox hbuttonbox2;
		private global::Gtk.Button btnRevertirPorc;
		private global::Gtk.Button btnActualizarPorc;
		private global::Gtk.Label label4;
		private global::Valle.GtkUtilidades.ArbolDeVista arbolArticulos;
		private global::Gtk.HButtonBox hbuttonbox3;
		private global::Gtk.Button btnAplicarCmb;
		private global::Gtk.Label lblInfomacion;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GesTpv.VenPrecios
			this.Name = "Valle.GesTpv.VenPrecios";
			this.Title = global::Mono.Unix.Catalog.GetString ("Cambio de precios");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/exec.gif"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.BorderWidth = ((uint)(6));
			// Container child Valle.GesTpv.VenPrecios.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			this.hbox1.BorderWidth = ((uint)(6));
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Mostrar familias");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label1]));
			w1.Position = 0;
			// Container child vbox2.Gtk.Box+BoxChild
			this.arbolSeciones = new global::Valle.GtkUtilidades.ArbolDeVista ();
			this.arbolSeciones.WidthRequest = 310;
			this.arbolSeciones.HeightRequest = 210;
			this.arbolSeciones.Events = ((global::Gdk.EventMask)(256));
			this.arbolSeciones.Name = "arbolSeciones";
			this.vbox2.Add (this.arbolSeciones);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.arbolSeciones]));
			w2.Position = 1;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			this.notebook1.BorderWidth = ((uint)(12));
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			this.vbox4.BorderWidth = ((uint)(45));
			// Container child vbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Euros a incrementar");
			this.vbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label3]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txtEuros = new global::Gtk.SpinButton (0, 100, 1);
			this.txtEuros.CanFocus = true;
			this.txtEuros.Name = "txtEuros";
			this.txtEuros.Adjustment.PageIncrement = 10;
			this.txtEuros.ClimbRate = 1;
			this.txtEuros.Digits = ((uint)(2));
			this.txtEuros.Numeric = true;
			this.vbox4.Add (this.txtEuros);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.txtEuros]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnRevertirEuros = new global::Gtk.Button ();
			this.btnRevertirEuros.Sensitive = false;
			this.btnRevertirEuros.CanFocus = true;
			this.btnRevertirEuros.Name = "btnRevertirEuros";
			this.btnRevertirEuros.UseStock = true;
			this.btnRevertirEuros.UseUnderline = true;
			this.btnRevertirEuros.Label = "gtk-undo";
			this.hbuttonbox1.Add (this.btnRevertirEuros);
			global::Gtk.ButtonBox.ButtonBoxChild w6 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnRevertirEuros]));
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnActualizarEuro = new global::Gtk.Button ();
			this.btnActualizarEuro.CanFocus = true;
			this.btnActualizarEuro.Name = "btnActualizarEuro";
			this.btnActualizarEuro.UseStock = true;
			this.btnActualizarEuro.UseUnderline = true;
			this.btnActualizarEuro.Label = "gtk-execute";
			this.hbuttonbox1.Add (this.btnActualizarEuro);
			global::Gtk.ButtonBox.ButtonBoxChild w7 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnActualizarEuro]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox4.Add (this.hbuttonbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbuttonbox1]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			this.notebook1.Add (this.vbox4);
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Incremento en euros");
			this.notebook1.SetTabLabel (this.vbox4, this.label2);
			this.label2.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			this.vbox5.BorderWidth = ((uint)(48));
			// Container child vbox5.Gtk.Box+BoxChild
			this.label24 = new global::Gtk.Label ();
			this.label24.Name = "label24";
			this.label24.Xalign = 0F;
			this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Porcentaje");
			this.vbox5.Add (this.label24);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label24]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.txtPorcentaje = new global::Gtk.SpinButton (0, 100, 1);
			this.txtPorcentaje.CanFocus = true;
			this.txtPorcentaje.Name = "txtPorcentaje";
			this.txtPorcentaje.Adjustment.PageIncrement = 10;
			this.txtPorcentaje.ClimbRate = 1;
			this.txtPorcentaje.Numeric = true;
			this.vbox5.Add (this.txtPorcentaje);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.txtPorcentaje]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnRevertirPorc = new global::Gtk.Button ();
			this.btnRevertirPorc.Sensitive = false;
			this.btnRevertirPorc.CanFocus = true;
			this.btnRevertirPorc.Name = "btnRevertirPorc";
			this.btnRevertirPorc.UseStock = true;
			this.btnRevertirPorc.UseUnderline = true;
			this.btnRevertirPorc.Label = "gtk-undo";
			this.hbuttonbox2.Add (this.btnRevertirPorc);
			global::Gtk.ButtonBox.ButtonBoxChild w12 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnRevertirPorc]));
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnActualizarPorc = new global::Gtk.Button ();
			this.btnActualizarPorc.CanFocus = true;
			this.btnActualizarPorc.Name = "btnActualizarPorc";
			this.btnActualizarPorc.UseStock = true;
			this.btnActualizarPorc.UseUnderline = true;
			this.btnActualizarPorc.Label = "gtk-execute";
			this.hbuttonbox2.Add (this.btnActualizarPorc);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2 [this.btnActualizarPorc]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox5.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.hbuttonbox2]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			this.notebook1.Add (this.vbox5);
			global::Gtk.Notebook.NotebookChild w15 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.vbox5]));
			w15.Position = 1;
			// Notebook tab
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Porcentaje");
			this.notebook1.SetTabLabel (this.vbox5, this.label4);
			this.label4.ShowAll ();
			this.vbox3.Add (this.notebook1);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.notebook1]));
			w16.Position = 0;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w17.Position = 1;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbox1]));
			w18.Position = 0;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.arbolArticulos = new global::Valle.GtkUtilidades.ArbolDeVista ();
			this.arbolArticulos.Events = ((global::Gdk.EventMask)(256));
			this.arbolArticulos.Name = "arbolArticulos";
			this.vbox1.Add (this.arbolArticulos);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.arbolArticulos]));
			w19.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox3 = new global::Gtk.HButtonBox ();
			this.hbuttonbox3.Name = "hbuttonbox3";
			this.hbuttonbox3.BorderWidth = ((uint)(3));
			this.hbuttonbox3.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox3.Gtk.ButtonBox+ButtonBoxChild
			this.btnAplicarCmb = new global::Gtk.Button ();
			this.btnAplicarCmb.CanFocus = true;
			this.btnAplicarCmb.Name = "btnAplicarCmb";
			this.btnAplicarCmb.UseStock = true;
			this.btnAplicarCmb.UseUnderline = true;
			this.btnAplicarCmb.Label = "gtk-apply";
			this.hbuttonbox3.Add (this.btnAplicarCmb);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox3 [this.btnAplicarCmb]));
			w20.Expand = false;
			w20.Fill = false;
			this.vbox1.Add (this.hbuttonbox3);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hbuttonbox3]));
			w21.Position = 2;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblInfomacion = new global::Gtk.Label ();
			this.lblInfomacion.Name = "lblInfomacion";
			this.lblInfomacion.Xalign = 0F;
			this.lblInfomacion.LabelProp = global::Mono.Unix.Catalog.GetString ("label2");
			this.vbox1.Add (this.lblInfomacion);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblInfomacion]));
			w22.Position = 3;
			w22.Expand = false;
			w22.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 727;
			this.DefaultHeight = 571;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.arbolSeciones.FilaActivada += new global::Gtk.RowActivatedHandler (this.OnArbolSecionesFilaActivada);
			this.btnRevertirEuros.Clicked += new global::System.EventHandler (this.OnBtnRevertirEurosClicked);
			this.btnActualizarEuro.Clicked += new global::System.EventHandler (this.OnBtnActualizarEuroClicked);
			this.btnRevertirPorc.Clicked += new global::System.EventHandler (this.OnBtnRevertirPorcClicked);
			this.btnActualizarPorc.Clicked += new global::System.EventHandler (this.OnBtnActualizarPorcClicked);
			this.btnAplicarCmb.Clicked += new global::System.EventHandler (this.OnBtnAplicarCmbClicked);
		}
	}
}
