
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GesTpv
{
	public partial class VenCamareros
	{
		private global::Gtk.VBox vboxPrincipal;
		private global::Gtk.HBox hbox1;
		private global::Gtk.VBox vbox2;
		private global::Gtk.Label label4;
		private global::Gtk.Entry txtNombre;
		private global::Gtk.VBox vbox3;
		private global::Gtk.Label label2;
		private global::Gtk.Entry txtApellidos;
		private global::Gtk.HBox hbox2;
		private global::Gtk.VBox vbox4;
		private global::Gtk.Label label5;
		private global::Gtk.Entry txtDireccion;
		private global::Gtk.VBox vbox5;
		private global::Gtk.Label label3;
		private global::Gtk.SpinButton txtTelfono;
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		private global::Gtk.TreeView lstTabla;
		private global::Gtk.HButtonBox grpModos;
		private global::Gtk.Button btnEditar;
		private global::Gtk.Button btnAñadir;
		private global::Gtk.Button btnBorrar;
		private global::Gtk.HButtonBox grpModos1;
		private global::Gtk.Button btnAceptar;
		private global::Gtk.Button btnSalir;
		private global::Gtk.Label lblInformacion;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GesTpv.VenCamareros
			this.WidthRequest = 500;
			this.Name = "Valle.GesTpv.VenCamareros";
			this.Title = global::Mono.Unix.Catalog.GetString ("Gestion de camareros");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/exec.gif"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Valle.GesTpv.VenCamareros.Gtk.Container+ContainerChild
			this.vboxPrincipal = new global::Gtk.VBox ();
			this.vboxPrincipal.Name = "vboxPrincipal";
			this.vboxPrincipal.Spacing = 6;
			this.vboxPrincipal.BorderWidth = ((uint)(9));
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.Xalign = 0F;
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre");
			this.vbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label4]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry ();
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '●';
			this.vbox2.Add (this.txtNombre);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.txtNombre]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			this.hbox1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.Xalign = 0F;
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Apellidos");
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.txtApellidos = new global::Gtk.Entry ();
			this.txtApellidos.CanFocus = true;
			this.txtApellidos.Name = "txtApellidos";
			this.txtApellidos.IsEditable = true;
			this.txtApellidos.InvisibleChar = '●';
			this.vbox3.Add (this.txtApellidos);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.txtApellidos]));
			w5.Position = 1;
			this.hbox1.Add (this.vbox3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox3]));
			w6.Position = 1;
			this.vboxPrincipal.Add (this.hbox1);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.hbox1]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.Xalign = 0F;
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Direccion");
			this.vbox4.Add (this.label5);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.label5]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.txtDireccion = new global::Gtk.Entry ();
			this.txtDireccion.CanFocus = true;
			this.txtDireccion.Name = "txtDireccion";
			this.txtDireccion.IsEditable = true;
			this.txtDireccion.InvisibleChar = '●';
			this.vbox4.Add (this.txtDireccion);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.txtDireccion]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			this.hbox2.Add (this.vbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox4]));
			w10.Position = 0;
			// Container child hbox2.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.Xalign = 0F;
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Telefono");
			this.vbox5.Add (this.label3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.label3]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.txtTelfono = new global::Gtk.SpinButton (0, 999999999, 1);
			this.txtTelfono.WidthRequest = 0;
			this.txtTelfono.HeightRequest = 0;
			this.txtTelfono.CanFocus = true;
			this.txtTelfono.Name = "txtTelfono";
			this.txtTelfono.Adjustment.PageIncrement = 10;
			this.txtTelfono.ClimbRate = 1;
			this.txtTelfono.Numeric = true;
			this.vbox5.Add (this.txtTelfono);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.txtTelfono]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			this.hbox2.Add (this.vbox5);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.vbox5]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			this.vboxPrincipal.Add (this.hbox2);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.hbox2]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.WidthRequest = 440;
			this.GtkScrolledWindow.HeightRequest = 300;
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.lstTabla = new global::Gtk.TreeView ();
			this.lstTabla.CanFocus = true;
			this.lstTabla.Name = "lstTabla";
			this.GtkScrolledWindow.Add (this.lstTabla);
			this.vboxPrincipal.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.GtkScrolledWindow]));
			w16.Position = 2;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.grpModos = new global::Gtk.HButtonBox ();
			this.grpModos.Name = "grpModos";
			this.grpModos.Spacing = 14;
			this.grpModos.BorderWidth = ((uint)(6));
			this.grpModos.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditar = new global::Gtk.Button ();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			// Container child btnEditar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w17 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w18 = new global::Gtk.HBox ();
			w18.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w19 = new global::Gtk.Image ();
			w19.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_effects", global::Gtk.IconSize.Menu);
			w18.Add (w19);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w21 = new global::Gtk.Label ();
			w21.LabelProp = global::Mono.Unix.Catalog.GetString ("Editar");
			w21.UseUnderline = true;
			w18.Add (w21);
			w17.Add (w18);
			this.btnEditar.Add (w17);
			this.grpModos.Add (this.btnEditar);
			global::Gtk.ButtonBox.ButtonBoxChild w25 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnEditar]));
			w25.Expand = false;
			w25.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnAñadir = new global::Gtk.Button ();
			this.btnAñadir.CanFocus = true;
			this.btnAñadir.Name = "btnAñadir";
			this.btnAñadir.UseUnderline = true;
			// Container child btnAñadir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w26 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w27 = new global::Gtk.HBox ();
			w27.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w28 = new global::Gtk.Image ();
			w28.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w27.Add (w28);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w30 = new global::Gtk.Label ();
			w30.LabelProp = global::Mono.Unix.Catalog.GetString ("Añadir");
			w30.UseUnderline = true;
			w27.Add (w30);
			w26.Add (w27);
			this.btnAñadir.Add (w26);
			this.grpModos.Add (this.btnAñadir);
			global::Gtk.ButtonBox.ButtonBoxChild w34 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnAñadir]));
			w34.Position = 1;
			w34.Expand = false;
			w34.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnBorrar = new global::Gtk.Button ();
			this.btnBorrar.CanFocus = true;
			this.btnBorrar.Name = "btnBorrar";
			this.btnBorrar.UseUnderline = true;
			// Container child btnBorrar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w35 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w36 = new global::Gtk.HBox ();
			w36.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w37 = new global::Gtk.Image ();
			w37.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-delete", global::Gtk.IconSize.Menu);
			w36.Add (w37);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w39 = new global::Gtk.Label ();
			w39.LabelProp = global::Mono.Unix.Catalog.GetString ("Borrar art");
			w39.UseUnderline = true;
			w36.Add (w39);
			w35.Add (w36);
			this.btnBorrar.Add (w35);
			this.grpModos.Add (this.btnBorrar);
			global::Gtk.ButtonBox.ButtonBoxChild w43 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnBorrar]));
			w43.Position = 2;
			w43.Expand = false;
			w43.Fill = false;
			this.vboxPrincipal.Add (this.grpModos);
			global::Gtk.Box.BoxChild w44 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.grpModos]));
			w44.Position = 3;
			w44.Expand = false;
			w44.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.grpModos1 = new global::Gtk.HButtonBox ();
			this.grpModos1.Name = "grpModos1";
			this.grpModos1.Spacing = 14;
			this.grpModos1.BorderWidth = ((uint)(6));
			this.grpModos1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child grpModos1.Gtk.ButtonBox+ButtonBoxChild
			this.btnAceptar = new global::Gtk.Button ();
			this.btnAceptar.CanFocus = true;
			this.btnAceptar.Name = "btnAceptar";
			this.btnAceptar.UseStock = true;
			this.btnAceptar.UseUnderline = true;
			this.btnAceptar.Label = "gtk-ok";
			this.grpModos1.Add (this.btnAceptar);
			global::Gtk.ButtonBox.ButtonBoxChild w45 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos1 [this.btnAceptar]));
			w45.Expand = false;
			w45.Fill = false;
			// Container child grpModos1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w46 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w47 = new global::Gtk.HBox ();
			w47.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w48 = new global::Gtk.Image ();
			w48.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/EXIT00C.ICO"));
			w47.Add (w48);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w50 = new global::Gtk.Label ();
			w50.LabelProp = global::Mono.Unix.Catalog.GetString ("Salir");
			w50.UseUnderline = true;
			w47.Add (w50);
			w46.Add (w47);
			this.btnSalir.Add (w46);
			this.grpModos1.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w54 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos1 [this.btnSalir]));
			w54.Position = 1;
			w54.Expand = false;
			w54.Fill = false;
			this.vboxPrincipal.Add (this.grpModos1);
			global::Gtk.Box.BoxChild w55 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.grpModos1]));
			w55.Position = 4;
			w55.Expand = false;
			w55.Fill = false;
			// Container child vboxPrincipal.Gtk.Box+BoxChild
			this.lblInformacion = new global::Gtk.Label ();
			this.lblInformacion.Name = "lblInformacion";
			this.lblInformacion.Xalign = 0F;
			this.lblInformacion.LabelProp = global::Mono.Unix.Catalog.GetString ("Modo no editable activado");
			this.vboxPrincipal.Add (this.lblInformacion);
			global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vboxPrincipal [this.lblInformacion]));
			w56.Position = 5;
			w56.Expand = false;
			w56.Fill = false;
			this.Add (this.vboxPrincipal);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 572;
			this.DefaultHeight = 592;
			this.btnAceptar.Hide ();
			this.Show ();
			this.lstTabla.CursorChanged += new global::System.EventHandler (this.OnLstTablaCursorChanged);
			this.btnEditar.Clicked += new global::System.EventHandler (this.OnBtnEditarClicked);
			this.btnAñadir.Clicked += new global::System.EventHandler (this.OnBtnAñadirClicked);
			this.btnBorrar.Clicked += new global::System.EventHandler (this.OnBtnBorrarClicked);
			this.btnAceptar.Clicked += new global::System.EventHandler (this.OnBtnAceptarClicked);
			this.btnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
