
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GesTpv
{
	public partial class VenPlanig
	{
		private global::Gtk.VBox vbox1;
		private global::Gtk.Table table1;
		private global::Gtk.Button btnAplicarEsc;
		private global::Gtk.HBox hbox1;
		private global::Gtk.Label label3;
		private global::Gtk.Entry txtNombre;
		private global::Gtk.HBox hbox2;
		private global::Gtk.Label label4;
		private global::Gtk.Entry txtRef;
		private global::Gtk.HBox hbox4;
		private global::Gtk.Label label2;
		private global::Gtk.ComboBox cmbZonas;
		private global::Gtk.Button btnAñadirZona;
		private global::Gtk.HButtonBox hbuttonbox1;
		private global::Gtk.Button btnLimpiar;
		private global::Gtk.Button btnRotarDibujo;
		private global::Gtk.Label lblEscalado;
		private global::Gtk.SpinButton spinEscalado;
		private global::Gtk.EventBox AreaDeDibujo;
		private global::Gtk.Image cImgPlano;
		private global::Gtk.HButtonBox grpModos;
		private global::Gtk.Button btnTexto;
		private global::Gtk.Button btnAceptar;
		private global::Gtk.Button btnEditar;
		private global::Gtk.Button btnSalir;
		private global::Gtk.Label lblInformacion;
        
		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GesTpv.VenPlanig
			this.Name = "Valle.GesTpv.VenPlanig";
			this.Title = global::Mono.Unix.Catalog.GetString ("Generador de planos");
			this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/exec.gif"));
			this.WindowPosition = ((global::Gtk.WindowPosition)(3));
			this.Modal = true;
			this.Resizable = false;
			this.AllowGrow = false;
			// Container child Valle.GesTpv.VenPlanig.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.CanDefault = true;
			this.vbox1.CanFocus = true;
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(9));
			// Container child vbox1.Gtk.Box+BoxChild
			this.table1 = new global::Gtk.Table (((uint)(3)), ((uint)(5)), false);
			this.table1.Name = "table1";
			this.table1.RowSpacing = ((uint)(6));
			this.table1.ColumnSpacing = ((uint)(6));
			this.table1.BorderWidth = ((uint)(6));
			// Container child table1.Gtk.Table+TableChild
			this.btnAplicarEsc = new global::Gtk.Button ();
			this.btnAplicarEsc.CanFocus = true;
			this.btnAplicarEsc.Name = "btnAplicarEsc";
			this.btnAplicarEsc.UseStock = true;
			this.btnAplicarEsc.UseUnderline = true;
			this.btnAplicarEsc.Label = "gtk-apply";
			this.table1.Add (this.btnAplicarEsc);
			global::Gtk.Table.TableChild w1 = ((global::Gtk.Table.TableChild)(this.table1 [this.btnAplicarEsc]));
			w1.TopAttach = ((uint)(2));
			w1.BottomAttach = ((uint)(3));
			w1.LeftAttach = ((uint)(3));
			w1.RightAttach = ((uint)(4));
			w1.XOptions = ((global::Gtk.AttachOptions)(4));
			w1.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Nombre mesa");
			this.hbox1.Add (this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.txtNombre = new global::Gtk.Entry ();
			this.txtNombre.WidthRequest = 256;
			this.txtNombre.CanFocus = true;
			this.txtNombre.Name = "txtNombre";
			this.txtNombre.IsEditable = true;
			this.txtNombre.InvisibleChar = '●';
			this.hbox1.Add (this.txtNombre);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.txtNombre]));
			w3.Position = 1;
			this.table1.Add (this.hbox1);
			global::Gtk.Table.TableChild w4 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox1]));
			w4.TopAttach = ((uint)(1));
			w4.BottomAttach = ((uint)(2));
			w4.XOptions = ((global::Gtk.AttachOptions)(4));
			w4.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Ref para el camarero");
			this.hbox2.Add (this.label4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.label4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.txtRef = new global::Gtk.Entry ();
			this.txtRef.WidthRequest = 256;
			this.txtRef.CanFocus = true;
			this.txtRef.Name = "txtRef";
			this.txtRef.IsEditable = true;
			this.txtRef.InvisibleChar = '●';
			this.hbox2.Add (this.txtRef);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.txtRef]));
			w6.Position = 1;
			this.table1.Add (this.hbox2);
			global::Gtk.Table.TableChild w7 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox2]));
			w7.TopAttach = ((uint)(2));
			w7.BottomAttach = ((uint)(3));
			w7.XOptions = ((global::Gtk.AttachOptions)(4));
			w7.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Zonas editada");
			this.hbox4.Add (this.label2);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.label2]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.cmbZonas = global::Gtk.ComboBox.NewText ();
			this.cmbZonas.WidthRequest = 262;
			this.cmbZonas.Name = "cmbZonas";
			this.hbox4.Add (this.cmbZonas);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.cmbZonas]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.btnAñadirZona = new global::Gtk.Button ();
			this.btnAñadirZona.CanFocus = true;
			this.btnAñadirZona.Name = "btnAñadirZona";
			this.btnAñadirZona.UseUnderline = true;
			// Container child btnAñadirZona.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Menu);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w11.Add (w14);
			w10.Add (w11);
			this.btnAñadirZona.Add (w10);
			this.hbox4.Add (this.btnAñadirZona);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.btnAñadirZona]));
			w18.Position = 2;
			w18.Expand = false;
			w18.Fill = false;
			this.table1.Add (this.hbox4);
			global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbox4]));
			w19.XOptions = ((global::Gtk.AttachOptions)(4));
			w19.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.hbuttonbox1 = new global::Gtk.HButtonBox ();
			this.hbuttonbox1.Name = "hbuttonbox1";
			this.hbuttonbox1.Homogeneous = true;
			this.hbuttonbox1.Spacing = 9;
			this.hbuttonbox1.BorderWidth = ((uint)(7));
			this.hbuttonbox1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnLimpiar = new global::Gtk.Button ();
			this.btnLimpiar.CanFocus = true;
			this.btnLimpiar.Name = "btnLimpiar";
			this.btnLimpiar.UseUnderline = true;
			// Container child btnLimpiar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w20 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w21 = new global::Gtk.HBox ();
			w21.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w22 = new global::Gtk.Image ();
			w22.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-clear", global::Gtk.IconSize.Menu);
			w21.Add (w22);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w24 = new global::Gtk.Label ();
			w24.LabelProp = global::Mono.Unix.Catalog.GetString ("Limiar plano");
			w24.UseUnderline = true;
			w21.Add (w24);
			w20.Add (w21);
			this.btnLimpiar.Add (w20);
			this.hbuttonbox1.Add (this.btnLimpiar);
			global::Gtk.ButtonBox.ButtonBoxChild w28 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnLimpiar]));
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbuttonbox1.Gtk.ButtonBox+ButtonBoxChild
			this.btnRotarDibujo = new global::Gtk.Button ();
			this.btnRotarDibujo.HeightRequest = 50;
			this.btnRotarDibujo.CanFocus = true;
			this.btnRotarDibujo.Name = "btnRotarDibujo";
			this.btnRotarDibujo.UseUnderline = true;
			// Container child btnRotarDibujo.Gtk.Container+ContainerChild
			global::Gtk.Alignment w29 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w30 = new global::Gtk.HBox ();
			w30.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w31 = new global::Gtk.Image ();
			w31.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_3d-normals-flip-illumination", global::Gtk.IconSize.Menu);
			w30.Add (w31);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w33 = new global::Gtk.Label ();
			w33.LabelProp = global::Mono.Unix.Catalog.GetString ("Rotar imagen");
			w33.UseUnderline = true;
			w30.Add (w33);
			w29.Add (w30);
			this.btnRotarDibujo.Add (w29);
			this.hbuttonbox1.Add (this.btnRotarDibujo);
			global::Gtk.ButtonBox.ButtonBoxChild w37 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox1 [this.btnRotarDibujo]));
			w37.Position = 1;
			w37.Expand = false;
			w37.Fill = false;
			this.table1.Add (this.hbuttonbox1);
			global::Gtk.Table.TableChild w38 = ((global::Gtk.Table.TableChild)(this.table1 [this.hbuttonbox1]));
			w38.TopAttach = ((uint)(1));
			w38.BottomAttach = ((uint)(3));
			w38.LeftAttach = ((uint)(4));
			w38.RightAttach = ((uint)(5));
			// Container child table1.Gtk.Table+TableChild
			this.lblEscalado = new global::Gtk.Label ();
			this.lblEscalado.Name = "lblEscalado";
			this.lblEscalado.LabelProp = global::Mono.Unix.Catalog.GetString ("Escalado mesas");
			this.table1.Add (this.lblEscalado);
			global::Gtk.Table.TableChild w39 = ((global::Gtk.Table.TableChild)(this.table1 [this.lblEscalado]));
			w39.TopAttach = ((uint)(1));
			w39.BottomAttach = ((uint)(2));
			w39.LeftAttach = ((uint)(2));
			w39.RightAttach = ((uint)(3));
			w39.XOptions = ((global::Gtk.AttachOptions)(4));
			w39.YOptions = ((global::Gtk.AttachOptions)(4));
			// Container child table1.Gtk.Table+TableChild
			this.spinEscalado = new global::Gtk.SpinButton (0, 100, 1);
			this.spinEscalado.CanFocus = true;
			this.spinEscalado.Name = "spinEscalado";
			this.spinEscalado.Adjustment.PageIncrement = 10;
			this.spinEscalado.ClimbRate = 1;
			this.spinEscalado.Numeric = true;
			this.spinEscalado.Value = 90;
			this.table1.Add (this.spinEscalado);
			global::Gtk.Table.TableChild w40 = ((global::Gtk.Table.TableChild)(this.table1 [this.spinEscalado]));
			w40.TopAttach = ((uint)(2));
			w40.BottomAttach = ((uint)(3));
			w40.LeftAttach = ((uint)(2));
			w40.RightAttach = ((uint)(3));
			w40.XOptions = ((global::Gtk.AttachOptions)(4));
			w40.YOptions = ((global::Gtk.AttachOptions)(4));
			this.vbox1.Add (this.table1);
			global::Gtk.Box.BoxChild w41 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.table1]));
			w41.Position = 0;
			w41.Expand = false;
			w41.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.AreaDeDibujo = new global::Gtk.EventBox ();
			this.AreaDeDibujo.CanFocus = true;
			this.AreaDeDibujo.Events = ((global::Gdk.EventMask)(2327548));
			this.AreaDeDibujo.Name = "AreaDeDibujo";
			this.AreaDeDibujo.AboveChild = true;
			this.AreaDeDibujo.VisibleWindow = false;
			// Container child AreaDeDibujo.Gtk.Container+ContainerChild
			this.cImgPlano = new global::Gtk.Image ();
			this.cImgPlano.WidthRequest = 900;
			this.cImgPlano.HeightRequest = 375;
			this.cImgPlano.Events = ((global::Gdk.EventMask)(17182));
			this.cImgPlano.ExtensionEvents = ((global::Gdk.ExtensionMode)(1));
			this.cImgPlano.Name = "cImgPlano";
			this.AreaDeDibujo.Add (this.cImgPlano);
			this.vbox1.Add (this.AreaDeDibujo);
			global::Gtk.Box.BoxChild w43 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.AreaDeDibujo]));
			w43.Position = 1;
			w43.Expand = false;
			w43.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.grpModos = new global::Gtk.HButtonBox ();
			this.grpModos.Name = "grpModos";
			this.grpModos.Spacing = 14;
			this.grpModos.BorderWidth = ((uint)(6));
			this.grpModos.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnTexto = new global::Gtk.Button ();
			this.btnTexto.CanFocus = true;
			this.btnTexto.Name = "btnTexto";
			this.btnTexto.UseUnderline = true;
			// Container child btnTexto.Gtk.Container+ContainerChild
			global::Gtk.Alignment w44 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w45 = new global::Gtk.HBox ();
			w45.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w46 = new global::Gtk.Image ();
			w46.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_data-table", global::Gtk.IconSize.Menu);
			w45.Add (w46);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w48 = new global::Gtk.Label ();
			w48.LabelProp = global::Mono.Unix.Catalog.GetString ("Texto");
			w48.UseUnderline = true;
			w45.Add (w48);
			w44.Add (w45);
			this.btnTexto.Add (w44);
			this.grpModos.Add (this.btnTexto);
			global::Gtk.ButtonBox.ButtonBoxChild w52 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnTexto]));
			w52.Expand = false;
			w52.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnAceptar = new global::Gtk.Button ();
			this.btnAceptar.CanFocus = true;
			this.btnAceptar.Name = "btnAceptar";
			this.btnAceptar.UseStock = true;
			this.btnAceptar.UseUnderline = true;
			this.btnAceptar.Label = "gtk-ok";
			this.grpModos.Add (this.btnAceptar);
			global::Gtk.ButtonBox.ButtonBoxChild w53 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnAceptar]));
			w53.Position = 1;
			w53.Expand = false;
			w53.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnEditar = new global::Gtk.Button ();
			this.btnEditar.CanFocus = true;
			this.btnEditar.Name = "btnEditar";
			this.btnEditar.UseUnderline = true;
			// Container child btnEditar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w54 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w55 = new global::Gtk.HBox ();
			w55.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w56 = new global::Gtk.Image ();
			w56.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "stock_effects", global::Gtk.IconSize.Menu);
			w55.Add (w56);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w58 = new global::Gtk.Label ();
			w58.LabelProp = global::Mono.Unix.Catalog.GetString ("Editar");
			w58.UseUnderline = true;
			w55.Add (w58);
			w54.Add (w55);
			this.btnEditar.Add (w54);
			this.grpModos.Add (this.btnEditar);
			global::Gtk.ButtonBox.ButtonBoxChild w62 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnEditar]));
			w62.Position = 2;
			w62.Expand = false;
			w62.Fill = false;
			// Container child grpModos.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w63 = new global::Gtk.Alignment (0.5F, 0.5F, 0F, 0F);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w64 = new global::Gtk.HBox ();
			w64.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w65 = new global::Gtk.Image ();
			w65.Pixbuf = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./Iconos/EXIT00C.ICO"));
			w64.Add (w65);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w67 = new global::Gtk.Label ();
			w67.LabelProp = global::Mono.Unix.Catalog.GetString ("Salir");
			w67.UseUnderline = true;
			w64.Add (w67);
			w63.Add (w64);
			this.btnSalir.Add (w63);
			this.grpModos.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w71 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.grpModos [this.btnSalir]));
			w71.Position = 3;
			w71.Expand = false;
			w71.Fill = false;
			this.vbox1.Add (this.grpModos);
			global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.grpModos]));
			w72.Position = 2;
			w72.Expand = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblInformacion = new global::Gtk.Label ();
			this.lblInformacion.Name = "lblInformacion";
			this.lblInformacion.Xalign = 0F;
			this.lblInformacion.LabelProp = global::Mono.Unix.Catalog.GetString ("Modo no editable activado");
			this.vbox1.Add (this.lblInformacion);
			global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.lblInformacion]));
			w73.Position = 3;
			w73.Expand = false;
			w73.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 934;
			this.DefaultHeight = 619;
			this.btnAceptar.Hide ();
			this.vbox1.HasDefault = true;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.btnLimpiar.Clicked += new global::System.EventHandler (this.OnBtnLimpiarClicked);
			this.btnRotarDibujo.Clicked += new global::System.EventHandler (this.OnBtnRotarDibujoClicked);
			this.cmbZonas.Changed += new global::System.EventHandler (this.OnCmbZonasChanged);
			this.btnAñadirZona.Clicked += new global::System.EventHandler (this.OnBtnAñadirZonaClicked);
			this.txtRef.Activated += new global::System.EventHandler (this.OnTxtRefActivated);
			this.txtNombre.Activated += new global::System.EventHandler (this.OnTxtNombreActivated);
			this.btnAplicarEsc.Clicked += new global::System.EventHandler (this.OnButton351Clicked);
			this.AreaDeDibujo.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnAreaDeDibujoButtonPressEvent);
			this.AreaDeDibujo.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnAreaDeDibujoMotionNotifyEvent);
			this.AreaDeDibujo.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnAreaDeDibujoButtonReleaseEvent);
			this.cImgPlano.MotionNotifyEvent += new global::Gtk.MotionNotifyEventHandler (this.OnAreaDeDibujoMotionNotifyEvent);
			this.cImgPlano.ButtonReleaseEvent += new global::Gtk.ButtonReleaseEventHandler (this.OnAreaDeDibujoButtonReleaseEvent);
			this.cImgPlano.ButtonPressEvent += new global::Gtk.ButtonPressEventHandler (this.OnAreaDeDibujoButtonPressEvent);
			this.btnTexto.Clicked += new global::System.EventHandler (this.OnBtnTextoClicked);
			this.btnAceptar.Clicked += new global::System.EventHandler (this.OnBtnAceptarClicked);
			this.btnEditar.Clicked += new global::System.EventHandler (this.OnBtnEditarClicked);
			this.btnSalir.Clicked += new global::System.EventHandler (this.OnBtnSalirClicked);
		}
	}
}
