
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.TpvFinal
{
	public partial class ImprimirTicket
	{
		private global::Gtk.VBox vbox1;

		private global::Valle.GtkUtilidades.MiLabel lblTitulo;

		private global::Gtk.HBox pnePrimcipal;

		private global::Gtk.VBox vbox5;

		private global::Valle.GtkUtilidades.MiLabel lblInfOriginal;

		private global::Gtk.HBox hbox4;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView lstListadoTicket;

		private global::Valle.GtkUtilidades.ScrollTactil scroolOriginal;

		private global::Gtk.VBox vbox7;

		private global::Valle.GtkUtilidades.MiLabel lblInfSelcecionados;

		private global::Gtk.HBox hbox5;

		private global::Gtk.ScrolledWindow GtkScrolledWindow1;

		private global::Gtk.TextView txtTicketInf;

		private global::Valle.GtkUtilidades.ScrollTactil scrollSeleccionados;

		private global::Gtk.HButtonBox hbuttonbox2;

		private global::Gtk.Button btnTicket;

		private global::Gtk.Button btnInfTicket;

		private global::Gtk.VBox vbox161;

		private global::Gtk.Image image28;

		private global::Gtk.Button btnImprimir;

		private global::Gtk.VBox vbox160;

		private global::Gtk.Image image27;

		private global::Gtk.Button btnMas;

		private global::Gtk.VBox vbox159;

		private global::Gtk.Image image26;

		private global::Gtk.Label label1;

		private global::Gtk.Button btnAceptar;

		private global::Gtk.Button btnSalir;

		private global::Gtk.ProgressBar barImformacion;

		protected virtual void Init ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.TpvFinal.ImprimirTicket
			this.Name ="Valle.Tpv.iconos.ImprimirTicket";
			this.Title = global::Mono.Unix.Catalog.GetString ("ImprimirTicket");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Valle.TpvFinal.ImprimirTicket.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblTitulo = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblTitulo.HeightRequest = 25;
			this.lblTitulo.Events = ((global::Gdk.EventMask)(256));
			this.lblTitulo.Name = "lblTitulo";
			this.vbox1.Add (this.lblTitulo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblTitulo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.pnePrimcipal = new global::Gtk.HBox ();
			this.pnePrimcipal.Name = "pnePrimcipal";
			this.pnePrimcipal.Spacing = 6;
			this.pnePrimcipal.BorderWidth = ((uint)(15));
			// Container child pnePrimcipal.Gtk.Box+BoxChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.lblInfOriginal = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblInfOriginal.HeightRequest = 25;
			this.lblInfOriginal.Events = ((global::Gdk.EventMask)(256));
			this.lblInfOriginal.Name = "lblInfOriginal";
			this.vbox5.Add (this.lblInfOriginal);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.lblInfOriginal]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.WidthRequest = 350;
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.lstListadoTicket = new global::Gtk.TreeView ();
			this.lstListadoTicket.CanFocus = true;
			this.lstListadoTicket.Name = "lstListadoTicket";
			this.GtkScrolledWindow.Add (this.lstListadoTicket);
			this.hbox4.Add (this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.GtkScrolledWindow]));
			w4.Position = 0;
			// Container child hbox4.Gtk.Box+BoxChild
			this.scroolOriginal = new global::Valle.GtkUtilidades.ScrollTactil ();
			this.scroolOriginal.Events = ((global::Gdk.EventMask)(256));
			this.scroolOriginal.Name = "scroolOriginal";
			this.hbox4.Add (this.scroolOriginal);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.scroolOriginal]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox5.Add (this.hbox4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.hbox4]));
			w6.Position = 1;
			this.pnePrimcipal.Add (this.vbox5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.pnePrimcipal[this.vbox5]));
			w7.Position = 0;
			// Container child pnePrimcipal.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox ();
			this.vbox7.WidthRequest = 350;
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.lblInfSelcecionados = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblInfSelcecionados.HeightRequest = 25;
			this.lblInfSelcecionados.Events = ((global::Gdk.EventMask)(256));
			this.lblInfSelcecionados.Name = "lblInfSelcecionados";
			this.vbox7.Add (this.lblInfSelcecionados);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.lblInfSelcecionados]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.txtTicketInf = new global::Gtk.TextView ();
			this.txtTicketInf.CanFocus = true;
			this.txtTicketInf.Name = "txtTicketInf";
			this.GtkScrolledWindow1.Add (this.txtTicketInf);
			this.hbox5.Add (this.GtkScrolledWindow1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.GtkScrolledWindow1]));
			w10.Position = 0;
			// Container child hbox5.Gtk.Box+BoxChild
			this.scrollSeleccionados = new global::Valle.GtkUtilidades.ScrollTactil ();
			this.scrollSeleccionados.Events = ((global::Gdk.EventMask)(256));
			this.scrollSeleccionados.Name = "scrollSeleccionados";
			this.hbox5.Add (this.scrollSeleccionados);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.scrollSeleccionados]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox7.Add (this.hbox5);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w12.Position = 1;
			this.pnePrimcipal.Add (this.vbox7);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.pnePrimcipal[this.vbox7]));
			w13.Position = 1;
			this.vbox1.Add (this.pnePrimcipal);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.pnePrimcipal]));
			w14.Position = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbuttonbox2 = new global::Gtk.HButtonBox ();
			this.hbuttonbox2.Name = "hbuttonbox2";
			this.hbuttonbox2.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnTicket = new global::Gtk.Button ();
			this.btnTicket.CanFocus = true;
			this.btnTicket.Name = "btnTicket";
			this.btnTicket.UseUnderline = true;
			// Container child btnTicket.Gtk.Container+ContainerChild
			global::Gtk.Alignment w15 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w16 = new global::Gtk.HBox ();
			w16.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w17 = new global::Gtk.Image ();
			w17.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "gtk-index", global::Gtk.IconSize.Dialog);
			w16.Add (w17);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w19 = new global::Gtk.Label ();
			w16.Add (w19);
			w15.Add (w16);
			this.btnTicket.Add (w15);
			this.hbuttonbox2.Add (this.btnTicket);
			global::Gtk.ButtonBox.ButtonBoxChild w23 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnTicket]));
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnInfTicket = new global::Gtk.Button ();
			this.btnInfTicket.CanFocus = true;
			this.btnInfTicket.Name = "btnInfTicket";
			// Container child btnInfTicket.Gtk.Container+ContainerChild
			this.vbox161 = new global::Gtk.VBox ();
			this.vbox161.Name = "vbox161";
			this.vbox161.Spacing = 7;
			// Container child vbox161.Gtk.Box+BoxChild
			this.image28 = new global::Gtk.Image ();
			this.image28.Name = "image28";
			this.image28.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "stock_dialog-info", global::Gtk.IconSize.Dialog);
			this.vbox161.Add (this.image28);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox161[this.image28]));
			w24.Position = 0;
			this.btnInfTicket.Add (this.vbox161);
			this.btnInfTicket.Label = null;
			this.hbuttonbox2.Add (this.btnInfTicket);
			global::Gtk.ButtonBox.ButtonBoxChild w26 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnInfTicket]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnImprimir = new global::Gtk.Button ();
			this.btnImprimir.CanFocus = true;
			this.btnImprimir.Name = "btnImprimir";
			// Container child btnImprimir.Gtk.Container+ContainerChild
			this.vbox160 = new global::Gtk.VBox ();
			this.vbox160.Name = "vbox160";
			this.vbox160.Spacing = 7;
			// Container child vbox160.Gtk.Box+BoxChild
			this.image27 = new global::Gtk.Image ();
			this.image27.Name = "image27";
			this.image27.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "gtk-print-preview", global::Gtk.IconSize.Dialog);
			this.vbox160.Add (this.image27);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox160[this.image27]));
			w27.Position = 0;
			this.btnImprimir.Add (this.vbox160);
			this.btnImprimir.Label = null;
			this.btnImprimir.HeightRequest=100;
			this.btnImprimir.WidthRequest=100;
			this.hbuttonbox2.Add (this.btnImprimir);
			global::Gtk.ButtonBox.ButtonBoxChild w29 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnImprimir]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnMas = new global::Gtk.Button ();
			this.btnMas.CanFocus = true;
			this.btnMas.Name = "btnMas";
			// Container child btnMas.Gtk.Container+ContainerChild
			this.vbox159 = new global::Gtk.VBox ();
			this.vbox159.Name = "vbox159";
			this.vbox159.Spacing = 7;
			// Container child vbox159.Gtk.Box+BoxChild
			this.image26 = new global::Gtk.Image ();
			this.image26.Name = "image26";
			this.image26.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "gtk-add", global::Gtk.IconSize.Dialog);
			this.vbox159.Add (this.image26);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.vbox159[this.image26]));
			w30.Position = 0;
			// Container child vbox159.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("   <big>Mas</big>\n<small>Facturas</small>");
			this.label1.UseMarkup = true;
			this.vbox159.Add (this.label1);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox159[this.label1]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			this.btnMas.Add (this.vbox159);
			this.btnMas.Label = null;
			this.hbuttonbox2.Add (this.btnMas);
			global::Gtk.ButtonBox.ButtonBoxChild w33 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnMas]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnAceptar = new global::Gtk.Button ();
			this.btnAceptar.WidthRequest = 100;
			this.btnAceptar.HeightRequest = 100;
			this.btnAceptar.CanFocus = true;
			this.btnAceptar.Name = "btnAceptar";
			this.btnAceptar.UseUnderline = true;
			// Container child btnAceptar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w34 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w35 = new global::Gtk.HBox ();
			w35.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w36 = new global::Gtk.Image ();
			w36.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "gtk-apply", global::Gtk.IconSize.Dialog);
			w35.Add (w36);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w38 = new global::Gtk.Label ();
			w35.Add (w38);
			w34.Add (w35);
			this.btnAceptar.Add (w34);
			this.hbuttonbox2.Add (this.btnAceptar);
			global::Gtk.ButtonBox.ButtonBoxChild w42 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnAceptar]));
			w42.Position = 4;
			w42.Expand = false;
			w42.Fill = false;
			// Container child hbuttonbox2.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w43 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w44 = new global::Gtk.HBox ();
			w44.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w45 = new global::Gtk.Image ();
			w45.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Dialog);
			w44.Add (w45);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w47 = new global::Gtk.Label ();
			w44.Add (w47);
			w43.Add (w44);
			this.btnSalir.Add (w43);
			this.hbuttonbox2.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w51 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.hbuttonbox2[this.btnSalir]));
			w51.Position = 5;
			w51.Expand = false;
			w51.Fill = false;
			this.vbox1.Add (this.hbuttonbox2);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbuttonbox2]));
			w52.Position = 2;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.barImformacion = new global::Gtk.ProgressBar ();
			this.barImformacion.Name = "barImformacion";
			this.vbox1.Add (this.barImformacion);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.barImformacion]));
			w53.Position = 3;
			w53.Expand = false;
			w53.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 754;
			this.DefaultHeight = 536;
			btnAceptar.Visible = false;
			lstListadoTicket.CursorChanged += new System.EventHandler(lstListadoTicket_SelectedIndexChanged);
			btnSalir.Clicked += new System.EventHandler(btnSalir_Click);
			btnMas.Clicked += new System.EventHandler(btnMasFacturas_Click);
			btnImprimir.Clicked += new System.EventHandler(btnImprimir_Click);
			btnTicket.Clicked +=new System.EventHandler(btnTicketClick);
			btnInfTicket.Clicked += new System.EventHandler(BtnEstadisticaClick);
			
		}
	}
}
