
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.TpvFinal
{
	public partial class SelectorDeMesas
	{
		private global::Gtk.VBox vbox1;

		private global::Valle.GtkUtilidades.MiLabel lblTitulo;

		private global::Gtk.HBox hbox1;

		private global::Gtk.HButtonBox pneBtnHerr;

		private global::Gtk.Button btnAsociar;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Image image343;

		private global::Gtk.Label label1;

		private global::Gtk.Button btnQuitarAsociacion;

		private global::Gtk.VBox vbox6;

		private global::Gtk.Image image347;

		private global::Gtk.Label label5;

		private global::Gtk.Button btnCambiar;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Image image344;

		private global::Gtk.Label label2;

		private global::Gtk.Button btnJuntar;

		private global::Gtk.VBox vbox4;

		private global::Gtk.Image image345;

		private global::Gtk.Label label3;

		private global::Gtk.Button btnInvitar;

		private global::Gtk.VBox vbox5;

		private global::Gtk.Image image346;

		private global::Gtk.Label label4;

		private global::Gtk.Alignment alignment1;

		private global::Gtk.HButtonBox pneBtnHerr1;

		private global::Gtk.Button btnAbrirCajon;

		private global::Gtk.Button btnSalir;

		private global::Gtk.Button btnCancelar;

		private global::Valle.GtkUtilidades.MiLabel lblInformacion;

		protected virtual void Init ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.TpvFinal.SelectorDeMesas
			this.Name ="Valle.Tpv.iconos.SelectorDeMesas";
			this.Title = global::Mono.Unix.Catalog.GetString ("SelectorDeMesas");
			this.Resizable = false;
			this.AllowGrow = false;
			this.Decorated = false;
			this.SkipTaskbarHint = true;
			// Container child Valle.TpvFinal.SelectorDeMesas.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			this.vbox1.BorderWidth = ((uint)(9));
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblTitulo = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblTitulo.HeightRequest = 25;
			this.lblTitulo.Events = ((global::Gdk.EventMask)(256));
			this.lblTitulo.Name = "lblTitulo";
			this.vbox1.Add (this.lblTitulo);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblTitulo]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.pneBtnHerr = new global::Gtk.HButtonBox ();
			this.pneBtnHerr.Name = "pneBtnHerr";
			this.pneBtnHerr.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child pneBtnHerr.Gtk.ButtonBox+ButtonBoxChild
			this.btnAsociar = new global::Gtk.Button ();
			this.btnAsociar.WidthRequest = 100;
			this.btnAsociar.HeightRequest = 100;
			this.btnAsociar.CanFocus = true;
			this.btnAsociar.Name = "btnAsociar";
			// Container child btnAsociar.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.image343 = new global::Gtk.Image ();
			this.image343.Name = "image343";
			this.image343.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "stock_help-add-bookmark", global::Gtk.IconSize.Dialog);
			this.vbox2.Add (this.image343);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.image343]));
			w2.Position = 0;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Asociar\n Rango");
			this.vbox2.Add (this.label1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label1]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.btnAsociar.Add (this.vbox2);
			this.btnAsociar.Label = null;
			this.pneBtnHerr.Add (this.btnAsociar);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pneBtnHerr[this.btnAsociar]));
			w5.Expand = false;
			w5.Fill = false;
			// Container child pneBtnHerr.Gtk.ButtonBox+ButtonBoxChild
			this.btnQuitarAsociacion = new global::Gtk.Button ();
			this.btnQuitarAsociacion.CanFocus = true;
			this.btnQuitarAsociacion.Name = "btnQuitarAsociacion";
			// Container child btnQuitarAsociacion.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			// Container child vbox6.Gtk.Box+BoxChild
			this.image347 = new global::Gtk.Image ();
			this.image347.Name = "image347";
			this.image347.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "stock_delete", global::Gtk.IconSize.Dialog);
			this.vbox6.Add (this.image347);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.image347]));
			w6.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label ();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("    Quitar\nAsociacion");
			this.vbox6.Add (this.label5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.label5]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			this.btnQuitarAsociacion.Add (this.vbox6);
			this.btnQuitarAsociacion.Label = null;
			this.pneBtnHerr.Add (this.btnQuitarAsociacion);
			global::Gtk.ButtonBox.ButtonBoxChild w9 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pneBtnHerr[this.btnQuitarAsociacion]));
			w9.Position = 1;
			w9.Expand = false;
			w9.Fill = false;
			// Container child pneBtnHerr.Gtk.ButtonBox+ButtonBoxChild
			this.btnCambiar = new global::Gtk.Button ();
			this.btnCambiar.CanFocus = true;
			this.btnCambiar.Name = "btnCambiar";
			// Container child btnCambiar.Gtk.Container+ContainerChild
			this.vbox3 = new global::Gtk.VBox ();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image344 = new global::Gtk.Image ();
			this.image344.Name = "image344";
			this.image344.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "stock_shuffle", global::Gtk.IconSize.Dialog);
			this.vbox3.Add (this.image344);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image344]));
			w10.Position = 0;
			w10.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Cambiar\n   mesa");
			this.vbox3.Add (this.label2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.label2]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			this.btnCambiar.Add (this.vbox3);
			this.btnCambiar.Label = null;
			this.pneBtnHerr.Add (this.btnCambiar);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pneBtnHerr[this.btnCambiar]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child pneBtnHerr.Gtk.ButtonBox+ButtonBoxChild
			this.btnJuntar = new global::Gtk.Button ();
			this.btnJuntar.CanFocus = true;
			this.btnJuntar.Name = "btnJuntar";
			// Container child btnJuntar.Gtk.Container+ContainerChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.image345 = new global::Gtk.Image ();
			this.image345.Name = "image345";
			this.image345.Pixbuf =Gdk.Pixbuf.LoadFromResource("Valle.Tpv.iconos.union.jpeg");
			this.vbox4.Add (this.image345);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.image345]));
			w14.Position = 0;
			w14.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label ();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Juntar\nmesas");
			this.vbox4.Add (this.label3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox4[this.label3]));
			w15.Position = 1;
			w15.Expand = false;
			w15.Fill = false;
			this.btnJuntar.Add (this.vbox4);
			this.btnJuntar.Label = null;
			this.pneBtnHerr.Add (this.btnJuntar);
			global::Gtk.ButtonBox.ButtonBoxChild w17 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pneBtnHerr[this.btnJuntar]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Container child pneBtnHerr.Gtk.ButtonBox+ButtonBoxChild
			this.btnInvitar = new global::Gtk.Button ();
			this.btnInvitar.CanFocus = true;
			this.btnInvitar.Name = "btnInvitar";
			// Container child btnInvitar.Gtk.Container+ContainerChild
			this.vbox5 = new global::Gtk.VBox ();
			this.vbox5.Name = "vbox5";
			this.vbox5.Spacing = 6;
			// Container child vbox5.Gtk.Box+BoxChild
			this.image346 = new global::Gtk.Image ();
			this.image346.Name = "image346";
			this.image346.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "stock_smiley-3", global::Gtk.IconSize.Dialog);
			this.vbox5.Add (this.image346);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.image346]));
			w18.Position = 0;
			w18.Fill = false;
			// Container child vbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label ();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Invitar\nmesa");
			this.vbox5.Add (this.label4);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox5[this.label4]));
			w19.Position = 1;
			w19.Expand = false;
			w19.Fill = false;
			this.btnInvitar.Add (this.vbox5);
			this.btnInvitar.Label = null;
			this.pneBtnHerr.Add (this.btnInvitar);
			global::Gtk.ButtonBox.ButtonBoxChild w21 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pneBtnHerr[this.btnInvitar]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			this.hbox1.Add (this.pneBtnHerr);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.pneBtnHerr]));
			w22.Position = 0;
			// Container child hbox1.Gtk.Box+BoxChild
			this.alignment1 = new global::Gtk.Alignment (0.5f, 0.5f, 1f, 1f);
			this.alignment1.WidthRequest = 100;
			this.alignment1.Name = "alignment1";
			this.hbox1.Add (this.alignment1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.alignment1]));
			w23.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.pneBtnHerr1 = new global::Gtk.HButtonBox ();
			this.pneBtnHerr1.Name = "pneBtnHerr1";
			this.pneBtnHerr1.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child pneBtnHerr1.Gtk.ButtonBox+ButtonBoxChild
			this.btnAbrirCajon = new global::Gtk.Button ();
			this.btnAbrirCajon.WidthRequest = 100;
			this.btnAbrirCajon.HeightRequest = 100;
			this.btnAbrirCajon.CanFocus = true;
			this.btnAbrirCajon.Name = "btnAbrirCajon";
			this.btnAbrirCajon.UseUnderline = true;
			// Container child btnAbrirCajon.Gtk.Container+ContainerChild
			global::Gtk.Alignment w24 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w25 = new global::Gtk.HBox ();
			w25.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w26 = new global::Gtk.Image ();
			w26.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Valle.Tpv.iconos.STARTUP.ICO");
			w25.Add (w26);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w28 = new global::Gtk.Label ();
			w25.Add (w28);
			w24.Add (w25);
			this.btnAbrirCajon.Add (w24);
			this.pneBtnHerr1.Add (this.btnAbrirCajon);
			global::Gtk.ButtonBox.ButtonBoxChild w32 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pneBtnHerr1[this.btnAbrirCajon]));
			w32.Expand = false;
			w32.Fill = false;
			// Container child pneBtnHerr1.Gtk.ButtonBox+ButtonBoxChild
			this.btnSalir = new global::Gtk.Button ();
			this.btnSalir.CanFocus = true;
			this.btnSalir.Name = "btnSalir";
			this.btnSalir.UseUnderline = true;
			// Container child btnSalir.Gtk.Container+ContainerChild
			global::Gtk.Alignment w33 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w34 = new global::Gtk.HBox ();
			w34.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w35 = new global::Gtk.Image ();
			w35.Pixbuf = global::Gdk.Pixbuf.LoadFromResource ("Valle.Tpv.iconos.~APP21MB.ICO");
			w34.Add (w35);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w37 = new global::Gtk.Label ();
			w34.Add (w37);
			w33.Add (w34);
			this.btnSalir.Add (w33);
			this.pneBtnHerr1.Add (this.btnSalir);
			global::Gtk.ButtonBox.ButtonBoxChild w41 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pneBtnHerr1[this.btnSalir]));
			w41.Position = 1;
			w41.Expand = false;
			w41.Fill = false;
			// Container child pneBtnHerr1.Gtk.ButtonBox+ButtonBoxChild
			this.btnCancelar = new global::Gtk.Button ();
			this.btnCancelar.CanFocus = true;
			this.btnCancelar.Name = "btnCancelar";
			this.btnCancelar.HeightRequest = 100;
			this.btnCancelar.WidthRequest=100;
			this.btnCancelar.UseUnderline = true;
			// Container child btnCandelar.Gtk.Container+ContainerChild
			global::Gtk.Alignment w42 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w43 = new global::Gtk.HBox ();
			w43.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w44 = new global::Gtk.Image ();
			w44.Pixbuf = global::Stetic.IconLoaderEx.LoadIcon (this, "gtk-cancel", global::Gtk.IconSize.Dialog);
			w43.Add (w44);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w46 = new global::Gtk.Label ();
			w43.Add (w46);
			w42.Add (w43);
			this.btnCancelar.Add (w42);
			this.pneBtnHerr1.Add (this.btnCancelar);
			global::Gtk.ButtonBox.ButtonBoxChild w50 = ((global::Gtk.ButtonBox.ButtonBoxChild)(this.pneBtnHerr1[this.btnCancelar]));
			w50.Position = 2;
			w50.Expand = true;
			w50.Fill = true;
			this.hbox1.Add (this.pneBtnHerr1);
			global::Gtk.Box.BoxChild w51 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.pneBtnHerr1]));
			w51.Position = 2;
			this.vbox1.Add (this.hbox1);
			global::Gtk.Box.BoxChild w52 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.hbox1]));
			w52.Position = 1;
			w52.Expand = false;
			w52.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.lblInformacion = new global::Valle.GtkUtilidades.MiLabel ();
			this.lblInformacion.HeightRequest = 25;
			this.lblInformacion.Events = ((global::Gdk.EventMask)(256));
			this.lblInformacion.Name = "lblInformacion";
			this.vbox1.Add (this.lblInformacion);
			global::Gtk.Box.BoxChild w53 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.lblInformacion]));
			w53.Position = 2;
			w53.Expand = false;
			w53.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 996;
			this.DefaultHeight = 210;
			this.btnQuitarAsociacion.Hide ();
			this.btnCancelar.Hide ();
		
			this.btnAsociar.Clicked += new global::System.EventHandler (this.OnBtnAsociarClicked);
			this.btnQuitarAsociacion.Clicked += new global::System.EventHandler (this.OnBtnQuitarAsociacionClicked);
			this.btnCambiar.Clicked += new global::System.EventHandler (this.OnBtnCambiarClicked);
			this.btnJuntar.Clicked += new global::System.EventHandler (this.OnBtnJuntarClicked);
			this.btnInvitar.Clicked += new global::System.EventHandler (this.OnBtnInvitarClicked);
			this.btnAbrirCajon.Clicked += new global::System.EventHandler (this.OnBtnAbrirCajonClicked);
			this.btnSalir.Clicked += new global::System.EventHandler (this.btnSalir_Click);
			this.btnCancelar.Clicked += new global::System.EventHandler (this.OnBtnCandelarClicked);
		}
	}
}
