
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GtkUtilidades
{
	public partial class ArbolDeVista
	{
		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.TreeView treeUnico;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GtkUtilidades.ArbolDeVista
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Valle.GtkUtilidades.ArbolDeVista";
			// Container child Valle.GtkUtilidades.ArbolDeVista.Gtk.Container+ContainerChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.treeUnico = new global::Gtk.TreeView ();
			this.treeUnico.CanFocus = true;
			this.treeUnico.Name = "treeUnico";
			this.GtkScrolledWindow.Add (this.treeUnico);
			this.Add (this.GtkScrolledWindow);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Show ();
			this.GtkScrolledWindow.ScrollChild += new global::Gtk.ScrollChildHandler (this.OnGtkScrolledWindowScrollChild);
			this.treeUnico.RowActivated += new global::Gtk.RowActivatedHandler (this.OnTreeUnicoRowActivated);
			this.treeUnico.CursorChanged += new global::System.EventHandler (this.OnTreeUnicoCursorChanged);
		}
	}
}
