
// This file has been generated by the GUI designer. Do not modify.
namespace Valle.GtkUtilidades
{
	public partial class ScrollTactil
	{
		private global::Gtk.VBox vbox6;

		private global::Gtk.Button btnSubirOrg;

		private global::Gtk.Button btnBajarOrg;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget Valle.GtkUtilidades.ScroolTactil
			global::Stetic.BinContainer.Attach (this);
			this.Name = "Valle.GtkUtilidades.ScroolTactil";
			// Container child Valle.GtkUtilidades.ScroolTactil.Gtk.Container+ContainerChild
			this.vbox6 = new global::Gtk.VBox ();
			this.vbox6.Name = "vbox6";
			this.vbox6.Spacing = 6;
			this.vbox6.BorderWidth = ((uint)(3));
			// Container child vbox6.Gtk.Box+BoxChild
			this.btnSubirOrg = new global::Gtk.Button ();
			this.btnSubirOrg.CanFocus = true;
			this.btnSubirOrg.Events = ((global::Gdk.EventMask)(768));
			this.btnSubirOrg.Name = "btnSubirOrg";
			this.btnSubirOrg.UseUnderline = true;
			// Container child btnSubirOrg.Gtk.Container+ContainerChild
			global::Gtk.Alignment w1 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w2 = new global::Gtk.HBox ();
			w2.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w3 = new global::Gtk.Image ();
			w3.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-up", global::Gtk.IconSize.Dialog);
			w2.Add (w3);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w5 = new global::Gtk.Label ();
			w2.Add (w5);
			w1.Add (w2);
			this.btnSubirOrg.Add (w1);
			this.vbox6.Add (this.btnSubirOrg);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.btnSubirOrg]));
			w9.Position = 0;
			// Container child vbox6.Gtk.Box+BoxChild
			this.btnBajarOrg = new global::Gtk.Button ();
			this.btnBajarOrg.CanFocus = true;
			this.btnBajarOrg.Name = "btnBajarOrg";
			this.btnBajarOrg.UseUnderline = true;
			// Container child btnBajarOrg.Gtk.Container+ContainerChild
			global::Gtk.Alignment w10 = new global::Gtk.Alignment (0.5f, 0.5f, 0f, 0f);
			// Container child GtkAlignment.Gtk.Container+ContainerChild
			global::Gtk.HBox w11 = new global::Gtk.HBox ();
			w11.Spacing = 2;
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Image w12 = new global::Gtk.Image ();
			w12.Pixbuf = global::Stetic.IconLoader.LoadIcon (this, "gtk-go-down", global::Gtk.IconSize.Dialog);
			w11.Add (w12);
			// Container child GtkHBox.Gtk.Container+ContainerChild
			global::Gtk.Label w14 = new global::Gtk.Label ();
			w11.Add (w14);
			w10.Add (w11);
			this.btnBajarOrg.Add (w10);
			this.vbox6.Add (this.btnBajarOrg);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox6[this.btnBajarOrg]));
			w18.Position = 1;
			this.Add (this.vbox6);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.Hide ();
			this.btnSubirOrg.Pressed += new global::System.EventHandler (this.OnBtnSubirOrgPressed);
			this.btnSubirOrg.Released += new global::System.EventHandler (this.OnBtnSubirOrgReleased);
			this.btnBajarOrg.Pressed += new global::System.EventHandler (this.OnBtnBajarOrgPressed);
			this.btnBajarOrg.Released += new global::System.EventHandler (this.OnBtnBajarOrgReleased);
		}
	}
}
